### ISSUE TITLE
CQL Engine fails to parse incorrect String, however does not throw any exception.

### ISSUE THREAD

**Issue by umeshprasad123** [cqframework/clinical_quality_language#1018]
Question : Why doesn't CQL engine throws CQL Exception in every instance of incorrect string value ? 

User case 1 : Following throws CQL Translation exception  
CQL : 
define itemsStr: '{\"items\":\" \
define endItem: '\}'

Console log : 
line 13:17 token recognition error at: '\'
line 13:19 token recognition error at: ''\r\n'
Translation failed due to errors:
[13:18, 13:18] Syntax error at }

Use case 2 : Following does **not** throw CQL Translation exception.
CQL : 
define itemsStr: '{\"items\":\" \
define endItem: '\"}'

Console log :
line 13:17 token recognition error at: '\'
line 13:18 token recognition error at: '"}'\r\n'

Please note only difference between Use case 1 and 2 is in expression **endItem** use case 2 has **"** 

On further debugging found that String validation failure is being reported from following code
Class : org.cqframework.cql.gen.cqlParser.java
	// Generated from cql.g4 by ANTLR 4.5
	package org.cqframework.cql.gen.cqlParser
Method : library()
public final LibraryContext library() throws RecognitionException {

Line# : 348 
Code : while (_la==T__26 || _la==T__27) {

**Comment by JPercival** [comment]
Closing due to lack of response from reporter.
