### ISSUE TITLE
cql-to-elm translator comment newlines being lost in some cases

### ISSUE THREAD

**Issue by nmorasb** [cqframework/clinical_quality_language#1109]
We are using the cql-to-elm library and have observed that when combining styles of comments the newline after the last comment is lost, causing issues with downstream consumers of the generated ELM.
CQL:
```
library ObsTestN1 version '0.0.000'

using FHIR version '4.0.1'


include FHIRHelpers version '4.1.000' called FHIRHelpers

parameter "Measurement Period" Interval<DateTime>

context Patient

/* Multi-line works fine */
// Single-line comment does not work
define "boolIpp":
  exists ["Encounter"] E where E.period.start during "Measurement Period"
```

Here are some screenshots of the issue as observed after passing the ELM to fqm-execution:
<img width="716" alt="Screen Shot 2023-01-06 at 11 25 59 AM" src="https://user-images.githubusercontent.com/94391996/211061010-e9fa4cff-b7d6-4095-a722-da312cb4be08.png">

<img width="671" alt="Screen Shot 2023-01-06 at 11 25 40 AM" src="https://user-images.githubusercontent.com/94391996/211061044-bc22744e-eafe-4f60-b74d-e0b01ea63def.png">

The issue is not observed when comment styles are not mixed:
<img width="966" alt="Screen Shot 2023-01-06 at 11 25 09 AM" src="https://user-images.githubusercontent.com/94391996/211061196-e5794db9-63b7-4e94-b34c-500690ec080e.png">

The issue is also not observed if a multi-line comment comes after the single-line comments:
<img width="695" alt="Screen Shot 2023-01-06 at 11 26 34 AM" src="https://user-images.githubusercontent.com/94391996/211061276-223cda13-04db-40f1-a56c-1bf1ba1be864.png">

These screenshots were all coming from fqm-execution library output, but we can see here the actual cql-to-elm output where the newline character is being lost:
<img width="727" alt="image" src="https://user-images.githubusercontent.com/94391996/211061538-030481f4-cdf8-4bc5-8919-f3f0a0eb1c75.png">

versus what appears when we only use single-line comment style:
<img width="692" alt="image" src="https://user-images.githubusercontent.com/94391996/211061690-d101bbde-edd5-4986-b386-5c49e571192a.png">

Adding @JSRankins here as well

**Comment by brynrhodes** [comment]
Included in 2.11.0
