### ISSUE TITLE
Add signature consideration to FunctionRefEvaluator

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/clinical_quality_language#1128]
The FunctionRefEvaluator currently considers only the declared and runtime signatures for function resolution. Update the evaluator to take advantage of the signature element if it is present (representing the compile-time resolution of the function).

This is related to this translator issue: https://github.com/cqframework/clinical_quality_language/issues/1127
And this evaluator issue: https://github.com/cqframework/clinical-reasoning/issues/244

**Comment by mdnazmulkarim** [comment]
Done
