### ISSUE TITLE
FunctionRefs to Overloaded Functions

### ISSUE THREAD

**Issue by cmoesel** [cqframework/clinical_quality_language#113]
CQL/ELM allows for the overloading of functions.  For example:
```
define function MostRecent(ObsList List<Observation>):
  Last(ObsList O sort by O.issued)

define function MostRecent(CondList List<Condition>):
  Last(CondList C sort by C.effectiveDateTime)
```

This is a great feature, but can be difficult to implement in an execution environment because when it is used, the FunctionRef in ELM does not indicate _which_ of the overloaded functions to use:
```
{
  "name" : "MostRecent",
  "type" : "FunctionRef",
  "operand" : [ {
    "name" : "LDLTests",
    "type" : "ExpressionRef"
  } ]
}
``` 

Implementors need to analyze the chain of expressions behind each operand to infer the return types of each before they can choose the correct version of the function to invoke.  Given that the CQL-to-ELM already has to do this inference when validating the CQL, it would be helpful if it used that information to generate more specific ELM function invocations.  Perhaps something like:
```
{
  "name" : "MostRecent",
  "type" : "FunctionRef",
  "operandTypeSpecifiers" : [ {
    "type" : "ListTypeSpecifier",
    "elementType" : {
      "name" : "{http://hl7.org/fhir}Observation",
      "type" : "NamedTypeSpecifier"
    }
  } ]
  "operand" : [ {
    "name" : "LDLTests",
    "type" : "ExpressionRef"
  } ]
}
``` 

Or when you define a FunctionDef in ELM, give it a unique local identifier that is a hash of the argument types, and then reference that in the FunctionRef as well.  In this way, the FunctionRef might look more like:
```
{
  "name" : "MostRecent",
  "type" : "FunctionRef",
  "functionIdentifier": "2f68523b6f0738c8194d6d76e9ffdb30",
  "operand" : [ {
    "name" : "LDLTests",
    "type" : "ExpressionRef"
  } ]
}
```

**Comment by cmoesel** [comment]
Of course, another alternative, that I think has been discussed before, would be to have every ELM element declare its return type.  Then we'd just need to look at the top level of each operand to determine what the argument type is.

**Comment by brynrhodes** [comment]
Overloads in FunctionRefs do require implementations to resolve overloads, and I agree that's a problem. A function identifier is a good potential solution that would preserve ELM not requiring type information, we should think about that a little more. However, the 1.2 translator now has an option to include return type information as part of the ELM output.

**Comment by brynrhodes** [comment]
This should be submitted as an STU comment against the CQL specification for further discussion and resolution.

**Comment by brynrhodes** [comment]
Submitted comment [1432](http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=1432)
