### ISSUE TITLE
QI-Core 4.1.1 primary code path issues

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#1134]
The primary code path provided for the AdverseEvent type in the [QI-Core Model Info file v 4.1.1](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/quick/src/main/resources/org/hl7/fhir/qicore-modelinfo-4.1.1.xml) is provided as 'type'. 

`
  <typeInfo xsi:type="ClassInfo" baseType="QICore.DomainResource" namespace="QICore" name="AdverseEvent" identifier="http://hl7.org/fhir/us/qicore/StructureDefinition/qicore-adverseevent" label="AdverseEvent" retrievable="true" primaryCodePath="type">
`

However, the 'type' attribute does not exist for AdverseEvent.

Also, the primary code path provided for the DeviceUseStatement type in the [QI-Core Model Info file v 4.1.1](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/quick/src/main/resources/org/hl7/fhir/qicore-modelinfo-4.1.1.xml) is provided as 'device.code', but device.code does not exist.

`   <typeInfo xsi:type="ClassInfo" baseType="QICore.DomainResource" namespace="QICore" name="DeviceUseStatement" identifier="http://hl7.org/fhir/us/qicore/StructureDefinition/qicore-deviceusestatement" label="DeviceUseStatement" retrievable="true" primaryCodePath="device.code">
`

**Comment by brynrhodes** [comment]
Fixed in 2.7.0
