### ISSUE TITLE
QI-Core 4.1.1 MedicationNotRequested Reason Code Mapping

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#1136]
After discussion with @brynrhodes and @mgramigna, there is agreement that there is an issue in how reasonCode is getting mapped to ELM for the MedicationNotRequested datatype in QI-Core 4.1.1. The [QI-Core Model Info File 4.1.1](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/quick/src/main/resources/org/hl7/fhir/qicore-modelinfo-4.1.1.xml) restricts reasonCode to cardinality of 1..1 for MedicationNotRequested based on the [QICoreMedicationNotRequested ](http://hl7.org/fhir/us/qicore/StructureDefinition-qicore-mednotrequested.html) profile. However, the MedicationRequest resource's reasonCode normally has cardinality of 0..*.

Since ELM is supposed to contain FHIR equivalent as if FHIR is what was being used to author in, reasonCode output should be similar between MedicationRequest v MedicationNotRequested when similar structures are used. They aren't. Refer to the CQL and ELM in the attached zip.

**@mgramigna's findings**
My take on the issue is that I think Stan’s instincts are correct. I believe that when restricting something that is 0..* to 1..1, the property still must be an array, but it will only have one element (this can be verified using the IG publisher and looking at the examples in the QI Core IG). It looks like the translator/ModelInfo thinks that “reasonCode” on a “MedicationNotRequested” is just a CodeableConcept rather than a list of CodeableConcepts. Here are some CQL snippets and data types from the cql language server that I created to confirm this:
 
![image](https://user-images.githubusercontent.com/8303773/224427674-10bd199a-1f5d-4f8f-8755-6c5b81e1c0e2.png)

![image](https://user-images.githubusercontent.com/8303773/224427709-ce4250ac-721d-45ea-be9b-97b5e22d8e7c.png)

reasonCode is a list of Concepts as expected. Now for MedicationNotRequested:

![image](https://user-images.githubusercontent.com/8303773/224427751-8e85cbd3-1023-471f-8d8e-42c8cd2faa65.png)
 
![image](https://user-images.githubusercontent.com/8303773/224427793-5fd8d2df-e743-42dc-b0a3-c6ab56a5d6c5.png)

In the MedicationNotRequsted case, the ModelInfo thinks that reasonCode is just one Concept, whereas I think it should be a list of just one Concept? (not sure how the communication between the cardinality constraint and the ModelInfo works in this instance). 

**@brynrhodes feedback**
Looking at the output ELM, yes, that is correct, the translator is considering the reasonCode a singular element, rather than a list of one. Can you submit this as an issue to the CQL translator repository and I will get it addressed.

Stan, you are correct, the ELM engines should be able to run profile-informed CQL without needing to consider the profiles (other than the profile markers in the resources at the data access layer), so this is something that the translator should be accounting for.

[ABCTest.zip](https://github.com/cqframework/clinical_quality_language/files/10946050/ABCTest.zip)

**Comment by mgramigna** [comment]
Likely relevant parts of ModelInfo:

[MedicationRequest reasonCode](https://github.com/cqframework/clinical_quality_language/blob/c1e1beefe119200a04a71543797f5f10601e28f9/Src/java/quick/src/main/resources/org/hl7/fhir/qicore-modelinfo-4.1.1.xml#L3143) has a `ListTypeSpecifier`

[MedicationNotRequested reasonCode](https://github.com/cqframework/clinical_quality_language/blob/c1e1beefe119200a04a71543797f5f10601e28f9/Src/java/quick/src/main/resources/org/hl7/fhir/qicore-modelinfo-4.1.1.xml#L3059) doesn't

**Comment by brynrhodes** [comment]
Fixed in 2.7.0
