### ISSUE TITLE
Translator is not expanding mappings when unions of different FHIR resources occur in CQL

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#1151]
The Translator is not expanding mappings when unions of different FHIR resources occur in CQL. Refer to https://github.com/projecttacoma/fqm-execution/issues/191.

*Recreated per request of ICF. This was initially believed to be resolved as part of 2.7.0 release. But there are remaining issues. cc @jenseeman @brynrhodes

**Comment by JSRankins** [comment]
This is the closed ticket: https://github.com/cqframework/clinical_quality_language/issues/1126

**Comment by brynrhodes** [comment]
I cannot reproduce this behavior, and all the references to issues and CQLIT/BONNIEMAT tickets are closed or indicated as resolved. Is there a reproduction of this issue that I can refer to? The test cases we have in place for this are passing, and as far as I can tell, the measures that were impacted by this issue are passing.

**Comment by JSRankins** [comment]
@brynrhodes I understand the confusion. I opened this issue because I received a request from ICF to do so. I was told there were still issues, because the update that was made for #1126 did not resolve the issue described in https://oncprojectracking.healthit.gov/support/browse/BONNIEMAT-1377. Per comments in ticket, users are no longer having the issue, so I think it is safe to close. CC @jenseeman

**Comment by brynrhodes** [comment]
Great, thank you @JSRankins !
