### ISSUE TITLE
QI-Core Model Info File 4.1.1 DiagnosisPresentOnAdmission

### ISSUE THREAD

**Issue by RohitKandimalla** [cqframework/clinical_quality_language#1152]
[QI-Core Model Info File 4.1.1 ](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/quick/src/main/resources/org/hl7/fhir/qicore-modelinfo-4.1.1.xml) contains the following snippet for Element "DiagnosisPresentOnAdmission"

`<element name="diagnosisPresentOnAdmission" elementType="QICore.DiagnosisPresentOnAdmissionExtension" target=" FHIRHelpers.ToConcept(%parent.diagnosis.extension[url='http://hl7.org/fhir/us/qicore/StructureDefinition/qicore-encounter-diagnosisPresentOnAdmission'].value)" description="onAdmission" definition="Indicator of whether the Encounter diagnosis was present at the time of admission." mustSupport="true"/>`

The target should not be having a "diagnosis", so it should be 

`target="FHIRHelpers.ToConcept(%parent.extension[url='[http://hl7.org/fhir/us/qicore/StructureDefinition/qicore-encounter-diagnosisPresentOnAdmission'].value])"`

Not seeing any runtime error, but This is currently impacting execution results for a user reported in [BONNIEMAT-1400](https://oncprojectracking.healthit.gov/support/browse/BONNIEMAT-1400)

**Comment by brynrhodes** [comment]
Included in release 2.10.0
