### ISSUE TITLE
QICore CommunicationNotDone reasonCode should be a list

### ISSUE THREAD

**Issue by mgramigna** [cqframework/clinical_quality_language#1168]
Offending ModelInfo line: https://github.com/cqframework/clinical_quality_language/blob/bc9e36e9c15085d9d80884b84b7bc0a32c077d27/Src/java/quick/src/main/resources/org/hl7/fhir/qicore-modelinfo-4.1.1.xml#L875

Discussed at connectathon 33 with @brynrhodes

**Comment by birick1** [comment]
Originated from https://github.com/projecttacoma/fqm-execution/issues/222

**Comment by lpawlik2** [comment]
When will this be updated in the translator?

**Comment by brynrhodes** [comment]
This is the same underlying issue as this issue: https://github.com/cqframework/clinical_quality_language/issues/1153 and we are recommending a content-level workaround rather than trying to extend the negation pattern to work with multi-cardinality elements.

**Comment by mgramigna** [comment]
@brynrhodes the issue that sparked this, https://github.com/projecttacoma/fqm-execution/issues/222, I think might be a slightly different use case that the [updated authoring pattern](https://github.com/cqframework/CQL-Formatting-and-Usage-Wiki/wiki/Authoring-Patterns---QICore-v4.1.1#communication-not-done) does not solve. From your response in issue #1153:

> [We recommend] avoiding the use of the reasonCode element directly in the negation pattern for CommunicationNotDone

The specific syntax that sparked the above `fqm-execution` issue was something like this:

```cql
// snip

code "Some Direct Reference Code": '12345' from "some system"

// snip

define "Example":
  [CommunicationNotDone] C 
        where "Some Direct Reference Code" in C.reasonCode
```

This syntax seems to be checking if some specific code exists in the expanded ValueSet referenced by the `.reasonCode` property of some QICore `CommunicationNotDone`. I don't see any way to avoid direct usage of `.reasonCode` for something like this.

It _almost_ works in the JavaScript engine, but the cardinality issue is still a problem. The ELM `Property` expression that attempts to pull off the [qicore-notDoneValueSet extension](https://hl7.org/fhir/us/qicore/STU4.1.1/StructureDefinition-qicore-notDoneValueSet.html) from the `reasonCode` fails since the translator still thinks `reasonCode` is not a list.

To test this locally, we manually added a call to `First` around the access of `.reasonCode` in the ELM and were able to get execution to succeed. Is it reasonable to suggest adding a call to `First` around this access in the translator logic or directly in the `target` of the [relevant ModelInfo attribute](https://github.com/cqframework/clinical_quality_language/blob/bc9e36e9c15085d9d80884b84b7bc0a32c077d27/Src/java/quick/src/main/resources/org/hl7/fhir/qicore-modelinfo-4.1.1.xml#L875) if it supports that?

**Comment by brynrhodes** [comment]
Hi @mgramigna , I agree there's no way to do this without referencing the reasonCode element, but the point of the workaround is to just say that direct-reference code negation is not supported, rather than trying to work out the semantics of a direct-reference code negation against a multi-cardinality element.
