### ISSUE TITLE
Equal operator can't match FHIR.canonical + System.String even with FHIRHelpers

### ISSUE THREAD

**Issue by vadi2** [cqframework/clinical_quality_language#1169]
Recently ran into this even with FHIRHelpers included:

```
Could not resolve call to operator Equal with signature (FHIR.canonical,System.String).
```

CQL:

```
      [QuestionnaireResponse] QR
      where QR.questionnaire = 'http://example.com/fhir/Questionnaire/Diagnose'
      and QR.status = 'completed'
```

**Comment by ddieppois** [comment]
Hello @vadi2 !  I just tried this locally with the latest version of the translator and it went through successfully. I did not receive an error except for expecting warnings and I got my XML in the end.

Would you be able to retry this with the latest version of the translator and let me know if you're still facing the issue ?

Thanks,

David

**Comment by mdnazmulkarim** [comment]
We tested on master and it is now rendering the translatorVersion to Json and Xml. Thus it is closed now.
