### ISSUE TITLE
Compiler should emit warnings/errors if current settings do not support generic overloads

### ISSUE THREAD

**Issue by JPercival** [cqframework/clinical_quality_language#1193]
In ELM (roughly "CQL bytecode") type annotations are optional. This means that in certain cases function signatures that are distinguishable at compile time are not distinguishable at runtime. This is conceptually similar to the idea of "type erasure" in Java, where generic type overloads are not allowed.

The CQL compiler has flags that allow it to emit type information into ELM, specifically `EnableAnnotations` and `EnableResultTypes`. For CQL where function overload resolution would be ambiguous if type information is omitted and those flags are not enabled, the CQL compiler should warn that the resulting ELM will be ambiguous.

There are (disabled, commented-out) examples that can be used to test this behavior here:
https://github.com/cqframework/clinical_quality_language/blob/2d799aeae53d617eef41be3f45b6a74882b489ab/Src/java/engine/src/test/resources/org/opencds/cqf/cql/engine/execution/CqlTestSuite.cql#L4577-L4584

The code for function resolution is here:
https://github.com/cqframework/clinical_quality_language/blob/843f17f7679964fd7edb4e330745feca6eaa2e3c/Src/java/cql-to-elm/src/main/java/org/cqframework/cql/cql2elm/LibraryBuilder.java#L1126-L1175

**Comment by lukedegruchy** [comment]
According to @JPercival this is no longer issue as proven here:  https://github.com/cqframework/clinical_quality_language/compare/test-result-types?expand=1
