### ISSUE TITLE
Build :cql-to-elm:installDist not founded

### ISSUE THREAD

**Issue by tibraga** [cqframework/clinical_quality_language#1194]
Hi, i'm trying to execute the command bellow, but happens some error:

```
./gradlew :cql-to-elm:installDist

FAILURE: Build failed with an exception.

* What went wrong:
Cannot locate tasks that match ':cql-to-elm:installDist' as task 'installDist' not found in project ':cql-to-elm'.
```

Anyone know how to fix it?

**Comment by brynrhodes** [comment]
We recently switched from the gradle Distribution plugin to the Maven publishing plugin, so the commands there are different now. What are you trying to accomplish?

**Comment by brynrhodes** [comment]
Closing this issue as stale, feel free to reopen or submit a new issue if you are still having problems
