### ISSUE TITLE
USCore 3.1.1 - Patient.address.line

### ISSUE THREAD

**Issue by jbyrdevans** [cqframework/clinical_quality_language#1225]
Error `Could not resolve data provider for package 'java.util'` encountered for `Execute CQL` for USCore v3.1.1 Patient.address.line.

CQL:
``` 
library Repro version '0.1.0'

using USCore version '3.1.1'
//using FHIR version '4.0.1'

include FHIRHelpers version '4.0.1'

context Patient

define "Address":
  Patient.address.line

define "Address Line 1":
  Patient.address.line[0]
```

Patient:
```
{
  "resourceType": "Patient",
  "id": "USCorePatient-2",
  "meta": {
    "profile": [
      "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
    ]
  },
  "identifier": [
    {
      "use": "usual",
      "type": {
        "coding": [
          {
            "code": "MR",
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "display": "Medical Record Number"
          }
        ]
      },
      "system": "urn:oid:1.2.36.146.595.217.0.1",
      "value": "12345",
      "period": {
        "start": "2001-05-06"
      },
      "assigner": {
        "display": "Acme Healthcare"
      }
    }
  ],
  "active": true,
  "name": [
    {
      "use": "official",
      "family": "Chalmers",
      "given": [
        "James"
      ]
    }
  ],
  "gender": "male",
  "birthDate": "1974-12-25",
  "deceasedBoolean": false,
  "maritalStatus": {
    "coding": [
      {
        "code": "M",
        "system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus"
      }
    ]
  },
  "address": [
    {
      "use": "home",
      "type": "both",
      "text": "534 Erewhon St PeasantVille, Utah 84414",
      "line": [
        "534 Erewhon St"
      ],
      "city": "PleasantVille",
      "district": "Rainbow",
      "state": "UT",
      "postalCode": "84414",
      "period": {
        "start": "1974-12-25"
      }
    }
  ]
}
```

Result:
```
Evaluation logs:
16:08:15.253 [pool-2-thread-1] INFO  ca.uhn.fhir.context.FhirContext - Creating new FHIR context for FHIR version [R4]
Could not resolve data provider for package 'java.util'.
```

**Comment by JPercival** [comment]
Potential dup of https://github.com/cqframework/clinical_quality_language/issues/1231. Retest

**Comment by ddieppois** [comment]
So I've been able to translate this using CQL-to-elm-cli 

`================================================================================
TRANSLATE /Users/daviddieppois/Documents/git/clinical_quality_language/Examples/TestLibrary_1186.cql
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Translation completed successfully.
ELM output written to: /Users/daviddieppois/Documents/git/clinical_quality_language/Examples/TestLibrary_1186.xml
`

XML coming back is

`<?xml version="1.0" encoding="UTF-8"?>
<library xmlns="urn:hl7-org:elm:r1" xmlns:t="urn:hl7-org:elm-types:r1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fhir="http://hl7.org/fhir" xmlns:qdm43="urn:healthit-gov:qdm:v4_3" xmlns:qdm53="urn:healthit-gov:qdm:v5_3" xmlns:a="urn:hl7-org:cql-annotations:r1">
   <annotation translatorVersion="3.3.0-SNAPSHOT" translatorOptions="" signatureLevel="None" xsi:type="a:CqlToElmInfo"/>
   <identifier id="Repro" version="0.1.0"/>
   <schemaIdentifier id="urn:hl7-org:elm" version="r1"/>
   <usings>
      <def localIdentifier="System" uri="urn:hl7-org:elm-types:r1"/>
      <def localIdentifier="USCore" uri="http://hl7.org/fhir"/>
   </usings>
   <includes>
      <def localIdentifier="FHIRHelpers" path="FHIRHelpers" version="4.0.1"/>
   </includes>
   <contexts>
      <def name="Patient"/>
   </contexts>
   <statements>
      <def name="Patient" context="Patient">
         <expression xsi:type="SingletonFrom">
            <operand dataType="fhir:Patient" templateId="http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient" xsi:type="Retrieve"/>
         </expression>
      </def>
      <def name="Address" context="Patient" accessLevel="Public">
         <expression xsi:type="Flatten">
            <operand xsi:type="Query">
               <source alias="$this">
                  <expression path="address" xsi:type="Property">
                     <source name="Patient" xsi:type="ExpressionRef"/>
                  </expression>
               </source>
               <where xsi:type="Not">
                  <operand xsi:type="IsNull">
                     <operand path="value" xsi:type="Property">
                        <source path="line" xsi:type="Property">
                           <source name="$this" xsi:type="AliasRef"/>
                        </source>
                     </operand>
                  </operand>
               </where>
               <return distinct="false">
                  <expression path="value" xsi:type="Property">
                     <source path="line" xsi:type="Property">
                        <source name="$this" xsi:type="AliasRef"/>
                     </source>
                  </expression>
               </return>
            </operand>
         </expression>
      </def>
      <def name="Address Line 1" context="Patient" accessLevel="Public">
         <expression xsi:type="Indexer">
            <operand xsi:type="Flatten">
               <operand xsi:type="Query">
                  <source alias="$this">
                     <expression path="address" xsi:type="Property">
                        <source name="Patient" xsi:type="ExpressionRef"/>
                     </expression>
                  </source>
                  <where xsi:type="Not">
                     <operand xsi:type="IsNull">
                        <operand path="value" xsi:type="Property">
                           <source path="line" xsi:type="Property">
                              <source name="$this" xsi:type="AliasRef"/>
                           </source>
                        </operand>
                     </operand>
                  </where>
                  <return distinct="false">
                     <expression path="value" xsi:type="Property">
                        <source path="line" xsi:type="Property">
                           <source name="$this" xsi:type="AliasRef"/>
                        </source>
                     </expression>
                  </return>
               </operand>
            </operand>
            <operand valueType="t:Integer" value="0" xsi:type="Literal"/>
         </expression>
      </def>
   </statements>
</library>


`
@jbyrdevans what command did you use. ?
