### ISSUE TITLE
Incorrect dependency on Eclipse Moxy on cqf-fhir-npm

### ISSUE THREAD

**Issue by vitorpamplona** [cqframework/clinical_quality_language#1235]
I believe this can be turned into `runtimeOnly`

https://github.com/cqframework/clinical_quality_language/blob/f86ed16b1f0fcf4c8c4c7bae5287cd5ad28b3371/Src/java/cqf-fhir-npm/build.gradle#L10

Also double check the reason to use Gson in the [cqf-fhir-npm](https://github.com/cqframework/clinical_quality_language/tree/master/Src/java/cqf-fhir-npm) package while the rest uses Jackson. I am not sure Gson is actually being used. 

https://github.com/cqframework/clinical_quality_language/blob/f86ed16b1f0fcf4c8c4c7bae5287cd5ad28b3371/Src/java/cqf-fhir-npm/build.gradle#L8

**Comment by lukedegruchy** [comment]
GSON is being used in `org.cqframework.fhir.npm.LibraryLoader#LibraryLoader`, which indirectly calls `org.hl7.fhir.dstu2016may.formats.JsonParserBase` among other DSTU*/R* variants.

**Comment by JPercival** [comment]
That dependency should be pulled in transitively, right?

**Comment by JPercival** [comment]
Resolved y #1255
