### ISSUE TITLE
Assistance required with Error message in CQL Library Editor

### ISSUE THREAD

**Issue by Svellanky1** [cqframework/clinical_quality_language#1272]
We are receiving the following errors in CQL Library Editor after editing the value set name for one of the value sets used:
ERRORS:
********************************************************************************************************************
Line 160: Could not validate reference to expression Active Exclusion Diagnosis at Start of ED Encounter because its definition contains errors.
Line 184: Could not resolve identifier Pregnancy (ICD10CM and SNOMEDCT) in the current library.
*******************************************************************************************************************/

The relevant lines from the CQL code are below: 
156 
157 define "Denominator Exclusions":
158   "Allergy or Intolerance to Thrombolytic Medications Overlaps ED Encounter"
159     union "Adverse Effect to Thrombolytic Medications Before End of ED Encounter"
**160     union "Active Exclusion Diagnosis at Start of ED Encounter"**
161     union "Active Oral Anticoagulant Medication at the Start of ED Encounter"
162     union "Exclusion Diagnosis During ED Encounter or Within 24 Hours of ED Encounter Start"
163     union "Major Surgical Procedure 21 Days or Less Before Start of or Starts During ED Encounter"
164     union "Intubation or Mechanical Circulatory Assist Procedure During ED Encounter or Within 24 Hours of ED Encounter Start"
165     union "Active Exclusion Diagnosis Within 90 Days Before or At the Start of ED Encounter"
166     union "Intracranial or Intraspinal Procedure 90 Days or Less Before Start of ED Encounter"
167     union "ED Encounter with Discharge Disposition as Patient Expired"
168 
169 define "Active Oral Anticoagulant Medication at the Start of ED Encounter":
170   "ED Encounter with STEMI Diagnosis" EDwSTEMI
171     with ["Medication, Active": "Oral Anticoagulant Medications"] OralAnticoagulant
172       such that ( Global.HasStart ( OralAnticoagulant.relevantPeriod )
173           and OralAnticoagulant.relevantPeriod starts before or on start of EDwSTEMI.relevantPeriod
174           and OralAnticoagulant.relevantPeriod ends on or after start of EDwSTEMI.relevantPeriod
175       )
176         or ( OralAnticoagulant.relevantDatetime before or on EDwSTEMI.relevantPeriod )
177 
178 define "Active Exclusion Diagnosis at Start of ED Encounter":
179   "ED Encounter with STEMI Diagnosis" EDwSTEMI
180     with ( ["Diagnosis": "Active Bleeding Excluding Menses or Bleeding Diathesis"]
181       union ["Diagnosis": "Malignant Intracranial Neoplasm Group"]
182       union ["Diagnosis": "Cerebral Vascular Lesion"]
183       union ["Diagnosis": "Dementia and Related Intracranial Pathologies"]
**184       union ["Diagnosis": "Pregnancy (ICD10CM and SNOMEDCT)"]**
185       union ["Diagnosis": "Allergy to thrombolytics"] ) ActiveExclusionDx
186       such that ActiveExclusionDx.prevalencePeriod overlaps before EDwSTEMI.relevantPeriod

Would you please let us know how to resolve this error? The value set has been updated in the workspace. Is there another step we are missing?

**Comment by JPercival** [comment]
Hi @Svellanky1! Thanks for the report. What is the "CQL Library Editor" you are referring to? At first glance it looks like you're missing a Value Set definition. It will look something like the following, but replace the example URL below with the correct one for your scenario.

```
valueset "Pregnancy (ICD10CM and SNOMEDCT)" : 'example.com/valueset/123`
```

**Comment by Svellanky1** [comment]
Hi @JPercival, thank you for your response. Apologies for the confusion, we are trying to edit the specifications for our measure in the MAT in the CQL workspace. This is where the error is showing up. Does that help? 

In terms of the value set definition, we have that in the specifications already as: 
**valueset "Pregnancy (ICD10 and SNOMEDCT)": 'urn:oid:2.16.840.1.113883.3.3157.4055'**
All other value sets are similarly defined but if there is anything additional that we need to do please let us know. 

Thank you!

**Comment by JPercival** [comment]
Hmm... It's not obvious to me where the issue is given that you've already defined the valueset. The MAT tool is actually "downstream" from this project. The Github org for MAT is here:

https://github.com/MeasureAuthoringTool

You may have better luck diagnosing the issue there.

**Comment by Svellanky1** [comment]
Thank you for your assistance, @JPercival
