### ISSUE TITLE
Task :engine:compileTestJava FAILED

### ISSUE THREAD

**Issue by MatthewDynamic** [cqframework/clinical_quality_language#1317]
Performing 
`gradlew build `
as per
[https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/README.md](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/README.md)
produces

```
> Task :engine:compileTestJava
D:\Development\_CQF\clinical_quality_language\Src\java\engine\src\test\java\org\opencds\cqf\cql\engine\model\CachingModelResolverDecoratorTest.java:43: warning: [deprecation] getPackageName() in ModelResolver has been deprecated
        when(m.getPackageName()).thenReturn("test.package");
              ^
D:\Development\_CQF\clinical_quality_language\Src\java\engine\src\test\java\org\opencds\cqf\cql\engine\model\CachingModelResolverDecoratorTest.java:58: warning: [deprecation] getPackageName() in ModelResolver has been deprecated
        when(m.getPackageName()).thenReturn("test.package");
              ^
D:\Development\_CQF\clinical_quality_language\Src\java\engine\src\test\java\org\opencds\cqf\cql\engine\runtime\DateTimeTest.java:356: error: cannot find symbol
        dateTime2 = new DateTime(BigDecimal.TWO, 2020);
                                           ^
  symbol:   variable TWO
  location: class BigDecimal
1 error
2 warnings

> Task :engine:compileTestJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':engine:compileTestJava'.
```

Hi. It's been a few weeks and I am still unable to compile this project. 

Since I have been struggling to compile this code for multiple weeks now, is my approach incorrect? I am trying to follow the instructions at Src/java/README.md. Am I following the wrong path? Are there different resources I can use to get this stuff running?

Thank you,
Matthew Dugal

**Comment by JPercival** [comment]
Looks like a Java 19 API snuck into the test code. Reverted to target 11. Changes are merged to `master`, give it go! :)

**Comment by JPercival** [comment]
The build on the `master` branch is currently passing in CI:
https://github.com/cqframework/clinical_quality_language/actions/runs/7565120881/job/20600348682

Could you try a clean checkout?

**Comment by JPercival** [comment]
Any updates here @MatthewDynamic ?

**Comment by JPercival** [comment]
@MatthewDynamic - Do you happen to be on windows? We found a couple platform-specific issues with the tests that have been fixed.
