### ISSUE TITLE
Unexpected union results

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/clinical_quality_language#1348]
The following union works as expected:

```cql
define Foo3: { 1 } union { 1.0 }
```
returning `{ 1, 1.0 }`

However, this oddly results in a null?

```
define Foo2: { 1, 'hi', true } union { 1.0, true }
```
I expected `{ 1, 'hi', true, 1.0 }` but I get `{ 1, 'hi', true, null }`?

**Comment by JPercival** [comment]
Appears that this may be a bug in the CQL Language Server rather than the CQL Runtime. IOW, they underlying value appears to be correctly computed, but it's serialized incorrectly.
