### ISSUE TITLE
Duplicate Type attribute when using ElmLibraryWriter to generate JSON from Library

### ISSUE THREAD

**Issue by gregory-akins** [cqframework/clinical_quality_language#1380]
When using clinical_quality_language ElmLibraryWriter.java ( ./Src/java/elm/src/main/java/org/cqframework/cql/elm/serializing/ElmLibraryWriter.java ) to generate JSON from a Library that was created with org.cqframework.cql.cql2elm.CqlTranslator

In version 3.3.2, the resulting JSON was correct (ie., could be parsed by org.json.JSONObject). When using version 3.11.0, the resulting JSON is incorrect and yields the message  "Duplicate key 'type' encountered at line 308 column 20" ( Below, you can see the two "type" definitions under localId 263

```
"resultTypeSpecifier" : {
               "localId" : "262",
               "type" : "ListTypeSpecifier",
               "elementType" : {
                  "localId" : "263",
                  "type" : "ChoiceTypeSpecifier",
                  "type" : [ ],
                  "choice" : [ {
                     "localId" : "264",
                     "name" : "{urn:healthit-gov:qdm:v5_6}PositiveEncounterPerformed",
                     "type" : "NamedTypeSpecifier"
                  }, {
                     "localId" : "265",
                     "name" : "{urn:healthit-gov:qdm:v5_6}PositiveInterventionPerformed
[3.3.2-LibraryJson.json](https://github.com/user-attachments/files/16144388/3.3.2-LibraryJson.json)
[3.11.0-LibraryJson.json](https://github.com/user-attachments/files/16144389/3.11.0-LibraryJson.json)
[3.3.2-LibraryJson.json](https://github.com/user-attachments/files/16144406/3.3.2-LibraryJson.json)
[3.11.0-LibraryJson.json](https://github.com/user-attachments/files/16144407/3.11.0-LibraryJson.json)
",
                     "type" : "NamedTypeSpecifier"
                  } ]
               }
            },
```

I haven't determined whether the problem is with the translator, or the Writer.

The error seems to occur when CQL contains UNION

```
library MAT6463GenerateElmJSON version '2.0.000'

using QDM version '5.6'


parameter "Measurement Period" Interval<DateTime>

context Patient

define "IPP":
  true
define "Undefined Encounter":
 ["Encounter, Performed"]
define "Undefined Intervention":
 ["Intervention, Performed"]
 define "Union of UnDefined":
 ("Undefined Encounter" union "Undefined Intervention")



```

[3.3.2-LibraryJson.json](https://github.com/user-attachments/files/16144439/3.3.2-LibraryJson.json)
[3.11.0-LibraryJson.json](https://github.com/user-attachments/files/16144440/3.11.0-LibraryJson.json)

**Comment by gregory-akins** [comment]
@hossenlopp I'm not seeing where this was mentioned in https://github.com/cqframework/cql-execution/pull/320

But it's impacting our ability to incorporate anything from cqframework 3.6.0 or greater into MADiE. Can I provide any additional information, or do any additional research to help debug this issue?

**Comment by hossenlopp** [comment]
I mentioned this issue in https://github.com/cqframework/cql-execution/pull/320 since that PR updated our testing deck to be translated with cql-to-elm 3.12.0 this issue broke a handful of tests. I had to manually remove the duplicate `type` attributes, specifically around ChoiceTypes, in the translated ELM to get the tests to have valid data for input.

There is no way for us to create a workaround in `cql-execution` as it would require replacing the built in `JSON.parse()` function which would be an unreasonable amount of work. This fix needs to be made in the translator.

**Comment by JSRankins** [comment]
@hossenlopp Do you know if this has been submitted as a ticket to https://github.com/cqframework/clinical_quality_language? cc @brynrhodes
