### ISSUE TITLE
Issue with Take/Skip operator.

### ISSUE THREAD

**Issue by c-schuler** [cqframework/clinical_quality_language#140]
I am having an issue with the Take and/or Skip operators. The problem is that they can produce the same Slice sig, but very different results are expected. 

For example:
If I call Take(List<T>, null), I get Slice(List<T>, 0, null) -> should return empty list
If I call Skip(List<T>, 0), I also get Slice(List<T>, 0, null) -> should return source list

This seems to be an issue with the mapping from Take to Slice...

**Comment by brynrhodes** [comment]
Submitted comment [1438](http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=1438)
