### ISSUE TITLE
Case sensitivity and UCUM units

### ISSUE THREAD

**Issue by mulcahyk** [cqframework/clinical_quality_language#144]
In section 2.5.4.1 of the R1.2 spec it says 

> Note also that the UCUM time-period units can be used when expressing duration quantities.

section 2.4.2.1 it says 

> In addition, CQL supports any valid Unified Code for Units of Measure (UCUM) unit code using
> the string representation of the UCUM code immediately following the numeric value, as shown
> in the first example in this section. UCUM codes can be specified in the case-sensitive (c/s) or
> case-insenstive form (c/i).

According to this site: http://download.hl7.de/documents/ucum/ucumdata.html there is something called a MegaSecond whose unit is `Ms`. There is also the MilliSecond with a unit of `ms`.  If you go with case insensitive units you could end up mixing these two units.

**Comment by brynrhodes** [comment]
This should be submitted as an issue against the CQL specification so we can determine a general resolution in the specification. If that resolution does not address the ambiguity, then the issue will need to be considered as part of an implementation guide or potentially program-specific guidance for artifacts.

**Comment by brynrhodes** [comment]
Submitted comment [1440](http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=1440)
