### ISSUE TITLE
Unexpected behavior with exists when list promotion is enabled

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#145]
@brynrhodes: 
With list promotion turned on, a boolean that is fed into the exists operator is turned into a list. Doing this will always cause the exists operator to return 'true'. As a result, something like the following will always true:

`exists(exists(null))`

or

`exists(false)`

Hopefully an author would never do this, but if an author did, it would have unintended consequences.  Earlier versions of CQL-to-ELM prevented the above scenario from happening. 
Is list promotion working as intended?

**Comment by brynrhodes** [comment]
List promotion is implemented with a ToList() operator, which is explicitly handling the `null` case to return an empty list, so `exists(null)` would return false. I agree thought that `exists(false)` would return true, which may be a surprising result. Can you give some examples of where you were thinking it would have unintended consequences though?

**Comment by JSRankins** [comment]
During testing, one of our QA people created a child library that did something like the following:

```
library child version '1.0.000'

using QDM version '5.0.2'

context Patient

define "hasEncounter":
    exists(["Encounter, Performed"])
```

They then used the child library in a parent library:

```
library parent version '1.0.000'

include child version '1.0.000' called ChildAlias

context Patient

using QDM version '5.0.2'

define "Initial Population":
    exists(ChildAlias.hasEncounter)
```

We expected this would return an error, but it did not. In this particular case, the author might think that this would only return true if the patient had an Encounter, but it would always return true and the patient would be included in the population even though the patient did not have an Encounter. If we allow this through list promotion, then we will have to be extra specially careful that we catch something like this during a review process.

**Comment by brynrhodes** [comment]
I agree that's a potential issue. Strictly speaking, it is correct though. Is this a good case for a warning? It would be easy to add a warning when a Boolean-valued expression is promoted to a list.

**Comment by JSRankins** [comment]
I think it would be a good use case for a warning message.
