### ISSUE TITLE
BaseTypeFhirConverter Does Not Support Long Cql Types

### ISSUE THREAD

**Issue by jreyno77** [cqframework/clinical_quality_language#1453]
isCqlType in BaseTypeFhirConverter does not check for Long:

`if (value instanceof BigDecimal
                || value instanceof String
                || value instanceof Integer
                || value instanceof Boolean) {
            return true;
        }`

**Comment by JPercival** [comment]
Integer64 is only defined in FHIR >=R4B. We don't support R4B, but I'll fix it for the R5 converter.
