### ISSUE TITLE
QI-Core STU 6 Model Info SimpleObservation.value

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#1461]
Good morning. Working through some QI-Core STU 6 logic updates, and an issue was encountered with SimpleObservation.value. In the model info, value seems to be specifically tied to [System.Concept](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/quick/src/main/resources/org/hl7/fhir/qicore-modelinfo-6.0.0.xml#L5412). However, the [QI-Core STU 6 Simple Observation](https://hl7.org/fhir/us/qicore/STU6/StructureDefinition-qicore-simple-observation.html) seems to support more than this type. Thoughts?

**Comment by JPercival** [comment]
Resolved by #1477
