### ISSUE TITLE
InValueSetEvaluator and AnyInValueset return null when a passed in code is null, contrary to the current cql spec

### ISSUE THREAD

**Issue by Zylox** [cqframework/clinical_quality_language#1469]
Looking through the version history, returning null in this case was the spec at one point. The last reference i could find to that was in STU2: https://cql.hl7.org/STU2/09-b-cqlreference.html#in-valueset

Since the version below however, the spec says it should return false in the situation where the code is null: https://cql.hl7.org/2018May/09-b-cqlreference.html#in-valueset

The effected areas, to the best of my knowledge, would be here: https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/engine/src/main/java/org/opencds/cqf/cql/engine/elm/executing/InValueSetEvaluator.java#L26-L28

and here: https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/engine/src/main/java/org/opencds/cqf/cql/engine/elm/executing/AnyInValueSetEvaluator.java#L16

The change itself would be minor, but the effect could be larger. Though it would seemingly be more in line with the cql spec.

**Comment by JPercival** [comment]
Thanks for the report! Related to #1048

**Comment by JPercival** [comment]
Most recent published spec: https://cql.hl7.org/09-b-cqlreference.html#in-valueset
