### ISSUE TITLE
Scoping Issue in CoffeeScript CQL Execution

### ISSUE THREAD

**Issue by cmoesel** [cqframework/clinical_quality_language#162]
In some cases, it appears there is a scoping issue in CQL execution -- specifically around aliases.  For example, if an expression uses an alias `C` in a query, and that query invokes a function that also uses an alias `C` for something different, one will overwrite the other.

I don't have a specific test case on hand at the moment, but did run into this on some internal CQL-related work.  Will try to create a test case (and maybe even a fix) when I have a moment.

**Comment by brynrhodes** [comment]
There was a translator issue with this that was recently resolved, #126. There is a unit test that verifies it [here](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/cql-to-elm/src/test/resources/org/cqframework/cql/cql2elm/OperatorTests/NameHiding.cql)

**Comment by cmoesel** [comment]
Ah, I remember that.  I'm not positive it's the same issue (there may really be a bug in CQL exec), but I'll try compiling w/ the new translator first to be sure.

**Comment by brynrhodes** [comment]
This issue was moved to cqframework/cql-execution#46
