### ISSUE TITLE
Cql Formatter recommendations

### ISSUE THREAD

**Issue by c-schuler** [cqframework/clinical_quality_language#163]
There are a few changes to the formatter that I would recommend:
I noticed that spaces after brackets are sometimes removed, which hinders readability, but not functionality. For example:
`AgeInYearsAt(start of MeasurementPeriod) < 64` -> `AgeInYearsAt(start of MeasurementPeriod)< 64`
Another example:
`Interval[A."start datetime", A."stop datetime"] overlaps MeasurementPeriod` -> `Interval[A."start datetime", A."stop datetime"]overlaps MeasurementPeriod`

I would also suggest formatting structured values differently. 
Here is example of how they are formatted:
`Tuple { firstEl: Numerator, secondEl: 88+96*89-9.0 / 2, thirdEl: {1,2, 3} union {8,0, 9, 10} }` ->
```
Tuple { firstEl: Numerator, secondEl: 88 + 96 * 89 - 9.0 / 2, thirdEl: { 1, 2, 3 }
		union { 8, 0, 9, 10 } }
```
I would suggest putting each element on a new line:
```
Tuple { 
    firstEl: Numerator, 
    secondEl: 88 + 96 * 89 - 9.0 / 2, 
    thirdEl: { 1, 2, 3 } union { 8, 0, 9, 10 } 
}
```
I think that is cleaner.

**Comment by brynrhodes** [comment]
This feature is included in the 1.2.11-SNAPSHOT release.
