### ISSUE TITLE
Considering Timezones in Difference Calculations

### ISSUE THREAD

**Issue by cmoesel** [cqframework/clinical_quality_language#184]
Given two dates in _different_ timezones:
* `define A: 2017-12-31@18:00:00.0-05:00`
* `define B: 2018-01-01@00:00:00.0+00:00`

What is the expected result of `difference in years between A and B`?

If we _don't_ consider timezones, then the result is `1`, since `A` is in `2017` and `B` is in `2018`.

If we _do_ consider timezones, then we must normalize to a common timezone in order to count boundaries.

If we normalize both to the _first_ timezone (EST), then `B` becomes `2017-12-31@19:00:00.0+00:00` -- and the result is `0` (both `A` and `B` are  in `2017`).

If we normalize both to the _second_ timezone (GMT), then `A` becomes `2017-12-31@11:00:00.0+00:00` -- and the result is `1` (since `A` is in `2017` and `B` is in `2018`).

If we normalize to the timezone of the request stamp, which might be neither EST nor GMT, then... who knows?

**Comment by brynrhodes** [comment]
It seems to me there are only two options for ensuring consistent behavior. 1) Normalize to UTC or 2) Normalize to the timezone of the request.

Given that the default timezone (i.e. the timezone used to construct date/time values if no timezone is specified in the selector) is the timezone of the request, I tend to lean towards option 2.

**Comment by cmoesel** [comment]
I think that normalizing to UTC or any other timezone not related to the data itself might get weird.

Normalizing time zones changes where all of the boundaries are.  If we do that whenever date 1 and date 2 have different offsets, then it will happen a _lot_ for areas that observe daylight savings, since there will so often be comparisons between dates in different offsets.  That's my main concern...

**Comment by brynrhodes** [comment]
But there's no basis for normalizing to one or the other operand of a binary expression, especially one that is supposed to be commutative. Identifying one operand as being given special consideration would break that property, tying the translators hands for optimization as well as translation to other systems. Seems like the worst option to me. So I still think that consistent with the Now() and Today() operators, we should normalize to the timezone of the request.

**Comment by cmoesel** [comment]
OK -- I agree that this would break commutativity.  I hadn't thought of that.

That said, if we normalize to the timezone of the request, then we're in a situation where calculations will be different depending on the location.  For example, running Bonnie tests in San Fransisco might yield different results than running them in Boston.

Or worst, the results might be different depending on whether or not you are currently observing daylight savings time.  For example, running them in Boston on March 1 might yield different results than running them in Boston on Apr 1.

I guess it is a bit of a no-win situation either way.

Would you propose that the dates only be normalized when the timezones differ?  Or would we always normalize them?  I know this is a bit of an edge case, but if we only normalize when they differ, then we have an opportunity for this situation:
```
// request timestamp in GMT
define A: 2012-06-15T23:30:00.0-04:00
define B: 2012-06-16T00:30:00.0-04:00
define C: 2012-06-16T01:00:00.0-00:00
define AsameDayAsC: A same day as C // true
define BsameDayAsC: B same day as C // true
define AsameDayAsB: A same day as B // false
```
(BTW -- this seeming inconsistency would occur if we normalized to the first timezone as well, so it's relevant to either case if we only normalize when timezones differ).

**Comment by brynrhodes** [comment]
I think given that there is no "right" answer, I'm hesitant to actually put anything prescriptive in the spec. I'd be comfortable suggesting an approach that always normalizes to the timezone of the request, and further suggesting that systems should record dates in UTC to begin with, but in the absence of that ideal, some flexibility in implementation is desirable to allow environments to select the most appropriate implementation strategy.

**Comment by cmoesel** [comment]
OK -- so that would be more like "implementation guidance" than a normative requirement of the spec?  I think that probably makes the most sense.  Over here, we're all hoping that some day the world will go to a single unified time.  That would make things a lot easier!

**Comment by brynrhodes** [comment]
Right, I'll take the action to log an STU comment on this.

**Comment by cmoesel** [comment]
An STU comment to get the world to move to a unified time?  Excellent!  If HL7 can pull that off, I'll pay double-dues for the rest of my life!

But seriously... thanks.

**Comment by brynrhodes** [comment]
Submitted comment [1441](http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=1441)
