### ISSUE TITLE
Validation of UCUM units

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#195]
The CQL Release 1.2 standard allows for the use of UCUM units when they are need for specifying certain criteria:

```
In addition, CQL supports any valid Unified Code for Units of Measure (UCUM) unit code using the string representation of the UCUM code immediately following the numeric value, as shown in the first example in this section. UCUM codes can be specified in the case-sensitive (c/s) or case-insenstive form (c/i).
```

These units are not currently validated within the CQL-to-ELM translator. The inaccurate spelling of a UCUM code can cause issues within an execution environment. Based on conversations with @brynrhodes, we are creating a ticket to get this validation added for authoring purposes, so users of the MAT or other authoring environments that use CQL-to-ELM translator can know when the provide incorrectly spelled codes.

**Comment by brynrhodes** [comment]
This feature is included in release [1.2.19](https://github.com/cqframework/clinical_quality_language/releases/tag/v1.2.19).
