### ISSUE TITLE
Not able to imports jars via maven. It looks like the jar does not have proper version.

### ISSUE THREAD

**Issue by heravelli** [cqframework/clinical_quality_language#208]
Example:
<groupId>info.cqframework</groupId>
<artifactId>cql-to-elm</artifactId>
<version>1.2.11-SNAPSHOT</version>

But, I do not see any jar with the name cql-to-elm-1.2.11-SNAPSHOT.

Maven is complaining about failing to read artifact descriptor

**Comment by c-schuler** [comment]
Do you have the following in your pom file?
```
<repositories>
        <repository>
            <id>oss-sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>oss-sonatype-public</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
</repositories>
```

**Comment by heravelli** [comment]
I had only  <repository>
            <id>oss-sonatype-public</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository> before.

I added snapshots url and tried it same results. Not able to read artifact descriptor.

**Comment by c-schuler** [comment]
Please share your pom file.

**Comment by heravelli** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.tsi</groupId>
    <name>Spinnaker CQL to ELM</name>
    <artifactId>spinnaker-cql-elm</artifactId>
    <version>0-SNAPSHOT</version>

    <properties>
	   <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <jdk.version>1.8</jdk.version>
        <mvn.compiler.version>2.3.2</mvn.compiler.version>
        <mvn.shade.version>2.4.3</mvn.shade.version>
        <mvn.resource.version>3.0.1</mvn.resource.version>
        <commonscodec.version>1.10</commonscodec.version>
        <commonslang.version>3.1</commonslang.version>
        <log4j.version>1.2.17</log4j.version>
        <slf4j.version>1.7.5</slf4j.version>
        <groovy.version>2.4.3</groovy.version>
        <commonsio.version>2.5</commonsio.version>
        <junit.sversion>4.12</junit.sversion>
        <commonsconfig.version>1.6</commonsconfig.version>
        <google.guava.version>19.0</google.guava.version>
        <cql.version>1.2.11</cql.version>

    </properties>

    <repositories>
        <repository>
            <id>oss-sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>oss-sonatype-public</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
    </repositories>
 <dependencies>
 <dependency>
            <groupId>info.cqframework</groupId>
            <artifactId>cql</artifactId>
            <version>${cql.version}</version>
        </dependency>
        <dependency>
            <groupId>info.cqframework</groupId>
            <artifactId>model</artifactId>
            <version>${cql.version}</version>
        </dependency>
        <dependency>
            <groupId>info.cqframework</groupId>
            <artifactId>elm</artifactId>
            <version>${cql.version}</version>
        </dependency>
        <dependency>
            <groupId>info.cqframework</groupId>
            <artifactId>cql-to-elm</artifactId>
            <version>${cql.version}</version>
        </dependency>
        <dependency>
            <groupId>info.cqframework</groupId>
            <artifactId>quick</artifactId>
            <version>${cql.version}</version>
        </dependency>
        <dependency>
            <groupId>info.cqframework</groupId>
            <artifactId>qdm</artifactId>
            <version>${cql.version}</version>
        </dependency>
</dependencies>
</project>

**Comment by heravelli** [comment]
I manually downloaded the jar and installed into maven locally. I noticed that the jars are not fat/uber jars. I created a unit test and when I tried to run it, I got several runtime errrors-- java.lang.NoClassDefFoundError: org/jvnet/jaxb2_commons/lang/Equals

I am adding those to my classpath to resolve it. 

So, my questions, are these jars meant to be used as an API by others. I am trying to wrap these in our project with our business logic. Please confirm if that is the case.

**Comment by c-schuler** [comment]
Change this:
`<commonslang.version>3.5</commonslang.version>`

Add this:
```
<dependency>
    <groupId>org.jvnet.jaxb2_commons</groupId>
    <artifactId>jaxb2-basics</artifactId>
    <version>0.9.4</version>
</dependency>
```
If that still doesn't work see if you can build this project:
https://github.com/DBCG/cql_execution_service

**Comment by heravelli** [comment]
Never mind, I had java certs issues. Installed the certs and was able to import it.

I did get class not found for JavaUnicodeEscaper. I added the dependency in my pom.
