### ISSUE TITLE
Participation ns:typeInfo

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#218]
The new Participation ns:typeInfo node is missing the label in the 5.3 QDM Model Info file:

https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/qdm/src/main/resources/gov/healthit/qdm/qdm-modelinfo-5.3.xml

```
    <ns4:typeInfo xsi:type="ns4:ClassInfo" name="QDM.Participation" retrievable="true" baseType="QDM.QDMBaseType" primaryCodePath="code">
        <ns4:element name="participationPeriod" type="interval&lt;System.DateTime&gt;"/>
</ns4:typeInfo>
```

This label exists for all the other ns4:typeInfo nodes when the retrievable attribute is set to true. Please add the label. Thanks.

**Comment by brynrhodes** [comment]
Yep, missed that. Unless anyone objects, I'm going to treat this as a typo and commit the fix directly to master.

**Comment by brynrhodes** [comment]
Fixed as a typo in master.

**Comment by brynrhodes** [comment]
Addressed in v.1.2.13-SNAPSHOT
