### ISSUE TITLE
Use of Ratio is Requiring a Unit

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#227]
This CQL expression

```
	["Laboratory Test, Performed"] L
		where L.result.numerator > 5
```

results in the following error being provided by CQL-to-ELM:

```
[org.cqframework.cql.cql2elm.CqlSemanticException: Could not resolve call to operator Greater with signature (System.Quantity,System.Integer).]
```

Adding a unit, as in 

```
	["Laboratory Test, Performed"] L
		where L.result.numerator > 5 'mg'
```

passes validation.

Per the annotated QDM 5.3, unit is optional. Thoughts?

**Comment by brynrhodes** [comment]
Discussions on this have resulted in a decision to wait for CQL to support a first-class Ratio type, and in the mean time, to provide guidance for specific use cases involving ratios as they are encountered in measure development.

**Comment by brynrhodes** [comment]
Submitted comment [1437](http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=1437) to add a Ratio type to CQL.
