### ISSUE TITLE
Commented-out demographics function in CBP example

### ISSUE THREAD

**Issue by WilliamParker** [cqframework/clinical_quality_language#229]
In the [CBP example](https://github.com/cqframework/clinical_quality_language/blob/master/Examples/library-cbp.cql) I see the following is commented out:

````
// TODO: Need to verify the demographic here
define "In Demographic":
    true
    //AgeInYearsAt(start of MeasurementPeriod) >= 40
````
This example seems to be distinct from the others in that it is using FHIR models.  Are there any known issues with age calculations on FHIR patient models that caused this to be commented out?  The following works for me when using QUICK but fails with an inability to find the FHIRHelpers library when using FHIR.  After some preliminary investigation I haven't found anything trying to load up the FHIRHelpers library based on debug statements around [addInclude](https://github.com/cqframework/clinical_quality_language/blob/v1.2.9-SNAPSHOT/Src/java/cql-to-elm/src/main/java/org/cqframework/cql/cql2elm/LibraryBuilder.java#L430) and, while I could easily be missing something as I haven't dug into the project too deeply yet, the commented-out example makes we wonder if I've stumbled onto an unsupported use-case.

````
define "InDemographic":
	AgeInYears() >= 16 and AgeInYears() < 24 and "Patient"."gender" = 'female'
````

**Comment by WilliamParker** [comment]
Looking into this more, it seems that the CQL to ELM translation succeeds when I explicitly bring in FHIRHelpers like this:
````
include FHIRHelpers called FHIRHelpers
```` 

but not when I bring them in like this:

````
include FHIRHelpers
````

Right now it looks like my immediate issue has been resolved, but there may be relevant documentation and or error-handling work so I'll leave the issue open for now pending a decision by the maintainers of what to do with it.

**Comment by brynrhodes** [comment]
Yeah, this example needs to be updated to the latest FHIR version, we're working on that on another repository and plan on updating this example once that's complete. The fact that it works when you include the "called" clause but not without it is surprising though, I'll take a look at that.

**Comment by WilliamParker** [comment]
I revisited this today and I found I was able to get my query to compile regardless of whether I added a "called" clause.  I'm not sure what I had going on before - I suppose it is possible that there is some kind of nondeterminism at play, but it was more likely some kind of user error on my part.  I'll let you know if I'm able to reproduce the issue in the future.

**Comment by brynrhodes** [comment]
Glad it's working, I'll close this issue then.
