### ISSUE TITLE
Issue with *Week* Functions

### ISSUE THREAD

**Issue by jackcmeyer** [cqframework/clinical_quality_language#231]
The AgeInWeeksAt(), AgeInWeeks(), CalculateAgeInWeeksAt(), and CalculateAgeInWeeks() appear to be missing from the cql-to-elm translator. These functions are listed in Appendix B in the CQL standard, but the translator reports an issue when using these functions.

**Comment by brynrhodes** [comment]
Yes, the Weeks overloads are not present in the translator, I'll get them added.

**Comment by brynrhodes** [comment]
Only measures that use weeks calculations would be impacted, and the workaround is to perform the calculation in days. Discussion on the CQL-Based HQMF WG call indicates it is preferable to bundle this fix into the next release, not necessary to get it in a hotfix.

**Comment by brynrhodes** [comment]
Included in the 1.2.15 release
