### ISSUE TITLE
Issue with comparing Quantities 

### ISSUE THREAD

**Issue by rdingwell** [cqframework/clinical_quality_language#234]
The following statement is taken from a measure that is currently being developed and highlights what I believe is an issue with the way the CQL spec currently handles comparisons of Quantities with incompatible units.   
````
define "Pap Test with Results":
    ["Laboratory Test, Performed": "Pap Test"] LabTest
         where ( LabTest.result as Code in "Positive Result" )
	 or ( ( LabTest.result as Quantity ) < 100 '%' )
	 or ( ( LabTest.result as Quantity ) > 45 'mmol/L' )
	 or ( LabTest.result >= 30 )
````
According to the spec in a number of locations. 

> For comparisons involving quantities, the dimensions of each quantity must be the same, but not necessarily the unit. For example, units of 'cm' and 'm' are comparable, but units of 'cm2' and 'cm' are not. Attempting to operate on quantities with invalid units will result in a run-time error.

In the case above the LabTest result can be coded either as a percentage or as millimoles per liter.  This presents a problem, if the result is a Quantity coded as mmol/L the initial comparison to a Quantity as a percentage is expected to throw a runtime error.   

For instances where an expected Quantity can be coded in multiple, incompatible units there  does not appear to be a way to handle the situation without throwing a runtime error at some point.  I can see throwing exceptions for arithmetic operations on Quantities that are incompatible but think that something else needs to be considered for comparison operations.   Perhaps this could be handled by some sort of Uncertainty or possibly a qualifier of some sort that would allow for the comparison to be performed only if the units where compatible with each other.

**Comment by cmoesel** [comment]
Another approach might be to leverage the three-valued logic that CQL supports and return `null` when comparisons are made using incompatible units.  Since `null` is basically equivalent to _maybe_ or _I don't know_, then this approach would essentially say _"Is 50 'mmol/L' < 100 '%'?  I don't know!"_

**Comment by brynrhodes** [comment]
I agree that an error isn't the most friendly. I'm a little hesitant to return null, although I think it's probably the best answer. It's worth a comment to the STU, so I'll submit one related to this issue.

As a potential workaround though, you could test the unit:

    define "Pap Test with Results 2":
      ["Laboratory Test, Performed": "Pap Test"] LabTest
        where
          case
            when LabTest.result as Code in "Positive Result" then true
            when LabTest.result.unit = '%' then LabTest.result < 100 '%'
            when LabTest.result.unit = 'mmol/L' then LabTest.result > 45 'mmol/L'
            else LabTest.result >= 30
          end

**Comment by rdingwell** [comment]
I thought about testing the units, and yes it would alleviate the issue with throwing an error but it comes with it's own problem.  Testing the units first requires them to be not just compatible but exactly the same so any units compatible with mmol/L, such as mmol/ml, will not be tested.   

I agree with Chris that returning null seems to be the most appropriate thing to do.  I think that is what would happen if the result in the example was a Code that was not in the valueset specified in the first test anyway.  That would result in comparing a Code to Quantities and an Integer in subsequent tests.  If you say CQL can't tell whether a Code is greater than a Quantity or an Integer so return null then it seems the logical conclusion would be if units are incompatible return null.

**Comment by brynrhodes** [comment]
Submitted as comment [1434](http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=1434)
