### ISSUE TITLE
Release (non-snapshot) artifacts on Maven Central

### ISSUE THREAD

**Issue by rbrush** [cqframework/clinical_quality_language#239]
We'd like to request a non-snapshot release of the latest version of the project (1.2.14 at the time of this request). 

Making a non-snapshot build available on Maven Central (or another publicly visible Maven repository) would make it usable in build environments that require released versions of dependencies rather than snapshots.

We'd be happy to assist in any way that would be helpful on this.

**Comment by brynrhodes** [comment]
The 1.2.15 release has been uploaded to the Sonatype repositories and is currently being sync'ed to Maven Central.

**Comment by rbrush** [comment]
We grabbed it from Maven Central and everything is working well. Thanks!
