### ISSUE TITLE
installApp not working

### ISSUE THREAD

**Issue by doitviolet** [cqframework/clinical_quality_language#247]
Current build throws an exception when using the the installApp option:

$ ./gradlew installApp

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installApp' not found in root project 'cql-all'. Some candidates are: 'install'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by cmoesel** [comment]
In the most recent versions of gradle, `installApp` was deprecated.  Please use `installDist` instead:
```
$ ./gradlew installDist
```

I apologize for the confusion.  We'll update the README to reflect this.
