### ISSUE TITLE
offsetPolarity in visitTimeLiteral causing negative timezone offsets to always result in 0.0

### ISSUE THREAD

**Issue by c-schuler** [cqframework/clinical_quality_language#256]
I believe this [line](https://github.com/cqframework/clinical_quality_language/blob/0237ba278ec40d69f04aeda4e2c7a45012da9558/Src/java/cql-to-elm/src/main/java/org/cqframework/cql/cql2elm/Cql2ElmVisitor.java#L905):

`int offsetPolarity = matcher.group(12).equals("+") ? 1 : 0;`

 should be 

`int offsetPolarity = matcher.group(12).equals("+") ? 1 : -1;`

When the offsetPolarity is zero, then the hour part of the timezone offset will always result in 0.0 because of the following [line](https://github.com/cqframework/clinical_quality_language/blob/0237ba278ec40d69f04aeda4e2c7a45012da9558/Src/java/cql-to-elm/src/main/java/org/cqframework/cql/cql2elm/Cql2ElmVisitor.java#L925):

`result.setTimezoneOffset(libraryBuilder.createLiteral((double)(hourOffset * offsetPolarity)));`

**Comment by brynrhodes** [comment]
Included in release 1.2.18
