### ISSUE TITLE
Could not resolve call to operator And with signature (System.Boolean,list&lt;FHIR.MedicationRequest>).

### ISSUE THREAD

**Issue by msainv** [cqframework/clinical_quality_language#257]
Hello,
I am using the CQL online editor tool. I received the message below after doing the following scenario:

Define".....":
expression 1 and expression 2
Both expressions are already defined in the library without any errors.  However, when I try to combine them I get this error in the ELM translator:
"Could not resolve call to operator And with signature (System.Boolean,list&lt;FHIR.MedicationRequest>)."

PS: I am using FHIR '1.8' 
Expression 2 is referencing the FHIR MedicationRequest resource.

Thanks,
M.Sainv

**Comment by c-schuler** [comment]
What's the issue? The error message explains what is going wrong. Are you arguing that you should be able to AND a Boolean and a list of MedicationRequests? 

Please clarify what you are trying to do and why you believe the error is invalid. It would also be helpful if you provide the CQL code that is resulting in the issue.

**Comment by cmoesel** [comment]
Marc, if you are using the new alpha CDS Connect CDS Authoring Tool, you've stumbled upon one of the "rough edges" in the alpha.  Although AND statements require boolean expressions, the CDS Authoring Tool doesn't yet force all expressions in Inclusions/Exclusions to be boolean.  In the expression builder, it always shows the result type of the expression (e.g., List of Medications).  Usually to get a List to a Boolean, you would use the "Exists" operator.  In the CDS Authoring Tool, you do this by clicking "Add Expression" and then choosing "Exists".

All that said, the CDS Authoring Tool uses FHIR 1.0.2 (not 1.8), so perhaps you are writing it by hand.  If so, you'd do it like this `exists (myMedList)`.

**Comment by msainv** [comment]
@c-schuler This has been resolved. Thanks a lot!

**Comment by msainv** [comment]
@cmoesel Hi Chris, I was using the CQL online tool. I got no error message now, all I did was putting parentheses. Thanks a lot!

**Comment by c-schuler** [comment]
That's great that it is working for you now. Personally, I would like to see the code in-error and the resulting code that fixed the issue. That way it is documented for future users.

**Comment by msainv** [comment]
@c-schuler I have done the following:



define "Expression_1":
        Previously_defined_expression.value='<3'
        
define "Expression_2":
        [MedicationRequest: medication in valueset_123] 
        

define "Recommended_action_1":
        Previously_defined_expression and Expression_2
		
		error: "Could not resolve call to operator And with signature (System.Boolean,list&lt;FHIR.MedicationRequest>)." errorType="semantic" errorSeverity="error" xsi:type="a:CqlToElmError"/>
		
**Correction made:**
		
I added the "exists" operator in Expression_2 definition
		
define "Expression_1":
        Previously_defined_expression.value='<3'
        
define "Expression_2":
        exists [MedicationRequest: medication in valueset_123] 
        

define "Recommended_action_1":
        Previously_defined_expression and Expression_2	

Results: No CQL error!

**Comment by brynrhodes** [comment]
Closing this issue as not related to the translator.
