### ISSUE TITLE
Retrieve library ELM XML from CQLTranslator

### ISSUE THREAD

**Issue by WilliamParker** [cqframework/clinical_quality_language#258]
We have a use-case where we translate CQL queries to ELM XML programmatically.  This is being done via the CqlTranslator class, which has factory methods that take [input streams, strings, and files](https://github.com/cqframework/clinical_quality_language/blob/v1.2.16/Src/java/cql-to-elm/src/main/java/org/cqframework/cql/cql2elm/CqlTranslator.java#L56).  We can then invoke the [toXml method](https://github.com/cqframework/clinical_quality_language/blob/v1.2.16/Src/java/cql-to-elm/src/main/java/org/cqframework/cql/cql2elm/CqlTranslator.java#L105) to obtain the ELM AST that we then use to run the CQL query.  This works for queries that are entirely self-contained, but the XML returned does not contain the ELM for libraries referenced by the query.  This ELM is necessary for us to compile the query in its entirety.

The necessary information seems to be present in the LibraryManager class, specifically the [private libraries field](https://github.com/cqframework/clinical_quality_language/blob/v1.2.16/Src/java/cql-to-elm/src/main/java/org/cqframework/cql/cql2elm/LibraryManager.java#L20).  Libraries can be located via the [resolveLibrary method on LibraryManager](https://github.com/cqframework/clinical_quality_language/blob/v1.2.16/Src/java/cql-to-elm/src/main/java/org/cqframework/cql/cql2elm/LibraryManager.java#L38) but this method requires that the caller be searching for a particular library.  Additionally, the fact that it takes a list of CqlTranslatorException suggests to me that this may not be intended to be called by external users, but rather used in internal translation.

Would you consider adding/merging a PR to add a method on CqlTranslator like

````
public getLibrariesXmlById <String, String>(){

}
````

where the keys would be the library ID and the values would be the ELM XML for the corresponding libraries?

I think something like this could be accomplished at a user level by walking the AST and finding all libraries that need to be looked up, but this seems like unnecessary complication and still seems potentially problematic if resolveLibrary isn't intended to be called by users.  For an implementor, the cleanest architecture seems to me to be to segregate the translation into an AST into its own component and have the rest of the implementation work purely in terms of this AST, regardless of how that AST was generated.

Alternatively, is there something I'm missing about the API and the reasoning behind it?  Perhaps there is a way to accomplish these goals already that I'm missing.

**Comment by brynrhodes** [comment]
Hi @WilliamParker , it's great to hear that you're using the translator! The translator was designed as a component to be usable within IDE-style environments, so it does have support for loading library sources and translating them as necessary, but you have to register a library source provider so the component know where to find the source. By default, we implement a library source provider that just loads from the current directory, but we've also implemented a loader that will pull source from a FHIR Library resource, for example.

In your environment, you would provide an implementation of the [LibrarySourceProvider](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/cql-to-elm/src/main/java/org/cqframework/cql/cql2elm/LibrarySourceProvider.java) that pulled the source from the appropriate place, and then register it with the following:

    libraryManager.getLibrarySourceLoader().clearProviders();
    libraryManager.getLibrarySourceLoader().registerProvider(new FooLibrarySourceProvider());

Then your class will be invoked whenever the translator needs the source for a library. You'll be given the library identifier and version. You can take a look at the [DefaultLibrarySourceProvider](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/cql-to-elm/src/main/java/org/cqframework/cql/cql2elm/DefaultLibrarySourceProvider.java) for details on how we use the identifier and version to resolve to a file name by default.

Please let me know if this doesn't address the question, or if there are other ways to improve this and make it easier to use, happy to make changes that would improve the developer experience for the translation components.

**Comment by WilliamParker** [comment]
I don't think that addresses the question I had, although it is good to confirm that implementing LibrarySourceProvider is an expected use-case. I'll try to clarify.  I am providing a LibrarySourceProvider implementation and registering it; my debug statements prove that it is being called by CQFramework.  In Java (the actual code is in another JVM language), I'd be doing something like this:

````
public MyLibrarySourceProvider implements LibrarySourceProvider {
     String getLibrarySource(VersionedIdentifier){
     
     }
}
````

The issue I'm having is that when I want to retrieve the library, I need a VersionedIdentifier to access it through the [resolveLibrary method](https://github.com/cqframework/clinical_quality_language/blob/v1.2.16/Src/java/cql-to-elm/src/main/java/org/cqframework/cql/cql2elm/LibraryManager.java#L38).  What I'm trying to do is have a function in my code that takes a CQL query and returns the ELM for both it and all libraries it consumes, either directly or transitively.  I can accomplish this by accessing the libraries field, but obviously forcibly accessing a private field isn't ideal.  That is:


````
    // Reflect on the LibraryManager class and access the java.lang.reflect.Field object for the libraries field.
    Field librariesField LibraryManager.class.getDeclaredField("libraries");
    // Forcibly reset this field from private to public.
    librariesField.setAccessible(true)
    Map<String, String> libraries = librariesField.get(myLibraryManager);
    Map<String, String> idToElm = new HashMap<String, String>();
    for (String id : libraries.keySet()):
           String elm = myCqlTranslator.convertToXml(libraries.get(id).getLibrary());
           idToElm.put(id, elm);
````

This gives me the information I need to return a map of the information:

````
{"query" : cql-query-elm
 "libraries" : {"library-id" : library-elm}}
 ````

 which can then be used in my compiler to create an executable format.

 Essentially, I was wondering whether the libraries field needs to be private or if a public accessor doing the same could be created, or alternatively if I'm missing a better way to retrieve all the libraries's ELM.

It would certainly be possible to wait to resolve the libraries until our compiler walked the AST, or to create a custom walk of it to find all libraries inside it upfront, but it seems like a cleaner separation of concerns to create a single pure data representation of all relevant CQL logic and pass it along rather than having callbacks into cql2elm.

Thanks for this project and the help by the way - implementing this is much easier with an AST to work with.

**Comment by brynrhodes** [comment]
Apologies for the delayed response here. Yes, that makes sense to provide a single method, and it would just be a convenient packaging of all the results. So looking at the translator methods now, given that the translator is instantiated on a particular string of source CQL, it seems like a method to retrieve the ELM for any referenced libraries would be ideal, so something like:

    public Map<String, Library> getReferences()

The result of this would be the unique set of libraries referenced by the source CQL, transitively. 

Then I'd want to also include something like:

    public Map<String, String> getReferencesAsXml()
    public Map<String, String> getReferencesAsJson()

To support easily obtaining the ELM in a particular format. Does that make sense?

**Comment by WilliamParker** [comment]
That should work for us @brynrhodes, thanks.  We may not have time to create a PR in December but hopefully we can get to it in the near future if it isn't otherwise addressed first.

cc @bdrillard

**Comment by brynrhodes** [comment]
Adressed in [1.3.14](https://github.com/cqframework/clinical_quality_language/releases/tag/v1.3.14)
