### ISSUE TITLE
Reduce nesting level in output ELM for binary operators such as union and intersect

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/clinical_quality_language#259]
When translating binary operators that can be chained such as union, intersect, and except, the translator will produce a right-deep tree. For long chains, this can result in a deeply nested ELM output.

Within ELM itself, this could potentially be addressed by defining these operators as nary instead of binary operators. That should be submitted as a comment against the CQL specification.

Within the translator, without changing ELM, the output should be changed to produce a bushy tree, rather than a right-deep tree as it currently does.

**Comment by p9g** [comment]
See also http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=1500

**Comment by brynrhodes** [comment]
Included in the [1.3 CQL Ballot](https://github.com/cqframework/clinical_quality_language/releases/tag/v1.3.0-SNAPSHOT) release.
