### ISSUE TITLE
Translator fails to parse Message() with null code argument

### ISSUE THREAD

**Issue by duncand** [cqframework/clinical_quality_language#262]
This is a valid Message() call with a null given to the "code" third argument:

```
define x: Message(null, true, null, 'Message', 'yadayada')
```

However, the Translator fails to translate that CQL to ELM, giving the following message:

```
null[1:11, 1:58]Could not resolve call to operator Message with signature (System.Any,System.Boolean,System.Any,System.String,System.String).
```

This should succeed as null is a valid argument for a String parameter.

Moreover, and critically, the above define sometimes does translate if certain other code lines are placed above it, such as this one:

```
define y: Message(null, true, '', 'Message', 'yadayada')
```

In that case, both defines then translate and execute with the correct behaviour, such that a null code argument suppresses an attempt to output a code.

Placing the y after the x does not prevent the translation error.

The Translator clearly has a bug which should be fixed.  However, it appears there is a feasible workaround for where one wants to use a null "code" argument with Message().  That workaround is to add a line like this to the top of the list of defines in the library with that Message() call, or specifically, above all defines that either contain such as Message() call or that reference any other defines which do, directly or indirectly.

```
define private ExistenceOfThisEarlierDefineIsWorkaroundForTranslatorDeathWithLaterMessageNullCodeArg: Message(null, true, '', 'Message', '')
```

**Comment by c-schuler** [comment]
This works for me:
define x: Message(null, true, null as String, 'Message', 'yadayada')

I don't believe this is a bug.

**Comment by duncand** [comment]
Yes, you are right, qualifying the null with "as String" is the best solution here.

There still appears to be a bug though, which is that the original "define x" DOES parse as-is if and only if there is a separate Message() call prior to it.

However, as the main topic of this issue is resolved not a bug, I will close this issue, and I can re-raise the other matter under its own issue later if warranted.

Thank you.
