### ISSUE TITLE
More Examples required

### ISSUE THREAD

**Issue by sumanlucky5** [cqframework/clinical_quality_language#263]
Hi can you attach a little more examples, to know more about the project's functionality. Right  now there are only two measure examples that are simple. Some examples of EH measures would be helpful. And also can you update the workspace with the latest code if any.

**Comment by brynrhodes** [comment]
Hi @sumanlucky5, there are lots of examples in the Formatting and Usage wiki [here](https://github.com/esacinc/CQL-Formatting-and-Usage-Wiki/wiki/Example-Measures).

As far as updating the workspace, I'm not sure I understand what workspace you're talking about? This is the repository for the tooling, lots of different workspaces use this tooling.

**Comment by sumanlucky5** [comment]
The project supports Quick data model, is there any reason you have not used QDM data model?

**Comment by brynrhodes** [comment]
The project supports QDM as well, in fact primarily, as the QDM support is the most developed of the data models. We have been working closely with QDM stewards and stakeholders throughout this process. To use QDM in CQL, just include the following `using`:

    using QDM version '5.3'

**Comment by brynrhodes** [comment]
Closing this as an answered question. Please feel free to submit another issue if you have more questions.
