### ISSUE TITLE
Models with '.' - delimited inner class names are not supported

### ISSUE THREAD

**Issue by sotty** [cqframework/clinical_quality_language#266]
The grammar rule 
namedTypeSpecifier
: (modelIdentifier '.')? identifier
;
does not recognize names such as (FHIR.)CommunicationRequest.Payload, e.g.:

define "Alert Reques":
  CommunicationRequest {
    payload : FHIR.CommunicationRequest.Payload {
                      content: string{ value: 'Alert!' } } ,
    subject: Reference{ identifier: Patient.identifier }
  }

**Comment by brynrhodes** [comment]
STU comment [#1507](http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=1507), approved as part of a CQL Block vote on 2018-02-28, addresses this issue.

**Comment by brynrhodes** [comment]
Included in the [1.3 CQL Ballot](https://github.com/cqframework/clinical_quality_language/releases/tag/v1.3.0-SNAPSHOT) release.
