### ISSUE TITLE
Unexpected behavior for return clauses in a query

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#268]
CQL R1, STU 2 has the following description for return clauses:

```
The return clause of a CQL query allows the results of the query to be shaped. In most cases, the results of a query will be of the same type as the primary source of the query. However, some scenarios involve the need to extract only specific elements or to perform computations on the data involved in each element.
```

Based on this, the understanding is that items associated to the specified retrieve may be returned or the result of a function that is operating on something within the retrieve. 
It does not appear that items that are foreign to the actual retrieve should be able to be returned. For example:

    ["Intervention, Performed"] I
        return ["Procedure, Performed"]

However, CQL-to-ELM appears to be supporting

    ["Intervention, Performed": "Referral"] I
        return ["Procedure, Performed": "Laparoscopy"]

Is this by design?

**Comment by brynrhodes** [comment]
This is legal CQL, yes. The expression in a return is allowed to be any arbitrary expression. In this case, it's hard to see how that would be useful, and the result would be the same as just invoking `["Procedure, Performed": "Laparoscopy"]`. There are, however, valid use cases for returning an expression that is not related to the source, such as:

    ["Procedure, Performed": "Laparoscopy"] P
      return 'There are Laparoscopy Procedures for this Patient'

**Comment by JSRankins** [comment]
In the example provided, I would think you would want to check for the nullness of P before returning that there were Laparoscopy procedures. 

For example, 

["Procedure, Performed": "Laparoscopy"] P
  return if P.code is not null then 'There are Laparoscopy Procedures for this Patient'

In that case, that would not violate what I'm suggesting, because the return is based on something specifically associated to an item in the retrieved set. 
If you are suggesting that the return does not have to be associated with anything in the retrieve, I think that could cause an issue in CQL-based HQMF, because the HQMF's data criteria section would show up with an entry based on the retrieve in the CQL definition, which may never get used anywhere. For example, if I had done something like the following, the Intervention would should show up in the corresponding HQMF's data criteria because of rules in CQL-based HQMF, even in the case where the Intervention was not used anywhere else in the logic: 

["Intervention, Performed": "Referral"] I
    return ["Procedure, Performed": "Laparoscopy"]

The presence of that data criteria entry could have an impact on what gets reported for the measure.

**Comment by brynrhodes** [comment]
> In the example provided, I would think you would want to check for the nullness of P before returning that there were Laparoscopy procedures.

Well, checking that the Code is not null isn't quite checking for the "nullness of P". You could have a Procedure, Performed that didn't have a Code, and it would still be a Procedure, Performed. I think what you're saying is that you'd want to make sure that there was at least one Procedure, Performed in the result, which is what the constant return does, because of the fact that the return of a query is distinct. If there are no Procedure, Performed elements, then the result of the query will be an empty list:

    { }

If there are any Procedure, Performed elements, then the result of the query will be:

    { 'There are Laparoscopy Procedures for this Patient' }

**Comment by JSRankins** [comment]
Thanks Bryn. I agree in theory, but I don't expect that unknown procedures would actually be recorded. Even if they were, I have a difficult time seeing where it would be useful to capture them. It's possible. At any rate, this does not really address the issue from a CQL-based HQMF side that I'm trying to bring up. Perhaps this is more specific CQL-based HQMF 'issue' is a discussion for another forum though. Thoughts?

**Comment by brynrhodes** [comment]
Yeah, from the base CQL specification perspective, the return clause is by design any expression and I wouldn't want to limit that flexibility. I can see it maybe being guidance in the CQL-Based HQMF IG, or even style-guide type material though.
