### ISSUE TITLE
Unable to set request date in CQL engine

### ISSUE THREAD

**Issue by jscherer-motivemi** [cqframework/clinical_quality_language#279]
When executing CQL rules, the "user" should be able to use either Today() or a specified date as input to the CQL engine. The engine should default to today unless otherwise specified. The engine should support setting a specified date/time for execution as input to the engine.

**Comment by c-schuler** [comment]
Hi Julie,

This issue has been addressed in the cql_engine repository. See the following [issue](https://github.com/DBCG/cql_engine/issues/34). This is available in the 1.2.38-SNAPSHOT version of the engine.

**Comment by cmoesel** [comment]
If you are talking about the coffee-script based engine in _this_ repository (as opposed to the other reference implementation at https://github.com/DBCG/cql_engine), then this is not yet supported.  I agree that it should be, but I'm not sure when I'd be able to get to it.  If you're interested in contributing a pull request, we'd gladly consider it.

On the other hand, if you are talking about the Java-based engine, see the other Chris's comment above.

**Comment by c-schuler** [comment]
Whoops, I may have jumped to the wrong conclusion there. Thanks for the follow-up Chris.

**Comment by brynrhodes** [comment]
Since it is something the JS engine should support, I've labeled this an enhancement and assigned it to that project. I've added the help wanted label too to let potential contributors know this would be a good one to jump in and help with.

**Comment by jscherer-motivemi** [comment]
All, sorry that I logged this issue in the wrong project.I will try to keep the two projects straight from now on.

**Comment by cmoesel** [comment]
It's alright.  I've been waiting for someone to ask for that in the CoffeeScript/JS project. ;-)

**Comment by brynrhodes** [comment]
This issue was moved to cqframework/cql-execution#43
