### ISSUE TITLE
LibraryManager isn't returning cached libraries

### ISSUE THREAD

**Issue by c-schuler** [cqframework/clinical_quality_language#284]
In this [block of code](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/cql-to-elm/src/main/java/org/cqframework/cql/cql2elm/LibraryManager.java#L51-L61) the LibraryManager will translate the library if a different version of the library isn't already loaded. However, if the library is cached, it isn't retrieved from the cache.

**Comment by brynrhodes** [comment]
This feature is included in release [1.2.19](https://github.com/cqframework/clinical_quality_language/releases/tag/v1.2.19)
