### ISSUE TITLE
Indexed Accessors in Retrieve Code Properties

### ISSUE THREAD

**Issue by bdrillard** [cqframework/clinical_quality_language#288]
I've noticed that the `codeProperty` of a `retrieve` apparently cannot be resolved if that path makes use of an indexer. For [Encounter](https://www.hl7.org/fhir/encounter.html), `type` is a CodeableConcept field of cardinality 0..1. We expect the following queries to compile correctly (and they do):

```
define EncounterPriorityRetrieve: exists([Encounter: priority in "ValueSet"])
define EncounterPriorityQuery: exists([Encounter] E where E.priority.coding[0].code = 'value')
```
Encounter also has the `type` field of cardinality 0..*. This query compiles as expected, 

```
define EncounterTypeQuery: exists([Encounter] E where E.type[0].coding[0].code = 'value')
```

but if we attempt to use an indexed accessor that would evaluate to a single CodeableConcept in the retrieve, we get the ELM semantic warnings, `"Could not resolve code path type[0] for the type of the retrieve FHIR.Encounter."` and `"Could not resolve membership operator for terminology target of the retrieve."`:

```
define EncounterTypeRetrieve: exists([Encounter: "type[0]" in "ValueSet"])
```

In the ELM, the `codeProperty` on the retrieve is simply `"type[0]"`. 

Should CQL have retrieve path behavior defined against indexed fields where the index would resolve to a single CodeableConcept to check against a ValueSet, or is perhaps a CQL author expected to filter lists of CodeableConcepts against a valueset in a different way? If the former, should the `codeProperty` field have more AST information attached than just a string of the field name and array index, or should an implementation against the AST parse out the necessary index operation from that `codeProperty` string?

**Comment by brynrhodes** [comment]
Hi @bdrillard, the translator will resolve paths through list-valued properties, so you don't provide the indexer in the path. However, because the code path is resolved with either an `in` or an `=`, the code path will be "demoted" to a singleton if it's list-valued. In other words, the translator will assume that the data access layer will "decide" which index of the list to use, where the most reasonable approach is to say that if the intersection is non-empty. This is actually the subject of an STU comment as well, and we plan to introduce an overload of "in" that can work in this way, specifically to support the use of List-valued code properties. Does that help?

**Comment by bdrillard** [comment]
Thanks @brynrhodes for the clarification. I see we should just use `type` in this case, and let the compiler discover how to handle the field. Since as you say the field gets "demoted" to a _singleton_ (which I can also see with the semantic warning that's thrown), but that reasonable behavior is to check if the code/ValueSet intersection is non-empty, do you suggest we address the CodeableConcept array at index 0, or that we scan across the CodeableConcept array for the first instance having a Coding in the ValueSet?

A formally overloaded `in` would be very useful. At the moment, it appears from the perspective of the generated ELM, there's nothing to distinguish a retrieve against an array of CodeableConcept from a single CodeableConcept (the generated `Retrieve` node has the same form with a string `codeProperty` and no other type information in either case), so for a CQL runtime implementation, it seems we can't statically determine whether we should be addressing an array of CodeableConcept or a scalar CodeableConcept, but would have to check if the field is an array or scalar at runtime.

**Comment by brynrhodes** [comment]
STU comment [#1447](http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=1447) will add an overload for `in` to take a list of `CodeableConcept` as the first argument.
