### ISSUE TITLE
QDM 4.3 cannot resolve "birth datetime"

### ISSUE THREAD

**Issue by Caskman** [cqframework/clinical_quality_language#292]
I have the following cql

```
using QDM version '4.3'

context Patient

define "test1":
        AgeInYearsAt(@2017-01-01T00:00:00.000)

```

I attempted to compile it and got the following:

```
================================================================================
TRANSLATE ./Test.cql
Translation failed due to errors:
Error:[6:2, 6:39] Member birth datetime not found for type QDM.Patient.
```

I then fixed this by modifying line 5 of Src/java/qdm/src/main/resources/gov/healthit/qdm/qdm-modelinfo-4.3.xml

from
`        <ns4:element name="birthDatetime" type="System.DateTime"/>`
to
`        <ns4:element name="birth datetime" type="System.DateTime"/>`

then rebuilt the compiler and ran it again and it was successful.

I'm not sure if the solution is just to submit this as a PR so I posted here just to make sure it was brought to your attention.

**Comment by brynrhodes** [comment]
Hi @Caskman , yes, it looks like this is just a bug in the modelinfo for QDM 4.3. If you can submit a pull request, that would be fantastic.
