### ISSUE TITLE
coffeescript execution framework example throws exception

### ISSUE THREAD

**Issue by twilson650** [cqframework/clinical_quality_language#294]
I followed the example in the README.md here

https://github.com/cqframework/clinical_quality_language/tree/master/Src/coffeescript/cql-execution

And when I ran the simple age example I got the following error. I suspect the sample patient format might be wrong, as it's trying to access an "entry" object that doesn't exist:

$ node age-execute
Library {
  source: 
   { library: 
      { identifier: [Object],
        schemaIdentifier: [Object],
        usings: [Object],
        parameters: [Object],
        statements: [Object] } },
  usings: [ { name: 'QUICK', version: undefined } ],
  parameters: 
   { MeasurementPeriod: 
      ParameterDef {
        name: 'MeasurementPeriod',
        default: [Interval],
        parameterTypeSpecifier: undefined } },
  codesystems: {},
  valuesets: {},
  codes: {},
  concepts: {},
  expressions: 
   { Patient: 
      ExpressionDef {
        name: 'Patient',
        context: 'Patient',
        expression: [SingletonFrom] },
     InDemographic: ExpressionDef { name: 'InDemographic', context: 'Patient', expression: [And] } },
  includes: {} }
/Users/tomwilson/github/clinical_quality_language/Src/coffeescript/cql-execution/lib/cql-patient.js:126
    filtered = this.entry().filter(function(e) {
                           ^

TypeError: Cannot read property 'filter' of undefined
    at Bundle.FHIR.Bundle.findRecords (/Users/tomwilson/github/clinical_quality_language/Src/coffeescript/cql-execution/lib/cql-patient.js:126:28)
    at Bundle.FHIR.Bundle.findRecord (/Users/tomwilson/github/clinical_quality_language/Src/coffeescript/cql-execution/lib/cql-patient.js:141:17)
    at PatientSource.nextPatient (/Users/tomwilson/github/clinical_quality_language/Src/coffeescript/cql-execution/lib/cql-patient.js:239:79)
    at new PatientSource (/Users/tomwilson/github/clinical_quality_language/Src/coffeescript/cql-execution/lib/cql-patient.js:228:12)
    at Object.<anonymous> (/Users/tomwilson/github/clinical_quality_language/Src/coffeescript/cql-execution/lib/age-execute.js:15:13)
    at Object.<anonymous> (/Users/tomwilson/github/clinical_quality_language/Src/coffeescript/cql-execution/lib/age-execute.js:37:4)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)

**Comment by cmoesel** [comment]
Thanks for reporting this.  We'll take a look at it and get back to you.  Last time I checked it was working, but some things may have changed since then.

**Comment by cmoesel** [comment]
It looks like the example in the `Src/coffeescript/cql-execution/src/example` folder was up-to-date, but the corresponding walk-through in the `README.md` was _not_.  There were several issues which it seems you must have already run into and figured out, but the biggest issue was that the format of the patient data was incorrect -- it needed to be formatted as FHIR bundles.  It should work if you update your code to use the following `psource` definition:

```coffee
psource = new cql.PatientSource [ {
    "resourceType": "Bundle",
    "id": "example1",
    "meta": {
      "versionId": "1",
      "lastUpdated": "2014-08-18T01:43:30Z"
    },
    "base": "http://example.com/base",
    "entry" : [{
        "resource": {
        "id" : "1",
        "meta" :{ "profile" : ["patient-qicore-qicore-patient"]},
        "resourceType" : "Patient",
        "identifier": [{ "value": "1" }],
        "name": {"given":["John"], "family": ["Smith"]},
        "gender": "M",
        "birthDate" : "1980-02-17T06:15"}
        }
    ]
  }, {
    "resourceType": "Bundle",
    "id": "example1",
    "meta": {
      "versionId": "1",
      "lastUpdated": "2014-08-18T01:43:30Z"
    },
    "base": "http://example.com/base",
    "entry" : [{
        "resource": {
        "id" : "2",
        "meta" :{ "profile" : ["patient-qicore-qicore-patient"]},
        "resourceType" : "Patient",
        "identifier": [{ "value": "2" }],
        "name": {"given":["Sally"], "family": ["Smith"]},
        "gender": "F",
        "birthDate" : "2007-08-02T11:47"}
        }
    ]
  } ]
```

I've updated the README in the Pull Request linked above this comment.

Thanks for reporting this, and I apologize for the inconvenience!

**Comment by twilson650** [comment]
Thank you, yes, I figured it was the FHIR bundle format. The script is running without error, however it looks like it's returning both patients in the results when it should only be returning one (age between 2 and 18).

**Comment by twilson650** [comment]
Okay now I see the inDemographic attribute, and it is being populated correctly. Closing this.
