### ISSUE TITLE
FHIR 1.0.2 modelinfo missing primaryCodePath for MedicationStatement

### ISSUE THREAD

**Issue by cmoesel** [cqframework/clinical_quality_language#296]
In [fhir-modelinfo-1.0.2.xml](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/quick/src/main/resources/org/hl7/fhir/fhir-modelinfo-1.0.2.xml#L3625), the definition for `MedicationStatement` is missing the `primaryCodePath`:
```xml
<ns4:typeInfo xsi:type="ns4:ClassInfo" name="FHIR.MedicationStatement" retrievable="true" baseType="FHIR.DomainResource">
```

Both [fhir-modelinfo-3.0.0.xml](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/quick/src/main/resources/org/hl7/fhir/fhir-modelinfo-3.0.0.xml#L7688) and [fhir-modelinfo-3.2.0.xml](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/quick/src/main/resources/org/hl7/fhir/fhir-modelinfo-3.2.0.xml#L9531), however, assign it a `primaryCodePath` of `medicationCodeableConcept`:
```xml
<ns4:typeInfo xsi:type="ns4:ClassInfo" name="MedicationStatement" retrievable="true" primaryCodePath="medicationCodeableConcept" baseType="FHIR.DomainResource">
```

If you agree that this is a bug in the FHIR 1.0.2 modelinfo, I'll be glad to submit a PR.

**Comment by cmoesel** [comment]
As seen above, I went ahead and submitted a PR to make this real easy if you agree it's a bug.

**Comment by brynrhodes** [comment]
Hi @cmoesel , agreed, that is the bug. Thank you for the PR!
