### ISSUE TITLE
Could not resolve membership operator for terminology target of the retrieve.

### ISSUE THREAD

**Issue by cmoesel** [cqframework/clinical_quality_language#298]
When compiling CQL against FHIR 1.0.2, most retrieves cause a warning.  For example, given the following simple CQL:
```
library Test version '1'
using FHIR version '1.0.2'
valueset "Systolic Blood Pressure": '2.16.840.1.113762.1.4.1104.2'
context Patient
define SBP: [Observation: "Systolic Blood Pressure"]
```
the following warning is emitted:
```
Warning:[5:13, 5:52] Could not resolve membership operator for terminology target of the retrieve.
```

I confirmed that `Observation` does define a `primaryCodeProperty`.  Might the problem be that the `primaryCodeProperty` (which is `code`) is a `FHIR.CodeableConcept` instead of a `System.CodeableConcept`?

**Comment by brynrhodes** [comment]
Hi @cmoesel , yes, that's the problem. If you include FHIRHelpers, with this line:

    include FHIRHelpers version '1.0.2' called FHIRHelpers

Then it translates successfully because the implicit conversion from FHIR.CodeableConcept to System.Concept will be used.

**Comment by cmoesel** [comment]
Thanks, Bryn!  I will give it a try!

**Comment by cmoesel** [comment]
I can now confirm that including `FHIRHelpers` resolved the issue.  Thanks for the tip.
