### ISSUE TITLE
Expected Behavior of "Instance" Construction over Null Values

### ISSUE THREAD

**Issue by bdrillard** [cqframework/clinical_quality_language#300]
We've noticed queries where the a `System.Quantity` would be instantiated from the results of upstream functions. In some instances, those upstream functions would return null, leading to null inputs to an instance-selector's `value` and/or `unit` fields. The documentation doesn't give expected nullary behavior for instance-selectors (for Quantity, or any other type). It seems behavior might be difficult to define since it could vary on the type. We could instantiate a CodeableConcept where every field is null, so perhaps we don't want to just return null if any arbitrary field is null, but on the other hand, what would you have if you instantiate a Quantity with a null unit? 

Is there a preferred way to handle `Instance` construction when fields may be null?

**Comment by brynrhodes** [comment]
Hi @bdrillard, thank you for the feedback. You're right that the spec could be clearer here, both with respect to how structured and class values are constructed in the absence of explicit values for all the elements of the tuple or class, as well as how quantities behave if the units are null. I think both these are worthy of STU comments on the specification itself.

I think the most reasonable behavior for an instance selector is that for any elements not specified by the selector, the resulting tuple or class instance has null for those elements. I think this applies to the Quantity type as well.

But in saying that, I have to say then that I think the most reasonable behavior for operations involving quantities with null units is that null is equivalent to the default unit `'1'`, which is how we defined the implicit conversion from Integer or Decimal to Quantity.

I've submitted STU comment [#1538](http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=1538) to clarify the behavior of instance selectors, and STU comment [#1539(http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=1539) to clarify the behavior of operations involving quantities with null units.
