### ISSUE TITLE
FHIRHelpers

### ISSUE THREAD

**Issue by kwboone** [cqframework/clinical_quality_language#302]
I got an exception in Context.resolveFunctionRef when using FHIRHelpers 1.0.2.

Could not resolve call to operator 'ToConcept' in library 'FHIRHelpers'.
	at org.opencds.cqf.cql.execution.Context.resolveFunctionRef(Context.java:332)
	at org.opencds.cqf.cql.elm.execution.FunctionRefEvaluator.evaluate(FunctionRefEvaluator.java:24)
	at org.opencds.cqf.cql.elm.execution.PropertyEvaluator.evaluate(PropertyEvaluator.java:16)
	at org.opencds.cqf.cql.elm.execution.FunctionRefEvaluator.evaluate(FunctionRefEvaluator.java:30)
	at org.opencds.cqf.cql.elm.execution.EqualEvaluator.evaluate(EqualEvaluator.java:131)
	at org.opencds.cqf.cql.elm.execution.ExpressionDefEvaluator.evaluate(ExpressionDefEvaluator.java:20)
	at org.opencds.cqf.cql.elm.execution.ExpressionRefEvaluator.evaluate(ExpressionRefEvaluator.java:14)
	at org.opencds.cqf.cql.elm.execution.OrEvaluator.evaluate(OrEvaluator.java:30)
	at org.opencds.cqf.cql.elm.execution.OrEvaluator.evaluate(OrEvaluator.java:30)
	at org.opencds.cqf.cql.elm.execution.OrEvaluator.evaluate(OrEvaluator.java:30)
	at org.opencds.cqf.cql.elm.execution.OrEvaluator.evaluate(OrEvaluator.java:30)
	at org.opencds.cqf.cql.elm.execution.ExpressionDefEvaluator.evaluate(ExpressionDefEvaluator.java:20)
	at org.opencds.cqf.cql.elm.execution.ExpressionRefEvaluator.evaluate(ExpressionRefEvaluator.java:14)

Basically what was calling it was something like the following:

// A re-usable function to get the response code for a specific question from the occupational factors assessment.
define function Response(QuestionConcept Concept):
  FHIRHelpers.ToConcept(MostRecentObservation(QuestionConcept).valueCodeableConcept)

define function MostRecentObservation(QuestionConcept Concept):
  Last([Observation: QuestionConcept] O sort by issued)

The problem appears to be the fact that Last() of an empty list is null.  The function resolver tries to match argument types, but fails to match on null because it gets converted to the type represented by Object.class, which is not assignable to a more refined class.

What I wound up doing was modifying FHIRHelpers to deal with nulls as follows:
define function ToCode(coding FHIR.Coding):
    if coding is null then null else System.Code {
      code: coding.code.value,
      system: coding.system.value,
      version: coding.version.value,
      display: coding.display.value
    }
    
define function ToConcept():
 null

define function ToConcept(concept FHIR.CodeableConcept):
    if concept is null then null else if concept.coding is null then System.Concept {
        display: concept.text.value
    } else System.Concept {
        codes: concept.coding C return ToCode(C),
        display: concept.text.value
    }

I also added the following.  
define function ToDateTime(): null
define function ToTime(): null
define function ToInteger(): null
define function ToDecimal(): null
define function ToBoolean(): null

I know the first of these was needed, likely because I ran into the same problem with ToDateTime() as a result of probably this expression:
define HasOldResponse:
  exists ( MostRecentQuestionObservations O where O.issued before (Today() - 6 months) )

Making these changes resolved my resolution errors, but I think there may be a better solution for these functions related to implicit null conversion.

**Comment by kwboone** [comment]
[FHIRHelpers-1.0.2.cql.txt](https://github.com/cqframework/clinical_quality_language/files/1761169/FHIRHelpers-1.0.2.cql.txt)

**Comment by kwboone** [comment]
OK, forget all the previous.  This seems to be the resolution in the Context class:

    private boolean isType(Class<?> argumentType, Class<?> operandType) {
        return operandType.isAssignableFrom(argumentType) || 
        		// handle nulls appropriately
        	   (argumentType.equals(Object.class) && !operandType.isPrimitive());
    }

Since: resolveType() will only return Object.class when the value given it is null, we can basically use that as a signal that null is involved.  In cases where null is involved and the object isn't a primitive object, then null will be assignable to it, and so we can return true in that case.

I see a lot of issues in resolveFunctionRef which look like they need to be addressed.  The argument matching is imperfect because if the number of arguments is greater than the number of operands, it will still match the function reference.  I'm not sure that's intentional.  I also wonder what the behavior should be with regard to multiple conversions for classes in a hierarchy.  For example: if ToX(Model.SuperType) and ToX(Model.Type) are both defined, the resolution order is apparently indeterminate, as resolveFunctionRef will match the first or second one depending on the order in which they appear in the list.  I also wonder about what should happen with regard to implicit type conversions in this area.

**Comment by kwboone** [comment]
Not sure how this got closed.

**Comment by brynrhodes** [comment]
For the functionRef resolve, there is an STU comment [#1432](http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=1432) that will add the resolved overload signature to the FunctionRef so that the engine doesn't have to perform that resolution at run-time. That's the root of the problem here, the engine doesn't have all the context it needs to determine the appropriate resolution (nor should it, it's a compile-time concern). The simplest workaround is to define unqiue functions, rather than overloading the same function name with different signatures. Would that work in this case?

**Comment by cmoesel** [comment]
That's the workaround I've tended to use @brynrhodes, but IIRC, `FHIRHelpers` uses overloaded functions -- and since CQL-to-ELM provides the `FHIRHelpers` it compiles against, I'm not sure if it's possible to provide a modified version of it.  Probably the best that could be done is re-implement the needed functions in a separate library and call them instead of `FHIRHelpers` -- but that doesn't help for any cases in which the translator applies an implicit conversion using `FHIRHelpers`.

**Comment by cmoesel** [comment]
BTW -- I'm really looking forward to those signatures in the `FunctionRef`s.  Glad that will be happening!

**Comment by brynrhodes** [comment]
Included in the [1.3 CQL Ballot](https://github.com/cqframework/clinical_quality_language/releases/tag/v1.3.0-SNAPSHOT) release.
