### ISSUE TITLE
InValueSet on non-Code types

### ISSUE THREAD

**Issue by WilliamParker** [cqframework/clinical_quality_language#306]
Both of the following expressions seem to be accepted by the CQL2ELM translator, where C is an alias for a FHIR 3.0.0 Condition:

```
C.category.coding[0].code in "Problem"
C.category.coding[0] in "Problem"
```

Specifically, they are translated into an InValueSet node, where the immediate child is a FHIRHelpers.toString and a FHIRHelpers.toCode call respectively.  The InValueSet definition in clinicalexpression.xsd does seem to allow any Expression:

```
<xs:complexType name="InValueSet">
  <xs:annotation>
    <xs:documentation>The InValueSet operator returns true if the given code is in the given value set.
Note that this operator explicitly requires a ValueSetRef as its valueset argument. This allows for both static analysis of the value set references within an artifact, as well as the implementation of valueset membership by the target environment as a service call to a terminology server, if desired.</xs:documentation>
  </xs:annotation>
  <xs:complexContent>
    <xs:extension base="Expression">
      <xs:sequence>
        <xs:element name="code" type="Expression"/>
        <xs:element name="valueset" type="ValueSetRef"/>
      </xs:sequence>
    </xs:extension>
  </xs:complexContent>
</xs:complexType>
```

Passing any arbitrary expression doesn't make sense to me though.  For example, asking if a DateTime is in a valueset would be nonsensical.
    

The July 2017 CQL specification indicates that InValueSetRef "Tests a string, code, or concept for membership in a valueset".

I'm basically looking for clarification of the expected semantics here.  If I simply use the code ID String should the InValueSet node return "true" if it is in the valueset for any code system?  Alternatively, is this an oversight in the spec and/or the CQL2ELM translator?  Perhaps CQL2ELM actually should fail in this instance and the spec just hasn't been updated accordingly.

**Comment by WilliamParker** [comment]
To give a concrete example:

Suppose we have a valueset "Outpatient" containing code "O" from "CodeSystem1".  Now suppose that code "O" from "CodeSystem2" means "Operation" i.e. a surgical operation.  Suppose that for some Encounter Encounter.class.coding[0]= "O" from "CodeSystem2".  Should Encounter.class.coding[0].code be considered to be in valueset "Outpatient"?

**Comment by brynrhodes** [comment]
@WilliamParker , apologies for the delayed response here. This is a good question, and you're right that the spec isn't clear about the expected behavior. We allow it specifically to support comparisons where the code system is implied by the context, which is the case with FHIR code elements, but a consequence is that it can also be used where the code system is not understood. My leaning would be to say that if the code system is not implied by the context, that the membership test would result in false.

**Comment by brynrhodes** [comment]
I submitted STU comment [#1556](http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=1556) to address this clarification.

**Comment by brynrhodes** [comment]
@WilliamParker After discussion with the CDS WG, the comment was resolved to indicate that a run-time error is the best behavior because attempting to use a string overload with a value set that contains multiple code systems is ambiguous.

**Comment by WilliamParker** [comment]
Is the ambiguity in terms of the valueset being checked against or the allowed codes on the field?  That is, in the case of an expression like

````
C.category.coding[0].code in "Problem"
````

is the idea to fail if

- The "Problem" valueset has more than one codesystem.
- The ultimate source of the code could have multiple codesystems?  This could be tricky to implement if the code in question wasn't a direct property access (probably an unusual case but I think the syntax would allow it).

It sounds like you're going for the former, and not the latter, but I'd like to clarify.

**Comment by brynrhodes** [comment]
The former, the determination can be made entirely within the context of the In evaluation.
