### ISSUE TITLE
Included In Semantics

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#310]
The following signature is provided for 'Included In' in CQL R1 STU 2:

For intervals:   _included in precision (left Interval<T>, right Interval<T>) Boolean_
For lists:  _included in(left List<T>, right list<T>) Boolean_

Per the above signatures, a point should not be able to be used as the first parameter to the 'Included In' operator. Per the spec, it appears that the 'In' operator should be used to determine if a point is in an interval or list. However, CQL-to-ELM is supporting the following: 

month from .authorDatetime included in Interval[1, 4]
.code included in "value set"

Is the specification correct in its restriction for the point to list/interval comparison, or does something need to be updated in CQL-to-ELM to restrict 'included in' to lists and intervals?

**Comment by JSRankins** [comment]
@cmoesel  @brynrhodes 
Hi Chris. I understand what you are saying, but then it becomes difficult to prevent 'included in' from being misused, except through some manual review process. For authors, this is a very frustrating situation, because they are being told through the CQL validation that they have valid CQL, but then being told not to do it after some manual review process has completed. This situation recently happened during some measure work. It would be great if there was a hard and fast rule that could be implemented. I hate to make things conditional, but maybe, as a possible solution, for point to interval/list membership tests, 'included in' could be restricted to points that are datetime typed??? That would still allow for the case where someone wants to use 'included in' as 'during'. Thoughts?

**Comment by cmoesel** [comment]
My preference would be to avoid special cases.  They're hard to remember.  I think a new signature should be added to `included in`:
```
included in precision (left Interval<T>, right Interval<T>) Boolean
included in precision (left T, right Interval<T>) Boolean
```
and probably the same approach for lists.

To me, it makes sense outside of dates too.  For example, this rings true for me as well:
```
5 included in Interval[2, 7]
```

The downside here is that there is more than one way to express the same thing.  Does anyone feel strongly about that?

**Comment by JSRankins** [comment]
The change of signatures would be fine with me. The use of 'in' -vs- 'included in' would then become more of an artistic restriction as opposed to a syntactic issue. I also imagine that the use of 'included in' could be controlled through a style guide at that point - e.g., by CMS measure developers.

**Comment by cmoesel** [comment]
Yeah.  I was thinking about that.  A next step might be to deprecate one of them -- but that would be a backwards incompatible change, so we'd want to be very careful about that.

But before we get too carried away, I'd still like to hear what @brynrhodes thinks of the whole matter.

**Comment by brynrhodes** [comment]
Yes, the translator initially disallowed this case, but we opened it up because of this paragraph in section 2.5.5.3:

> In other words, the timing phrases in general compare two quantities, either of which may be an date/time interval or date/time point value, and the boundary access modifiers can be added to a given timing phrase to access the boundary of an interval.

And the result is that something like what @cmoesel is pointing out:

    5 included in Interval[2, 7]

works as expected. So I agree that this is a place where the spec is missing the overload in the reference.

**Comment by brynrhodes** [comment]
I've added comment [1561](http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=1561) to address this.
