### ISSUE TITLE
ucum-essence.xml

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#316]
@brynrhodes 

We are incorporating the UCUM validation code into our installation of the CQL-to-ELM translator. During incorporation of the UCUM validation code, we noted that the ucum-essence.xml file is not available. To compile correctly, the CQLTranslator class is requiring the usum-essence.xml to be available:

ucumService = new UcumEssenceService("/ucum-essence.xml"); 

Should this file be physically part of the code, or is it intended to have users of this code periodically download the ucum-essence.xml from UCUM - http://unitsofmeasure.org/ucum-essence.xml?

**Comment by brynrhodes** [comment]
The UCUM package should include the ucum-essence.xml content as a resource, so that code should just work (it does in our usage). Is there a specific error you are seeing when you try this? Are you referencing the same UCUM package that we do in the translator?

**Comment by JSRankins** [comment]
There is a comment from Grahame Grieve at the top of the UcumEssenceService class in the UCUM package: 

```
/**
 * implements UCUM services. Applications must provide a copy of 
 * ucum-essence.xml as either a stream or a file name to create 
 * the services.
 * 
 * the provided ucum-essence.xml must be released on 25 Apr 2008 
 * or more recent. Note that if the ucum-essence.xml file does not 
 * contain a release date on an attribute of the root element, it 
 * is not more recent than this date (Gunther added it on this date for 
 * this usage, thanks)
 * 
 * See UcumService for documentation concerning the services this class provides
 * 
 * @author Grahame Grieve
 *
 */ 
```
 
In looking through the code on github, the ucum-essence.xml cannot be found.
Is this resource getting added on the fly through Gradle?

**Comment by brynrhodes** [comment]
The ucum-essence.xml file is included as a resource [here](https://github.com/FHIR/Ucum-java/blob/master/src/main/resources/ucum-essence.xml), so it gets built into the Ucum-java package directly.

To confirm, I tried this again and sure enough, I'm seeing the same thing you are now. Not sure how that happened, this was validated prior to the release. I'm marking this as a defect and correcting now.

**Comment by brynrhodes** [comment]
Release [1.2.20](https://github.com/cqframework/clinical_quality_language/releases/tag/v1.2.20) should address this issue, please let me know if it's still occurring.
