### ISSUE TITLE
CQL-to-ELM generating  output without error when no QDM element used in retrieve

### ISSUE THREAD

**Issue by edeyoung** [cqframework/clinical_quality_language#333]
See the following ticket:
https://oncprojectracking.healthit.gov/support/projects/BONNIE/issues/BONNIE-451

In this ticket, the used the value set alone in the logic (never associated it with a retrieve). As a result, the value set is never associated with a QDM element. Should the CQL-to-ELM translator thrown an error in this situation?

**Comment by brynrhodes** [comment]
Apologies for the late followup on this, but the referenced ticket has already been resolved.  In general, it's reasonable for the only reference to a ValueSet to be outside of a retrieve, so I don't think it would be appropriate for the translator to error when a ValueSet is declared in a library but never used in a retrieve.

**Comment by brynrhodes** [comment]
Closing as resolved.
