### ISSUE TITLE
qdm 5.3 model info file includes active datetime for medication order, which was removed in the qdm 5.3 annotated spec

### ISSUE THREAD

**Issue by edeyoung** [cqframework/clinical_quality_language#335]
It looks like this line should be removed: https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/qdm/src/main/resources/gov/healthit/qdm/qdm-modelinfo-5.3.xml#L408

See pages 32 and 59 in https://ecqi.healthit.gov/system/files/QDM_5_3_ANNOTATED_2017August_508.pdf

**Comment by brynrhodes** [comment]
Addressed in 1.3.4-SNAPSHOT
