### ISSUE TITLE
QDM 5.4 Model Info - Active Datetime for Medication Order

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#342]
The [QDM 5.4 Model Info file](https://github.com/cqframework/clinical_quality_language/blob/v13/Src/java/qdm/src/main/resources/gov/healthit/qdm/qdm-modelinfo-5.4.xml) under the v13 branch contains an attribute for "Medication, Order" that was removed from that datatype with QDM 5.3. That attribute is "activeDatetime". Per [QDM 5.4 documentation](https://ecqi.healthit.gov/system/files/QDM_v5_4_508.pdf), activeDatetime should only be available for "Immunization, Order".

**Comment by brynrhodes** [comment]
Addressed in release 1.3.1-SNAPSHOT.
