### ISSUE TITLE
Dependency Refresh for Antlr4

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/clinical_quality_language#343]
Antlr4 tooling has new versions. Note that there may be an issue with the new version that results in incorrect parse trees for negation. See [CQLIT-154](https://oncprojectracking.healthit.gov/support/browse/CQLIT-124) for more.

**Comment by brynrhodes** [comment]
Regression testing with the 4.7.2 ANTLR changes uncovered other issues with the way the updated ANTLR parser resolves potential ambiguities in the CQL. The ticket that initially spawned this issue (CQLIT-154) is an example. Several different resolution approaches are possible, but none of them within the required timeframe for the 1.3 Maintenance release, so this issue will be pulled from 1.3 Maintenance, and resolved as part of the 1.4 Ballot release.

Specifically, the tooling currently uses ANTLR version 4.5. The 4.6 version introduced a significant [change](https://github.com/antlr/antlr4/issues/1398) to the way left-recursive grammars are parsed, which dramatically improves performance (addressing issue #149), but introduces various regression failures and other difficulties due to differences in the resulting parse trees.

The most significant issue is that with ANTLR 4.6+, the following:

    define Test: { 1, 2, 3 } A bunch of gobbledygook that ANTLR ignores

This should result in a failure, but ANTLR parses the list selector and ignores the rest of the input, failing silently.

**Comment by brynrhodes** [comment]
Note that changes to the 1.4 grammar around the specification of keywords and reserved words addressed the performance issue, and likely addresses the issues with switching to 4.6.

**Comment by alexanderkiel** [comment]
It would be nice to have this fixed, because I have real-world queries with long chains of boolean logic. I currently use v1.4.9 with an ANTLR 4.6 runtime. Although this works for me, it seems a bit hacky.
