### ISSUE TITLE
C#/.Net version of CQL to EML converter - calBaseVisitor class is not present

### ISSUE THREAD

**Issue by sumitpkedia** [cqframework/clinical_quality_language#344]
I am trying .net version of converter and calBaseVisitor class is not found.
Do i need to reference nuget , which one to use for .Net 

Also, I am trying this on 2015 VS version and not 2013.
Thanks!

**Comment by brynrhodes** [comment]
Apologies for the delayed response. The .NET project has not had as much interest so it is not at the same level of maturity, and would require a fairly significant effort to bring it on par with the Java-based version. Are you interested in the full translation functionality in a .NET environment? (i.e. full CQL to ELM translation)

**Comment by sumitpkedia** [comment]
Thanks Bryan for getting back , really appreciate it.

Yes, I was exploring/need of .Net version of it, if handy
Else I will try looking at java version and make changes to dot net version. Any tips/tricks I need to aware of if I try my self.

Thanks
Sumeet

**Comment by brynrhodes** [comment]
If you set about updating the .NET one, one thing that helped the Java-based one was a refactoring to split the ELM Builder (LibraryBuilder) from the parser/visitor. I'd recommend that sort of layering in the .NET one too. Other than that, happy coding :)
