### ISSUE TITLE
Incorrect Version of QDM Model Info File Updated to Handle QDM 5.4 Errata Changes

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#348]
Hi @brynrhodes
The incorrect model info file version was updated with snapshot 1.3.2 to handle QDM 5.4 errata changes. Updates were made to the QDM 5.3 model info file, but they should have been made to the QDM 5.4 model info file.

**Comment by brynrhodes** [comment]
Indeed, it looks like I applied to the wrong model info. I'll back the changes out and apply to the correct, and release a new version. Apologies for the mixup.

**Comment by brynrhodes** [comment]
Note that based on discussions with the QDM Owner, we are also aligning on Id, rather than Identifier to avoid changing the existing model info. So prescriberId and dispenserId of type QDM.Id.

**Comment by brynrhodes** [comment]
Included in release 1.3.3-SNAPSHOT
