### ISSUE TITLE
Custom QDM support

### ISSUE THREAD

**Issue by sumitpkedia** [cqframework/clinical_quality_language#350]
Hi , 

Can we create a custom QDM and have it included in 5.3 version of supported QDM. 
And Generate updated model info XML and late use it to generate cql to ELM conversion ? This CQL will be using custom QDM. 

Thanks
Sumeet

**Comment by brynrhodes** [comment]
The translator absolutely supports custom models, you would just need to create a package with the model info and provide an implementation of a [ModelInfoProvider](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/cql-to-elm/src/main/java/org/cqframework/cql/cql2elm/ModelInfoProvider.java).

For example [QdmModelInfoProvider](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/cql-to-elm/src/main/java/org/cqframework/cql/cql2elm/QdmModelInfoProvider.java)

Then register your provider with the [ModelInfoLoader](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/cql-to-elm/src/main/java/org/cqframework/cql/cql2elm/ModelInfoLoader.java#L44) and when you invoke the translator it will call your loader to resolve your model name.

**Comment by sumitpkedia** [comment]
Thanks Bryan , .
I was trying to modify existing QDM for 5.3 model - add custom datatype and category to xsd and then generate new modelinfo.xml for 5.3 . I think this wouldn't work.

But need to come up with new model like 5.5 as whole with new 5.5 xsd and then generate corresponding modelinfo.xml. Correct?

Thanks
Sumeet

**Comment by brynrhodes** [comment]
I would actually suggest using a different name, like `QDMPlus` or something that indicates that you're using a model that is an extension of common QDM. So in the CQL it would look like:

using QDMPlus version '1.0'

Otherwise, there would be confusion about the model when you tried to use the CQL in an environment that just used the standard QDM.

Does that make sense?
