### ISSUE TITLE
Product(List<System.Quantity>) not supported

### ISSUE THREAD

**Issue by jbradl11** [cqframework/clinical_quality_language#363]
The CQL example: 

define QuantityProduct: Product({ 1.0 ‘mg’, 2.0 ‘mg’, 3.0 ‘mg’, 4.0 ‘mg’ })

Creates an error  when running it through the CQL-to-ELM translator:

<data.coffee#Product[5:25, 5:75]> Could not resolve call to operator Product with signature (list<System.Quantity>).

**Comment by brynrhodes** [comment]
Addressed in 1.3.7-SNAPSHOT
