### ISSUE TITLE
Question regarding resolution when function argument identifier matches definition identifier

### ISSUE THREAD

**Issue by jackcmeyer** [cqframework/clinical_quality_language#364]
```
library testlibrary version '1.0.000'

using QDM version '5.4'

define "samename":
	true

define function "test"(samename Integer):
	samename
```

Given this library. The function `test` returns an `Integer` and the definition `samename` returns a `Boolean`. This implies that `samename` in the function body is using the argument to resolve rather than the definition. 

```
library testlibrary version '1.0.000'

using QDM version '5.4'

define "samename":
	true

define function "test"(samename Integer):
	"samename"
```

When using the quoted version, the return types are the same as the previous library. Which again implies that the argument is being used rather than the expression. 

Is it possible to reference the definition from the function body if there is an argument with the same name? Is it true to say that any identifier that is local ONLY to the function will be the result of the resolution instead of the definition?

**Comment by brynrhodes** [comment]
CQL uses scope hiding for identifiers, so no, there is no way to reference an expression from within a function body if the expression has the same identifier as a function argument.

**Comment by brynrhodes** [comment]
Closing as resolved, please feel free to reopen if you have further questions on this.
