### ISSUE TITLE
Issue with ConvertsTo* Functions

### ISSUE THREAD

**Issue by jackcmeyer** [cqframework/clinical_quality_language#367]
There appears to be an issue when using `ConvertsTo*` Functions

For example: 

```
define "test":
  true and ConvertsToInteger('1')
```
or
```
define "test":
  true and ConvertsToString('1')
```
or
```
define "test":
  true and ConvertsToDecimal('1')
```
results in the following error: `Could not determine signature for invocation of operator System.And.`

It appears that the ResultType of the `ConvertsTo*` function is `null`.

This issue is present in CQL to ELM v1.3.9 or newer.

**Comment by brynrhodes** [comment]
Adressed in [1.3.14](https://github.com/cqframework/clinical_quality_language/releases/tag/v1.3.14)
