### ISSUE TITLE
Without filter not functioning correctly with hours between

### ISSUE THREAD

**Issue by jscherer-motivemi** [cqframework/clinical_quality_language#368]
The without filter does now work correctly with an hours between filter parameter. The statement that is failing is as follows:

define ClaimWithQualifiyingPOSWithoutEncounter: ClaimWithQualifyingPOS C without InpatientEncounters E such that hours between C.billablePeriod."start" and E.period."start"  <= 24

The context for this logic is available in the attached doducment:
[mmi_cql-issue_without_filter_not_working.txt](https://github.com/cqframework/clinical_quality_language/files/2444074/mmi_cql-issue_without_filter_not_working.txt)

**Comment by cmoesel** [comment]
Hi @jscherer-motivemi. Is this an issue against one of the execution engines?  If so, which one?

**Comment by jscherer-motivemi** [comment]
Hi @cmoesel. I am not sure that I know. We use the CQL java engine version 1.2 currently. Let me know if you need additional information.

**Comment by cmoesel** [comment]
OK.  In that case I'd recommend you file these against that specific project here:
https://github.com/DBCG/cql_engine

(FYI @brynrhodes)
