### ISSUE TITLE
Distinct operator does not work with resources

### ISSUE THREAD

**Issue by jscherer-motivemi** [cqframework/clinical_quality_language#369]
If you have duplicated resources in a list and apply the distinct operator, the duplicates are not removed.

**Comment by cmoesel** [comment]
Hi @jscherer-motivemi. Is this an issue against one of the execution engines?  If so, which one?

**Comment by jscherer-motivemi** [comment]
Hi @cmoesel. I am not sure that I know. We use the CQL java engine version 1.2 currently. Let me know if you need additional information.

**Comment by cmoesel** [comment]
OK.  In that case I'd recommend you file these against that specific project here:
https://github.com/DBCG/cql_engine

(FYI @brynrhodes)

**Comment by jscherer-motivemi** [comment]
@cmoesel, Thank you, I will do that.
