### ISSUE TITLE
fhir-modelinfo-3.0.0.xml and FHIRHelpers missing function for ReferralRequest.status

### ISSUE THREAD

**Issue by jscherer-motivemi** [cqframework/clinical_quality_language#371]
fhir-modelinfo-3.0.0.xml and FHIRHelpers-3.0.0.cql do not support accessing the value of ReferralRequest.status.

**Comment by brynrhodes** [comment]
I was unable to reproduce this with the latest translator. Can you provide some more details about when you are seeing this issue?
