### ISSUE TITLE
ConvertsTo* expression type

### ISSUE THREAD

**Issue by losborne** [cqframework/clinical_quality_language#372]
`define Converts: ConvertsToBoolean(‘y’)`
 
is translated to a FunctionRef:
```
"expression" : {
    "localId" : "3",
    "name" : "ConvertsToBoolean",
    "type" : "FunctionRef",
    "operand" : [ {
        "localId" : "2",
        "valueType" : "{urn:hl7-org:elm-types:r1}String",
        "value" : "y",
        "type" : "Literal"
    } ]
}
```

Should this be `“type” : “ConvertsToBoolean”` instead?  The FunctionRef is throwing an error because ConvertsToBoolean is not defined in any library.

**Comment by brynrhodes** [comment]
Adressed in [1.3.14](https://github.com/cqframework/clinical_quality_language/releases/tag/v1.3.14)
