### ISSUE TITLE
Today() is an operand of ToDateTime() in cql-to-elm translation

### ISSUE THREAD

**Issue by zefcon** [cqframework/clinical_quality_language#375]
Hi. We've found a discrepancy we believe is an error, but would love your feedback.

In a version sometime more recent than this commit: `commit 94613e88d21dace7df847b0115a86613cb9daf45` we found the ELM produced via `cql-to-elm` does not match the ELM as present in the [eCQM 2019 Downloads](https://ecqi.healthit.gov/eligible-professional-eligible-clinician-ecqms?field_year_value=1).

 To be clear, we haven't confirmed at what commit this discrepancy appears, we just know that it's not present at this hash and manifests by `tag 1.3.10`

# Example
Using `CalendarAgeInYears` from `MATGlobalCommonFunctions` , this is the elm as produced on the above commit and as found in the eCQM download:
```
      <def name="CalendarAgeInYears" context="Patient" accessLevel="Public" xsi:type="FunctionDef">
         <expression name="CalendarAgeInYearsAt" xsi:type="FunctionRef">
            <operand name="BirthDateTime" xsi:type="OperandRef"/>
            <operand xsi:type="Today"/>
         </expression>
         <operand name="BirthDateTime">
            <operandTypeSpecifier name="t:DateTime" xsi:type="NamedTypeSpecifier"/>
         </operand>
      </def>
```

This is the ELM produced on tag `1.3.10`:
```
      <def name="CalendarAgeInYears" context="Patient" accessLevel="Public" xsi:type="FunctionDef">
         <expression name="CalendarAgeInYearsAt" xsi:type="FunctionRef">
            <operand name="BirthDateTime" xsi:type="OperandRef"/>
            <operand xsi:type="ToDateTime">
               <operand xsi:type="Today"/>
            </operand>
         </expression>
         <operand name="BirthDateTime">
            <operandTypeSpecifier name="t:DateTime" xsi:type="NamedTypeSpecifier"/>
         </operand>
      </def>
```

This difference we believe is in error:
```
            <operand xsi:type="ToDateTime">
               <operand xsi:type="Today"/>
            </operand>
```

1. `ToDateTime` is absent in this function of the CQL.
2. This says something like: `ToDateTime(Today())` and the signatures per document `HL7_CQLANG_R1_STU2_2017JUL` are:
```
9.3.8 ToDateTime
Signature:
ToDateTime(argument String) DateTime

9.8.15
Today
Signature:
Today() DateTime
```

## Conclusion
`Today()` should not be an operand of `ToDateTime()`.

Please let me know if we're in error and need to adjust.

Thanks for taking a look!

**Comment by brynrhodes** [comment]
@zefcon, thank you for the report, there is an issue here related to the use of Date versus DateTime with the age calculation functions. Marking as a bug and scheduling for the next maintenance release. Note that the MATGlobalCommonFunctions library retained the CalendarAge calculation functions due to this release. See the related issue [here](https://github.com/esacinc/CQL-Formatting-and-Usage-Wiki/issues/7).

**Comment by brynrhodes** [comment]
Adressed in [1.3.14](https://github.com/cqframework/clinical_quality_language/releases/tag/v1.3.14)
