### ISSUE TITLE
CQL .net source compilation issues

### ISSUE THREAD

**Issue by NeetaRamani** [cqframework/clinical_quality_language#376]
I am trying to compile the dot net source code that I downloaded from the following path "https://github.com/cqframework/clinical_quality_language", but I am getting lots of errors for missing namespaces for CQL project. 

Example:  Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0115	'cqlTranslationVisitor.VisitQuery(cqlParser.QueryContext)': no suitable method found to override	CQL.Translation	C:\Users\neeta_r\Downloads\clinical_quality_language-master\Src\dotnet\CQL.Translation\cqlTranslationVisitor.cs	140	Active

Could you please help with this?

**Comment by cmoesel** [comment]
Hi @Maxsqladmin.  The .NET implementation was never fully realized and has not been updated in the last 3 - 4 years.  There is quite a bit of work needed to bring it up to parity with the Java version.  Please see #344.

@brynrhodes -- unless someone else picks up this work, we may want to consider removing the .NET implementation from this repository or moving it under a `deprecated` or `abandoned` folder.  What do you think?

**Comment by Maxsqladmin** [comment]
So, is there any scope that the .net source would be taken up and completed Or we will have to move with java version?

**Comment by cmoesel** [comment]
I do not believe that the core committer team has any plans to update the .NET implementation.  The issue submitter for #344 expressed some potential interest in working on it (about 3 months ago), but I don't know if they decided to pursue it or not.  From my perspective, I have not seen any additional activity on the .NET code.

**Comment by brynrhodes** [comment]
We would love to see further effort on the .NET implementation. It is something we are trying to get to so that we can support both .NET and Java platforms at parity. This is an area where community input would be welcomed.
