### ISSUE TITLE
Choice-based primaryCodePaths for FHIR STU3

### ISSUE THREAD

**Issue by cmoesel** [cqframework/clinical_quality_language#379]
The model-info for FHIR STU3 has several `primaryCodePath` values that are unresolvable by CQL-to-ELM.  These cause warnings like this to be emitted:
```
Could not resolve code path medicationCodeableConcept for the type of the retrieve FHIR.MedicationRequest.
```
and
```
Could not resolve membership operator for terminology target of the retrieve.
```

This seems to happen when the primaryCodePath refers to a choice.  In the model-info, the `primaryCodePath` uses the full name of the choice (as it would appear in the JSON) rather than the property name as defined in the model-info (e.g., it uses `medicationCodeableConcept` rather than `medication`).

Affected classes:

Class | Current primaryCodePath | Actual property name
--- | --- | ---
DeviceRequest | codeCodeableConcept | code
MedicationDispense | medicationCodeableConcept | medication
MedicationRequest | medicationCodeableConcept | medication
MedicationAdministration | medicationCodeableConcept | medication
MedicationStatement | medicationCodeableConcept | medication
MedicationDispense | medicationCodeableConcept | medication

I think the model-info should be updated to reflect the true property name.  In cases where a different choice is used (e.g., a `Reference`), engines should detect that the value is not a concept and ignore it.

If there is agreement, I can submit a PR with the necessary fixes.

**Comment by brynrhodes** [comment]
@cmoesel, completely agree, these should be corrected.

**Comment by brynrhodes** [comment]
Adressed in [1.3.14](https://github.com/cqframework/clinical_quality_language/releases/tag/v1.3.14)
