### ISSUE TITLE
Hinting of Resources and Fields

### ISSUE THREAD

**Issue by bdrillard** [cqframework/clinical_quality_language#383]
A potentially powerful optimization would be having the CQL-to-ELM compiler hint resources and, more granularly, resource fields referenced by the CQL query. The benefit here would be to expose information supporting programmatic construction of data selection statements that would limit data pulled from the store to only those fields required.

Although this kind of static analysis would be possible in a backend implementation over the compiled ELM, I feel similar logic would be quite at home on the compiler frontend, where the resource & field information could be exposed towards the top of the ELM, somewhere just above the `statements` definition.

An optimization like this could be optional, turned on via a flag, like some of the other compiler optimizations. I feel like it could be greatly valuable when considering current implementations realistically have to pull in full, quite nested resources, where much of the data may not even be referenced by the query, but would still have an impact on the computational resources available in the query runtime (Claims data, for example).

I'm curious if devs here would welcome an optional optimization like this.

If so, there would be some design questions to discuss, e.g. how "deep" or "shallow" across nested structs the should field hinting be? If "deep", should hinting just be for chained `property` calls, or also included `index` calls? A first pass of an optimization like this may be "shallow" just for ease of implementation.

**Comment by brynrhodes** [comment]
Hi @bdrillard, I think this would be a great addition, a sort of summary of the retrieves. It's also some of the same infrastructure that could enable this feature: #79, which would be very useful as well (though it would require some modeling support to identify mustSupport attributes in the first place).

**Comment by brynrhodes** [comment]
Included in 1.5.4-SNAPSHOT (via the ElmDataRequirementsVisitor and the elm-fhir package)
