### ISSUE TITLE
Support for Extensions & Contained Resources

### ISSUE THREAD

**Issue by bdrillard** [cqframework/clinical_quality_language#384]
There are instances where we'd like to model relationships between certain FHIR resources using [Provenance](https://www.hl7.org/fhir/provenance.html) resources, for example, to indicate which Claim a Condition or Procedure may have originated from. 

It can sometimes be the case that such resources are directly "[contained](https://www.hl7.org/fhir/references.html#contained)" within the referring FHIR Resource, e.g. a Procedure directly "contains" a Provenance resource that refers to a Claim.

The CQL spec has no specific discussion of Contained resources (we might not expect it to, since it's quite a FHIR-specific thing), but since all FHIR resources that inherit from [DomainResource](https://www.hl7.org/fhir/stu3/domainresource.html#DomainResource) have a `contained` field (which also exists in the [fhir-modelinfo](https://github.com/cqframework/clinical_quality_language/blob/v1.3.10/Src/java/quick/src/main/resources/org/hl7/fhir/fhir-modelinfo-3.0.0.xml#L3498), using the current v1.3.10 CQL-to-ELM compiler, it should be possible to do something like

```
library Query version '1'
using FHIR version '3.0.0'
include FHIRHelpers version '3.0.0' called FHIRHelpers

context Patient

define GetProvenance: (First([Procedure]).contained) P where P is FHIR.Provenance return P as FHIR.Provenance
```

We'd expect `GetProvenance` to have a type List<FHIR.Provenance> given the return cast.

This query fails to compile, giving a type error:

```
Translation failed due to errors:
Error:[7:90, 7:114] Expression of type 'FHIR.ResourceContainer' cannot be cast as a value of type 'FHIR.Provenance'.
```

The CQL spec implies other forms of "down-cast" are viable in its section on [Casting](https://cql.hl7.org/03-developersguide.html#casting) (e.g. Procedure to ImageProcedure), so I'm not sure if this error in casting from FHIR.ResourceContainer to FHIR.Provenance is expected behavior or a bug.

I think similar questions would arise with how CQL handles FHIR Extensions, but I haven't dug into that as much.

**Comment by brynrhodes** [comment]
Hi @bdrillard, looking at this it should be possible, but contained element is actually modeled in the FHIR XML Schema as a "ResourceContainer", which has elements for each of the possible resource types,
so that structure will be reflected directly in the FHIR ModelInfo:

https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/quick/src/main/resources/org/hl7/fhir/fhir-modelinfo-3.0.0.xml#L5529

So this should work to access the contained resources:

    define GetProvenance: 
      (First([Procedure]).contained) C 
        where C.Provenance is not null 
        return C.Provenance

And yes, extensions work similarly, there is an extension element, based on the FHIR XML schema, so you can access those as well. We have used extensions successfully, but we have not yet tried accessing contained elements.

**Comment by bdrillard** [comment]
Hi @brynrhodes, thanks for this guidance. Do you think you could tell me which version of the CQFramework project supports this access pattern?

**Comment by brynrhodes** [comment]
Hi @bdrillard , apologies for the delay, I didn't see this question. I just verified that the proposed query I posted above works in the latest 1.3 translator against FHIR STU3. Are you seeing different behavior?

**Comment by bdrillard** [comment]
I can verify this access pattern works for the latest translator you mention, @brynrhodes! Gonna close this question.
