### ISSUE TITLE
Issue with parameter error reporting in a specific scenario

### ISSUE THREAD

**Issue by jackcmeyer** [cqframework/clinical_quality_language#385]
Given the following parameter: 

`parameter "test" Interval<Date Time>` 

There is no information inside of the `VersionedIdentifier` called `library` in the `TrackBack` called `locator` for this `CqlSyntaxException`. 

The `TrackBack` does, however, have line number information.

**Comment by brynrhodes** [comment]
Hi @jackcmeyer , thank you for the report. If I understand correctly, you're saying the exception does not have sufficient error information to be able to display the error appropriately tied to the library it originated in. I'll take a look and get a fix, but unless this is a critical issue, I'm going to schedule it for the 1.4 ballot support release.

**Comment by brynrhodes** [comment]
Addressed by #487

**Comment by brynrhodes** [comment]
Addressed in 1.4.9 release
