### ISSUE TITLE
FHIRHelpers and ToString for FHIR.code

### ISSUE THREAD

**Issue by bdrillard** [cqframework/clinical_quality_language#399]
FHIRHelpers version 3.0.0 previously included a [`ToString`](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/quick/src/main/resources/org/hl7/fhir/FHIRHelpers-3.0.0.cql#L181) implementation for FHIR.code, which just extracted the code value of the Code as a String. 

The latest [FHIRHelpers](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/quick/src/main/resources/org/hl7/fhir/FHIRHelpers-3.0.1.cql) for R3, 3.0.1, no longer includes that function, so

```
library Query version '1'
using FHIR version '3.0.1'
include FHIRHelpers version '3.0.1' called FHIRHelpers

context Patient

define Encounters: [Encounter] E where E.priority.coding[0].code = 'value'
```

will no longer infer the use of ToString against the code. The original behavior can be achieved via

```
library Query version '1'
using FHIR version '3.0.1'
include FHIRHelpers version '3.0.1' called FHIRHelpers

context Patient

[Encounter] E where E.priority.coding[0].code.value = 'value'
```

I suppose I'm wondering what the rationale was for removing `ToString`, because it is _useful_, but the uplift isn't all that challenging. I can understand extracting just the code, without the system, to compare against an arbitrary string, could be considered semantically odd behavior. Although, arguably we do something like that when we apply `ToString` against types like FHIR AdministrativeGender that appear as codes in the HL7 doc, but are slightly different (enumerations vs. codes). We can do a comparison like,

```
Patient.gender = 'Female'
```

and `ToString` will be dispatched against the enum type.

The one thing I do want to note is that the current behavior does have one surprising aspect, i.e. both the code and the String being compared against now get promoted to lists for the equals comparison via the `ToList` operator:

```
      <def name="Encounters" context="Patient" accessLevel="Public">
         <resultTypeSpecifier xsi:type="ListTypeSpecifier">
            <elementType name="fhir:Encounter" xsi:type="NamedTypeSpecifier"/>
         </resultTypeSpecifier>
         <expression xsi:type="Query">
            <resultTypeSpecifier xsi:type="ListTypeSpecifier">
               <elementType name="fhir:Encounter" xsi:type="NamedTypeSpecifier"/>
            </resultTypeSpecifier>
            <source alias="E">
               <resultTypeSpecifier xsi:type="ListTypeSpecifier">
                  <elementType name="fhir:Encounter" xsi:type="NamedTypeSpecifier"/>
               </resultTypeSpecifier>
               <expression dataType="fhir:Encounter" xsi:type="Retrieve">
                  <resultTypeSpecifier xsi:type="ListTypeSpecifier">
                     <elementType name="fhir:Encounter" xsi:type="NamedTypeSpecifier"/>
                  </resultTypeSpecifier>
               </expression>
            </source>
            <where resultTypeName="t:Boolean" xsi:type="Equal">
               <operand xsi:type="ToList">
                  <operand resultTypeName="fhir:code" path="code" xsi:type="Property">
                     <source resultTypeName="fhir:Coding" xsi:type="Indexer">
                        <operand path="coding" xsi:type="Property">
                           <resultTypeSpecifier xsi:type="ListTypeSpecifier">
                              <elementType name="fhir:Coding" xsi:type="NamedTypeSpecifier"/>
                           </resultTypeSpecifier>
                           <source resultTypeName="fhir:CodeableConcept" path="priority" scope="E" xsi:type="Property"/>
                        </operand>
                        <operand resultTypeName="t:Integer" valueType="t:Integer" value="0" xsi:type="Literal"/>
                     </source>
                  </operand>
               </operand>
               <operand xsi:type="ToList">
                  <operand resultTypeName="t:String" valueType="t:String" value="value" xsi:type="Literal"/>
               </operand>
            </where>
         </expression>
      </def>
```

Is this expected behavior?

**Comment by brynrhodes** [comment]
Thank you for the detailed report and reproduction, this is definitely an oversight in the 3.0.1 model. We are working on a new toolchain to produce modelinfo from FHIR Profiles and the only difference between 3.0.0 and 3.0.1 is the toolchain that was used to produce it. It looks like all the FHIRHelpers for string-valued FHIR Primitives were missed, so I've added them in here, and that should address the issue.

As far as the list promotion behavior, that is an undesirable byproduct of the list promotion behavior, since it can't find a way to do the equality comparison directly, the translator is looking to see if it can find a signature by promoting the arguments to lists, and it ends up finding list equality. There is a disableListPromotion flag to disable that behavior, and the QDM-based artifact authors typically run with that setting.

**Comment by brynrhodes** [comment]
Adressed in [1.3.14](https://github.com/cqframework/clinical_quality_language/releases/tag/v1.3.14)
