### ISSUE TITLE
cqframework groupid/namespace doesn't correspond to a working web domain

### ISSUE THREAD

**Issue by duncand** [cqframework/clinical_quality_language#421]
On https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/cql-to-elm/OVERVIEW.md we see you use the groupid info.cqframework however if I go to cqframework.info in my web browser it brings up some Japanese-language page that doesn't seem related to the project.

Did you lose control of your groupid domain or should org.cqframework be used in the above document?

For that matter, trying to visit cqframework.org doesn't bring up a server at all.

**Comment by brynrhodes** [comment]
Thank you for bringing this to our attention. We'll look into it.
