### ISSUE TITLE
Issue with annotations in the 1.4.4-SNAPSHOT build

### ISSUE THREAD

**Issue by jackcmeyer** [cqframework/clinical_quality_language#432]
When executing any CQL library with the `--annotations` flag, the translator always throws a `CqlSemanticException` with the following message: `Error:[1:1, 31:58] Child chunk cannot be added because it is not contained within the parent chunk.`. 

The same library passes when the `--annotations` flag is not used.

**Comment by brynrhodes** [comment]
I have confirmed the issue and am working on a root cause now.

**Comment by brynrhodes** [comment]
Included in 1.4.5-SNAPSHOT release
