### ISSUE TITLE
Issue with using end of in an interval operator phrase in 1.4.5-SNAPSHOT

### ISSUE THREAD

**Issue by jackcmeyer** [cqframework/clinical_quality_language#434]
using the following CQL:

```
define "test":
  ["Encounter, Performed"] e
    where e.relevantPeriod 3 years or less before 
    end of "Measurement Period"
```

I am receiving the error: `Error:[17:9, 17:10] Could not resolve identifier of in the current library.`. 

This statement has successfully translated in prior versions of the translator. 

It appears that the parser is not recognizing the time boundary operator on the right hand side of the interval operator phrase expression. Here is the parse tree: 

![image](https://user-images.githubusercontent.com/18731800/59875705-108b7400-9367-11e9-8e93-a10b44ac9c21.png)

**Comment by brynrhodes** [comment]
Confirmed the issue, working on a root cause now.
