### ISSUE TITLE
Signature passed to cql2elm translator is null

### ISSUE THREAD

**Issue by jscherer-motivemi** [cqframework/clinical_quality_language#440]
We are trying to integrated the cql2elm translator v1.3.16 with the CQL Engine v1.3 using FHIR 3.0.0 data model. When we translate any CQL-FHIR expression we get the following error:

operandTypes in signatures cannot be null

It appears that the issue is with the Date signature, which is coming back null from the system model. If others have seen this issue, we would appreciate assistance with resolving it.

**Comment by brynrhodes** [comment]
We are unable to reproduce this issue in the translator directly, is there an engine issue submitted for this?

**Comment by brynrhodes** [comment]
Is this issue still occurring? It feels like a classpath issue where the translator is not able to load the correct resources for the modelinfo.
