### ISSUE TITLE
Casting for Choice Types

### ISSUE THREAD

**Issue by andy-schriever** [cqframework/clinical_quality_language#441]
The 'result' attribute on many QDM data types is a Choice Type in QDM 5.4.  In a query, when the result attribute is compared to a number, the CQL-to-ELM compiler generates an explicit cast, depending upon the detected type of the comparand.  For example, when the CQL code reads... 

`where PHQ.result > 9`

...the 'PHQ.result' value will be cast (with 'As') to an Integer in the generated ELM.  However, if the CQL code reads...

`where PHQ.result > 9.0`

...PHQ.result will be cast to Decimal.

When measure authors write code in the first style, problems arise if PHQ.result happens to be presented by the data provider as a Decimal, since Decimals can't be cast to Integers.  

As a rule, it would seem wise to select the most general option from the list of choices when generating a cast.  In this case that would mean generating a cast to Decimal regardless of whether the result is compared to 9 or to 9.0.

**Comment by brynrhodes** [comment]
We're considering adding "choice-based operator resolution" to address this more broadly, see #564 for details
