### ISSUE TITLE
In CqlTranslator.java file i did't get org.hl7.cql_annotations.r1 and org.hl7.elm.r1 Packages in IntelliJ 

### ISSUE THREAD

**Issue by rajeshnalluri** [cqframework/clinical_quality_language#46]
Hi,
I am tring to translate cql to elm format i was setup the cqframework,in my intelliJ IDEA , i am not able to import following package classes..
org.hl7.cql_annotations.r1 and org.hl7.elm.r1 how to create the above packages please help me..

thank you,
Rajesh.

**Comment by cmoesel** [comment]
Hi Rajesh,

Those packages contain generated code.  The best way to ensure you have everything you need is just to do a full build from the commandline.

```
$ cd /your/path/to/clinical-quality-language/Src/java
$ ./gradlew build
```

**Comment by rajeshnalluri** [comment]
Hi cmoesel,
thank you very much for your reply i will run the above commands.
Regards,
Rajesh.

**Comment by rajeshnalluri** [comment]
Hi Chris Moesel,

I am exploring on genarating drools rules dynamically based on ELM(XML) file is there any predefined tools or sample code available in github.

Regards,
Rajesh.

**Comment by cmoesel** [comment]
I believe that others have done some work with CQL/ELM and drools, but I was not involved in those efforts.  I do not know if any of them were open source, or if they were all proprietary.  @brynrhodes might know.

**Comment by brynrhodes** [comment]
There was a pilot that produced an ELM to Drools translation, but it was not open source.
