### ISSUE TITLE
Address illegal reflective operation

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/clinical_quality_language#460]
> Task :tools:xsd-to-modelinfo:test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.ws.commons.schema.utils.DOMUtil (file:/C:/Users/Bryn/.gradle/caches/modules-2/files-2.1/org.apache.ws.xmlschema/xmlschema-core/2.2.0/a229830c66670359fd3bd69e62519c533ad894ec/xmlschema-core-2.2.0.jar) to method com.sun.org.apache.xerces.internal.dom.CoreDocumentImpl.getInputEncoding()
WARNING: Please consider reporting this to the maintainers of org.apache.ws.commons.schema.utils.DOMUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by JPercival** [comment]
Resolved on master
