### ISSUE TITLE
CQL to ELM Target Library not populated in Annotation Error

### ISSUE THREAD

**Issue by ddecouteau** [cqframework/clinical_quality_language#487]
The target library name and version are not being serialized and returned in response during cql-to-elm validation and conversion.

"library": {
    "annotation": [
      {
        "startLine": 42,
        "startChar": 33,
        "endLine": 42,
        "endChar": 38,
        "message": "Could not resolve call to operator Before with signature (FHIR.dateTime,FHIR.Period).",
        "errorType": "semantic",
        "errorSeverity": "error",
        "type": "CqlToElmError"
      },
      {
        "startLine": 41,
        "startChar": 17,
        "endLine": 42,
        "endChar": 57,
        "message": "Could not determine signature for invocation of operator System.And.",
        "errorType": "semantic",
        "errorSeverity": "error",
        "type": "CqlToElmError"
      },

**Comment by brynrhodes** [comment]
Addressed in 1.4.9-SNAPSHOT

**Comment by brynrhodes** [comment]
Ooops, only meant to mark it as addressed.

**Comment by brynrhodes** [comment]
Addressed in 1.4.9 release
