### ISSUE TITLE
CQL-to-ELM :  Translation failed due to errors for = null check

### ISSUE THREAD

**Issue by karthisuku** [cqframework/clinical_quality_language#496]
_cql-to-elm_ fails for the following cql from _Equal_ spec [1]

`define NullEqualIsNull: null = null`

**To Reproduce the error:**

Run the following command, where the  _inputfile.cql_ contains the above cql

`bash cql-to-elm -input inputfile.cql -output output.xml`

**Error**
```
Translation failed due to errors:
Error:[1:19, 1:29] Call to operator Equal(System.Any,System.Any) is ambiguous with: 
  - Equal(System.Decimal,System.Decimal)
  - Equal(System.Boolean,System.Boolean)
  - Equal(list<System.Any>,list<System.Any>)
  - Equal(System.Integer,System.Integer)
  - Equal(System.DateTime,System.DateTime)
  - Equal(System.Ratio,System.Ratio)
  - Equal(System.Date,System.Date)
  - Equal(System.String,System.String)
  - Equal(System.Quantity,System.Quantity)
  - Equal(System.Time,System.Time)
```
**Environment used**
cql-to-elm version used  1.3.15

[1] https://cql.hl7.org/09-b-cqlreference.html#equal

**Comment by brynrhodes** [comment]
Thank you for the report, this is a known issue, see #435. The workaround is to cast explicitly, but there is a challenge with the operator resolver in that if a signature for (Any, Any) gets instantiated on the equal or equivalent operators, it ends up incorrectly overriding the more specific signatures. That's an issue we are working on addressing, but since it has a workaround it hasn't been prioritized.

**Comment by karthisuku** [comment]
> Thank you for the report, this is a known issue, see #435. The workaround is to cast explicitly, but there is a challenge with the operator resolver in that if a signature for (Any, Any) gets instantiated on the equal or equivalent operators, it ends up incorrectly overriding the more specific signatures. That's an issue we are working on addressing, but since it has a workaround it hasn't been prioritized.

Thanks @brynrhodes for the details.

**Comment by brynrhodes** [comment]
Closing as a duplicate
