### ISSUE TITLE
CQL-to-ELM Translator - Internal translator error

### ISSUE THREAD

**Issue by sanumula** [cqframework/clinical_quality_language#500]
When the argument for the collapse operator is null, the CQL Translator is throwing an error.

**CQL:**
`define CollapseIsNull: collapse null`

**Error:**
Translation failed due to errors:
Error:[1:24, 1:36] Internal translator error.

CQL Spec: https://cql.hl7.org/09-b-cqlreference.html#collapse

**Comment by brynrhodes** [comment]
Thank you for the report @sanumula

**Comment by brynrhodes** [comment]
Addressed in 1.4.9 release
