### ISSUE TITLE
CQL-to-ELM Translator unresponsive

### ISSUE THREAD

**Issue by ChristopherTJaramillo** [cqframework/clinical_quality_language#510]
With certain large libraries, the translator becomes unresponsive.

**Comment by brynrhodes** [comment]
Thank you for the report, I have reproduced this problem and am working on a root cause now.

**Comment by brynrhodes** [comment]
After investigation, this is related to a known issue with the version of Antlr. See issue #343 for a description of the issue.

**Comment by brynrhodes** [comment]
Closing as a duplicate of #343
