### ISSUE TITLE
Human readable generation issue in cql-to-elm v1.4.6

### ISSUE THREAD

**Issue by adongare** [cqframework/clinical_quality_language#524]
Hello,

We are using cql-to-elm v1.4.6 in Measure Authoring Tool. We are facing an issue where one of the cql definitions is missing from Human Readable(measure name is `Elective Delivery` CMS113). Because of some reason cql-to-elm translator thinks that the definition is not being used however the definition is used in denominator. CQL definitions: 
```
define "Denominator":
  "Delivery Encounter Near Term"

define "Delivery Encounter Near Term":
  "Delivery Encounter With Calculated Gestational Age"
    union "Delivery Encounter With Estimated Gestational Age Assessment"
```
The missing definition from Human Readable is` Delivery Encounter With Calculated Gestational Age` 

To filter out all the used definitions, we use following code:

```
// prepare cqlFilter
MATCQLFilter cqlFilter = new MATCQLFilter(parentLibraryString, childrenLibraries , parentExpressions, translator, translatedLibraries);
// call filter
cqlFilter.filter();
// get used definitions
cqlFilter.getUsedDefinitions() // "Delivery Encounter With Calculated Gestational Age" not being returned in list
```
When I change denominator to use this definition directly as:
```
define "Denominator":
  "Delivery Encounter With Calculated Gestational Age"
    union "Delivery Encounter With Estimated Gestational Age Assessment"
```

`cqlFilter.getUsedDefinitions()` returns the definition correctly.  

Original ticket that was created by our user is: https://oncprojectracking.healthit.gov/support/browse/BONNIEMAT-646
I can also provide original cql lib if needed.

Thank you!

**Comment by brynrhodes** [comment]
Hi @adongare , my guess is that something in the MATCqlFilter class is not traversing the ELM tree, is there a way I can see what's happening in that code?

**Comment by adongare** [comment]
Thank you @brynrhodes! I can walk you through the code. Please let me know when you get some time. I can setup meeting invite.

**Comment by adongare** [comment]
Hi @brynrhodes, sorry to bother you again, just followup to our earlier conversation. Please let me know your thoughts on this. Thank you!

**Comment by yanyanhu2** [comment]
Hi @adongare @brynrhodes, Just wanted to follow up on this issue. The Joint Commission is going to publish our eCQMs for 2020AU soon, including CMS113 and CMS334. We hope this issue could be resolved by MAT tool completely so that we can have issue-free eCQMs published.  Thank you both!

**Comment by brynrhodes** [comment]
@adongare , apologies for the delay here, I'll reach out directly to set up a time to chat.

**Comment by mparenzan** [comment]
Can I get an update on this issue?   We would like to publish this measure next week.  Thank you.

**Comment by adongare** [comment]
Hi @mparenzan, we met with Bryn and he helped us to figure out the issue. Issue is not in this code. It's in another MAT dependency which uses this code. MAT team is working on it. We'll provide you the status on Jira ticket. Thanks!

**Comment by mparenzan** [comment]
Do you have an EDC?

**Comment by adongare** [comment]
This was an issue in MAT wrapper around CQLtoELM translator and not the original CQLtoELM translator. Thank you so much @brynrhodes for your help on this. I'm closing this issue.
