### ISSUE TITLE
CQL to ELM translator, removes certain expressions when date range optimization is enabled

### ISSUE THREAD

**Issue by amarvakul** [cqframework/clinical_quality_language#544]
With the optimization hints enhancements from [1], the translator produces "dateProperty" and "dateRange" hints but it removes the other parts of the ELM which we rely on for functional correctness.

Example CQL
`define "Filtered Claims": [Claim] C where C.billablePeriod during "Default Claim Period"`

ELM generated with DateRangeOptimization turned ON

> <def name="Filtered Claims" context="Patient" accessLevel="Public">
         <resultTypeSpecifier xsi:type="ListTypeSpecifier">
            <elementType name="fhir:Claim" xsi:type="NamedTypeSpecifier"/>
         </resultTypeSpecifier>
         <expression xsi:type="Query">
            <resultTypeSpecifier xsi:type="ListTypeSpecifier">
               <elementType name="fhir:Claim" xsi:type="NamedTypeSpecifier"/>
            </resultTypeSpecifier>
            <source alias="C">
               <resultTypeSpecifier xsi:type="ListTypeSpecifier">
                  <elementType name="fhir:Claim" xsi:type="NamedTypeSpecifier"/>
               </resultTypeSpecifier>
               <expression dataType="fhir:Claim" dateProperty="billablePeriod" xsi:type="Retrieve">
                  <resultTypeSpecifier xsi:type="ListTypeSpecifier">
                     <elementType name="fhir:Claim" xsi:type="NamedTypeSpecifier"/>
                  </resultTypeSpecifier>
                  <dateRange name="Default Claim Period" xsi:type="ExpressionRef">
                     <resultTypeSpecifier xsi:type="IntervalTypeSpecifier">
                        <pointType name="t:DateTime" xsi:type="NamedTypeSpecifier"/>
                     </resultTypeSpecifier>
                  </dateRange>
               </expression>
            </source>
         </expression>
</def>

ELM generated with DateRangeOptimization turned OFF

> <def name="Filtered Claims" context="Patient" accessLevel="Public">
         <resultTypeSpecifier xsi:type="ListTypeSpecifier">
            <elementType name="fhir:Claim" xsi:type="NamedTypeSpecifier"/>
         </resultTypeSpecifier>
         <expression xsi:type="Query">
            <resultTypeSpecifier xsi:type="ListTypeSpecifier">
               <elementType name="fhir:Claim" xsi:type="NamedTypeSpecifier"/>
            </resultTypeSpecifier>
            <source alias="C">
               <resultTypeSpecifier xsi:type="ListTypeSpecifier">
                  <elementType name="fhir:Claim" xsi:type="NamedTypeSpecifier"/>
               </resultTypeSpecifier>
               <expression dataType="fhir:Claim" xsi:type="Retrieve">
                  <resultTypeSpecifier xsi:type="ListTypeSpecifier">
                     <elementType name="fhir:Claim" xsi:type="NamedTypeSpecifier"/>
                  </resultTypeSpecifier>
               </expression>
            </source>
            <where resultTypeName="t:Boolean" xsi:type="IncludedIn">
               <signature xsi:type="IntervalTypeSpecifier">
                  <pointType name="t:DateTime" xsi:type="NamedTypeSpecifier"/>
               </signature>
               <signature xsi:type="IntervalTypeSpecifier">
                  <pointType name="t:DateTime" xsi:type="NamedTypeSpecifier"/>
               </signature>
               <operand name="ToInterval" libraryName="FHIRHelpers" xsi:type="FunctionRef">
                  <signature name="fhir:Period" xsi:type="NamedTypeSpecifier"/>
                  <operand resultTypeName="fhir:Period" path="billablePeriod" scope="C" xsi:type="Property"/>
               </operand>
               <operand name="Default Claim Period" xsi:type="ExpressionRef">
                  <resultTypeSpecifier xsi:type="IntervalTypeSpecifier">
                     <pointType name="t:DateTime" xsi:type="NamedTypeSpecifier"/>
                  </resultTypeSpecifier>
               </operand>
            </where>
         </expression>
      </def>

Expectations : Preserve the original ELM structure that includes "where" (really all original ELM content) expression and also add "dateProperty"/"dateRange" information.

[1] https://github.com/cqframework/clinical_quality_language/issues/311

**Comment by brynrhodes** [comment]
This is addressed by the new DataRequirementsProcessor, included in the 1.5.4 release, in that the DataRequirements analysis does not remove the expressions from the ELM, it only reports them to support query planning.
