### ISSUE TITLE
AdverseEvent::primaryCodePath points to obsolete "type" field in fhir-modelinfo xml

### ISSUE THREAD

**Issue by serhii-ilin** [cqframework/clinical_quality_language#549]
There is probably an error in the model-info XML file. 

AdverseEvent::primaryCodePath points to an obsolete "type" field.  There is no "type" field in AdverseEvent class, but there is an "event" field instead.

Could you please take a look and correct the issue?

**Comment by JSRankins** [comment]
@brynrhodes , there appear to be some similar issues with other non-existent primaryCode paths:

- category for DetectedIssue (should this be code?)
- device.code for DeviceUseStatement (should this be device?)
- measure.topic for MeasureReport (should this be measure?)

These are all in FHIR Model Info file for FHIR 4.0.1 but not present within the respective resources.

**Comment by brynrhodes** [comment]
Included in release 1.5.1
