### ISSUE TITLE
CQL to ELM translator - annotations of function signatures can generate invalid XML

### ISSUE THREAD

**Issue by lscott15** [cqframework/clinical_quality_language#555]
Annotations generated for function definitions that use generic types (Interval, List) don't escape ">" properly, leading to invalid XML.

For example:

```
library LAS_Invalid version '1.0'

using QDM version '5.5'
context Patient

define function "MyFunction"(range Interval<Date>):
  duration in days of range
```

Generates the XML (notice how "<" becomes "&lt" but ">" is left as is):
```
<annotation xsi:type="a:Annotation">
            <a:s r="6">
               <a:s>define function &quot;MyFunction&quot;(range </a:s>
               <a:s r="3">
                  <a:s>Interval&lt;</a:s>
                  <a:s r="2">
                     <a:s>Date</a:s>
                  </a:s>
                  <a:s>></a:s>
               </a:s>
               <a:s>):&#xd;
  </a:s>
               <a:s r="5">
                  <a:s r="5">
                     <a:s>duration in days of </a:s>
                     <a:s r="4">
                        <a:s>range</a:s>
                     </a:s>
                  </a:s>
               </a:s>
            </a:s>
         </annotation>
```

**Comment by brynrhodes** [comment]
We use a third party library to do the encoding, and we have researched this issue before in another context, and per specifications, the greater than symbol is not required to be encoded (since it is not a beginning token in XML). There are some encoders that do, and some that don't, but we don't have any control over that. Is this causing issues in your environment?

**Comment by lscott15** [comment]
Ah, I didn't realize the XML spec allowed that. I'll follow up internally to look at removing the ">" escaping requirement in our XML deserializer. Thanks!
