### ISSUE TITLE
Interval "except" produces exclusive/open endpoints

### ISSUE THREAD

**Issue by matthewtiller** [cqframework/clinical_quality_language#560]
`define "test": Interval(-4, 6) except Interval(7, 12) //calculates to Interval(-3, 5)`

As shown in the above CQL, when "except" is used on intervals that do not overlap, the calculated interval will carry through any exclusive endpoints, but the endpoint values are calculated as if the endpoints are inclusive.

**Comment by brynrhodes** [comment]
This is actually an engine bug, so I've reported it [there](https://github.com/DBCG/cql_engine/issues/403)
