### ISSUE TITLE
Interval "expand" produces invalid intervals

### ISSUE THREAD

**Issue by matthewtiller** [cqframework/clinical_quality_language#561]
`define "test": expand {Interval[@2020-01-01, @2020-01-08]} per day`

The above CQL calculates:
`[Interval[2020-01-01, 2020-01-01), Interval[2020-01-02, 2020-01-02) [...]`

Those intervals are invalid, both including and excluding a particular day. If the "expand" operator uses the "except" operator, this issue may be linked to issue #560

**Comment by matthewtiller** [comment]
This same behavior is confirmed for integer intervals.
`define "test": expand {Interval[4,6]} //results in Interval[4, 4), Interval[5, 5), Interval[6, 6)]`

**Comment by brynrhodes** [comment]
This is an engine issue, so I've reported it [there](https://github.com/DBCG/cql_engine/issues/404)
