### ISSUE TITLE
Inconsistency in primaryCodePath when Choice Types Involved

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#566]
Currently, DeviceRequest in FHIR Model Info file 4.0.1 has primaryCodePath as codeCodeableConcept. 

`
<ns4:typeInfo xsi:type="ns4:ClassInfo" namespace="FHIR" name="DeviceRequest" identifier="http://hl7.org/fhir/StructureDefinition/DeviceRequest" label="DeviceRequest" retrievable="true" primaryCodePath="codeCodeableConcept" baseType="FHIR.DomainResource">
`

Although the codeCodeableConcept attribute does not exist in the DeviceRequest resource, the flavor of it does, since CodeableConcept is part of the applicable choice type. 

![image](https://user-images.githubusercontent.com/8303773/92970867-0ad6ee00-f445-11ea-9f46-26fb37094aee.png)

We are not certain if (1) the use of codeCodeableConcept is an error or (2) a way of setting which type should be used for the primaryCodePath for DeviceRequest. If the latter, then we are wondering why the other primary code paths that are choice typed do not set the type that should be used within the related choice type. One example of this would be GuidanceResponse, which has a primaryCodePath of module.

`
<ns4:typeInfo xsi:type="ns4:ClassInfo" namespace="FHIR" name="GuidanceResponse" identifier="http://hl7.org/fhir/StructureDefinition/GuidanceResponse" label="GuidanceResponse" retrievable="true" primaryCodePath="module" baseType="FHIR.DomainResource">
`

The attribute module has a few different choices available - among them, moduleCodableConcept. There are other primarycodePath attributes that do the same thing. If possible, we would like to request that the primaryCodePath type be set when the primaryCodePath corresponds to a choice type. Thoughts?

**Comment by brynrhodes** [comment]
Agreed, the code path should be in terms of the attributes of the model, this is incorrect and should be fixed.

**Comment by brynrhodes** [comment]
In addition to this, updates for other missing or incorrect primary code paths should be applied:

DeviceRequest -> code
DetectedIssue -> code
BodyStructure -> location
PractitionerRole -> code
RelatedPerson -> relationship
AdverseEvent -> event
Location -> type

See https://github.com/cqframework/cqf-tooling/issues/160 for where this was applied to generation tooling.

**Comment by brynrhodes** [comment]
Included in 1.5.1 Release
