### ISSUE TITLE
Incorrect translation of Time(x,x,x,x,x) operator

### ISSUE THREAD

**Issue by c-schuler** [cqframework/clinical_quality_language#57]
The cql-to-elm translator is not recognizing the Time(x,x,x,x,x) operator properly. 

For example: 
define TimeTest: Time(23, 59, 59, 999)
This expression should result in a Time object populated with the corresponding hour, minute, second, and millisecond values, but it is not. This is causing problems with implementation as the Time(x,x,x,x,x) operator is being evaluated as a function, which leads to errors as the corresponding evaluator never gets called.

*I am using the @Txx:xx:xx.xxxZ Time format as a workaround for now.

**Comment by brynrhodes** [comment]
This issue has been corrected and tests added to verify it on both the master and v12 branches.
