### ISSUE TITLE
Fix Wrong Parsing of Decimals under Non-English Locales

### ISSUE THREAD

**Issue by alexanderkiel** [cqframework/clinical_quality_language#579]
Parsing of decimals like `1.2` truncates the decimal digits under German locale and returns the BigDecimal `1`. The parsing [code](https://github.com/cqframework/clinical_quality_language/blob/0fa511996c760d8b754357f81c8abb4d498cf4a1/Src/java/cql-to-elm/src/main/java/org/cqframework/cql/cql2elm/Cql2ElmVisitor.java#L1343) uses `DecimalFormat`, which is locale dependent. 

I would propose to just use the `BigDecimal` constructor to parse decimals. Should I file an PR?

**Comment by brynrhodes** [comment]
@alexanderkiel , yes please, would definitely welcome a PR on that, and agree, that behavior is unintentional and incorrect.

**Comment by brynrhodes** [comment]
Addressed in the 1.5.2 release
