### ISSUE TITLE
USCore modle info missing target, targetUrl, targetVersion in latest commit

### ISSUE THREAD

**Issue by msargentibm** [cqframework/clinical_quality_language#584]
The USCore model info has dropped some information in the latest commit. At the metadata level, `targetUrl` and `targetVersion` are no longer present in the model info. https://github.com/cqframework/clinical_quality_language/commit/0fa511996c760d8b754357f81c8abb4d498cf4a1#diff-2866531ca569a1f18a985d1ded2cf46f1517557115d77132fcbdd14df9c4d528R2.

Likewise, some of the resources dropped their `target` attribute in this commit. https://github.com/cqframework/clinical_quality_language/commit/0fa511996c760d8b754357f81c8abb4d498cf4a1#diff-2866531ca569a1f18a985d1ded2cf46f1517557115d77132fcbdd14df9c4d528R1483. The attribute previously contained the mapping information needed to identify the base FHIR type (ex: `target="Patient"` for `PatientProfile`).

It seems that without these fields, CQL to ELM translation is producing  an ELM file that will not work with the CQL engine. Example CQL:
```
library "Test" version '1.0.0'
using "USCore" version '3.1.0'

context Patient
```

Resulting ELM:
```
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns="urn:hl7-org:elm:r1" xmlns:t="urn:hl7-org:elm-types:r1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fhir="http://hl7.org/fhir" xmlns:qdm43="urn:healthit-go
v:qdm:v4_3" xmlns:qdm53="urn:healthit-gov:qdm:v5_3" xmlns:a="urn:hl7-org:cql-annotations:r1">
   <annotation translatorOptions="" xsi:type="a:CqlToElmInfo"/>
   <identifier id="Test" version="1.0.0"/>
   <schemaIdentifier id="urn:hl7-org:elm" version="r1"/>
   <usings>
      <def localIdentifier="System" uri="urn:hl7-org:elm-types:r1"/>
      <def localIdentifier="USCore" uri="http://hl7.org/fhir/us/core" version="3.1.0"/>
   </usings>
   <contexts>
      <def name="Patient"/>
   </contexts>
   <statements>
      <def name="Patient" context="Patient">
         <expression xsi:type="SingletonFrom">
            <operand xmlns:ns0="http://hl7.org/fhir/us/core" dataType="ns0:PatientProfile" templateId="http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient" xsi:type="Retrieve"/>
         </expression>
      </def>
   </statements>
</library>
```

The ELM still contains `PatientProfile` for the `dataType` and has no mapping back to the base FHIR spec. This causes the CQL engine to break with this error: `ca.uhn.fhir.parser.DataFormatException: Unknown resource name "PatientProfile" (this name is not known in FHIR version "R4")`

With  the previous version of model info for USCore, the ELM instead was mapped back  to base FHIR (the USCore uri was the base FHIR uri, and  the data type was for `Patient`). The resulting ELM worked with the CQL engine.

This has left me with a couple questions:
* Was removing `targetUrl`,  `targetVersion`, and `target` for resources intentional?
* If so, is there a way to make the CQL to ELM translation layer still know how to map back to the base FHIR spec?

Thanks!

**Comment by brynrhodes** [comment]
Hi @msargentibm , apologies for the delays here. It wasn't so much an intentional removal as a level set to get the 1.5.0 initial release out. The "profile-informed ModelInfo" project is still in progress, and the USCore and QICore model infos are part of that. It's a high priority item we've been working on, and current state is that most things are working, but there are some cases where the slicing maps don't work as expected, and that results in the translator producing incorrect ELM.

**Comment by msargentibm** [comment]
Thanks for the information. Is it safe to say that the intention is to eventually populate the  `target*` fields in the model info again? I'm happy to patch my local copy of model info for the time being to enable testing if that's part of the plan going forward. I mostly did not want to rely on fields if they were disappearing for good.

**Comment by brynrhodes** [comment]
Hi @msargentibm , yes, definitely safe to say that's the proposed approach. The idea is that the ELM that is actually output from the translator will produce "pure FHIR" ELM (with profile references), so that systems can deal only with FHIR directly.

**Comment by msargentibm** [comment]
Thanks! That takes care of my questions. I'll close this issue out.
