### ISSUE TITLE
CQL-to-ELM Interval operator per argument null is not working as expected in v1.5

### ISSUE THREAD

**Issue by ds065598** [cqframework/clinical_quality_language#587]
I noticed that trying to add a null per to a collapse seems to throw an error. We do not expect it to throw an error in this scenario as its a valid use case of the collapse.
**CQL Code**
`define CollapseWithNullPer: collapse { Interval[1, 4], Interval[5, 8], Interval[7, 9] } null`

**Error message**
`ExceptionInfo Errors encountered while ELM generation:
[org.cqframework.cql.cql2elm.CqlSyntaxException: extraneous input 'null' expecting {<EOF>, 'define', 'context'}, org.cqframework.cql.cql2elm.CqlTranslatorException: extraneous input 'null' expecting {<EOF>, 'define', 'context'}]  clojure.core/ex-info (core.clj:4739)`

According to https://cql.hl7.org/09-b-cqlreference.html#collapse having a null in the per quantity field should work.
Also I noticed that if you give collapse an empty list it will also throw an error yet collapse is able to accept null when its not in a list.

example
**CQL code**
`define CollapseWithNullPer: collapse null //this works`
`define CollapseWithNullPer: collapse {null} //this doesnt work`

**Error message**
`ExceptionInfo Errors encountered while ELM generation:
[org.cqframework.cql.cql2elm.CqlInternalException: Internal translator error.]  clojure.core/ex-info (core.clj:4739)`

**Comment by brynrhodes** [comment]
The syntax for collapse includes a `per` keyword to provide the per argument to the collapse operator. It shouldn't be giving you an Internal Error though, should be a better error message, so I'm marking as a bug to address the unhelpful error message.

**Comment by brynrhodes** [comment]
This is related to known issue #435. Since there is a trivial workaround, deferring to vNext.

**Comment by brynrhodes** [comment]
Addressed in the 1.5.2 release
