### ISSUE TITLE
Add a "warning" when case-mismatching an identifier

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/clinical_quality_language#598]
If an identifier does not resolve but differs only in case from an existing identifier, include a mention of the case-insensitive match as a potential resolution.

JP: A failed resolution is a compile-time error, so the implementation of this story needs to enhance that error message. The current message doesn't include any message to potentially matching identifiers.

Luke:  The solution is to use conditional logic to select the error message depending on whether the identifiers were a case-insensitive match or didn't match at all.

**Comment by lukedegruchy** [comment]
Related or potentially related tickets:

https://github.com/cqframework/clinical_quality_language/issues/426
https://github.com/cqframework/clinical_quality_language/issues/607
https://github.com/cqframework/clinical_quality_language/issues/721
https://github.com/cqframework/clinical_quality_language/issues/1254
