### ISSUE TITLE
QDM 5.6 Model Info Discrepancies with QDM 5.6 Model Documentation

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#609]
After comparing the current QDM 5.6 Model Info File in Master to the QDM 5.6 documentation on eCQI, the following discrepancies have been found:

- Location entity type needs to be added for Prescriber attribute for two datatypes: 
  -	MedicationDischarge
  -	MedicationOrder
- DeviceApplied datatype is still in Model Info File, though it was removed from QDM 5.6
- Recorder attribute is still in Model Info File for Participation datatype, though it was removed from QDM 5.6
- Priority attribute is still in Model Info File for ProcedurePerformed datatype, though it was removed from QDM 5.6
- NegativeEncounterPerformed profile is still in Model Info File, but negationRationale was removed for "Encounter, Performed" datatype with QDM 5.6
- The negationRationale attribute is still available for the EncounterPerformed datatype in Model Info File, though it was removed with QDM 5.6.

**Comment by brynrhodes** [comment]
Addressed in the 1.5.2 release
