### ISSUE TITLE
How to define an external function returning a Tuple in CQL

### ISSUE THREAD

**Issue by dmartino88** [cqframework/clinical_quality_language#618]
I need to define and invoke an external function returning a Tuple object. How it is possible?
I try several solutions but I have syntax errors.
For example

**library ExamplePatientView version '0.0.1'
using FHIR version '4.0.0'
include FHIRHelpers version '4.0.0' called FHIRHelpers
define function MyCustomFunction() returns Tuple : external
context Patient
define myfunction: MyCustomFunction()**

Another solution that I tried was defining a new parameter tuple likes this:

**library ExamplePatientView version '0.0.1'
using FHIR version '4.0.0'
include FHIRHelpers version '4.0.0' called FHIRHelpers
parameter Info Tuple { city String, address String }
define function MyCustomFunction() returns Info : external
context Patient
define myfunction: MyCustomFunction()**

The validator gives me always syntax errors.
How Can solve my problem? I want to define an external function returning a Tuple where I know how the tuple consists of.
I also tried with 
`define function MyCustomFunction() returns Tuple<Info> : external`
but I have always the syntax error.

**Comment by brynrhodes** [comment]
Closing as resolved, feel free to re-open if you still have questions
