### ISSUE TITLE
CQL translator fails to compile "interval1 begins interval2"

### ISSUE THREAD

**Issue by csandersdev** [cqframework/clinical_quality_language#620]
Table 2-P under <a href="https://cql.hl7.org/02-authorsguide.html#comparing-intervals">5.5.2 Comparing Intervals</a> in the CQL author's guide says that CQL authors should be able to write an ``interval1 begins interval2`` comparison. When we try this in the sample below, it fails to compile. I think this is because the translator expects "starts" instead of "begins". This is probably just a documentation issue in the author's guide, but I'm calling it out here in case the author's guide is correct and the translator is wrong.

```cql
 library "IntervalBeginsInterval" version '1.0.0'
 
 define LHS:
 	Interval[@2020-07-04T12:00:00.000-05:00, @2021-07-04T12:00:00.000-05:00]
 
 define RHS:
 	Interval[@2020-07-04T12:00:00.000-05:00, @2022-07-04T12:00:00.000-05:00]
 
 define "LHS Begins RHS":
 	LHS begins RHS
```

**Comment by brynrhodes** [comment]
Hi @csandersdev , yes, this is an error in that diagram in the documentation, the grammar uses `starts` (it used to use `begins` when that diagram was actually created way back before the first ballot). So this is an issue with the specification. I'll log a tracker for it.

**Comment by brynrhodes** [comment]
Logged as [FHIR-31883](https://jira.hl7.org/browse/FHIR-31883)
