### ISSUE TITLE
Incorrect cardinality for prescriber attribute in QDM 5.6 modelinfo

### ISSUE THREAD

**Issue by adongare** [cqframework/clinical_quality_language#621]
Hello,

We are using qdm-modelinfo-5.6.xml to generate the models in Bonnie. It appears that `prescriber` attribute cardinality doesn't match with specification(https://ecqi.healthit.gov/sites/default/files/QDM-v5.6-508.pdf page number 67)
Resources: `MedicationOrder`, `MedicationDischarge`

As per spec it should be 0..* but modelinfo shows 0..1. I think it should be list of choicetypes or am I misinterpreting it? 

Could someone please take a look?  

Thanks!

**Comment by brynrhodes** [comment]
Addressed in 1.5.3. release
