### ISSUE TITLE
QDM 5.0 Model Info 

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#63]
Questions about the following file: https://github.com/cqframework/clinical_quality_language/tree/modelinfo-profiles/Src/java/qdm/src/main/resources/gov/healthit/qdm/qdm-modelinfo-5.0.xml

**First:** The file contains the following label values for the patient characteristic datatypes:

- Patient Characteristic: Birthdate
- Patient Characteristic: Clinical Trial Participant
- Patient Characteristic: Ethnicity
- Patient Characteristic: Expired
- Patient Characteristic: Payer
- Patient Characteristic: Race
- Patient Characteristic: Sex

Based on the draft QDM 5.0 document (https://ecqi.healthit.gov/system/files/qdm_5_0_draft_.pdf), none of these datatypes contain colons.
 
**Second:** It appears that the generic "Patient Characteristic" datatype is missing from the model info file. Since this datatype is part of QDM 5.0, how is this datatype being handled?
 
**Third:** There is a typo for the DeviceApplied element anatomialLocationSite - should be anatomi**c**alLocationSite

**Comment by brynrhodes** [comment]
Agreed on all counts, thank you for the detailed review. These changes have been made to the 5.0 and 5.0.1 xsd and model info files.
