### ISSUE TITLE
MeasureReport primaryCodePath in modelinfo should not be measure.topic

### ISSUE THREAD

**Issue by p9g** [cqframework/clinical_quality_language#637]
CQL Retrieve [MeasureReport:"SomeValueSet"] returns an error "Could not resolve code path measure.topic for the type of the retrieve FHIR.MeasureReport"

MeasureReport.measure is a canonical, essentially a reference to a Measure.url
MeasureReport.measure.topic does not make sense for the primaryCodePath for MeasureReport since it would need to retrieve the Measure then check Measure.topic.

suggest MeasureReport.type should be the primaryCodePath

**Comment by brynrhodes** [comment]
Agree that makes sense as the primary code path.

**Comment by brynrhodes** [comment]
Included in 1.5.6 release
