### ISSUE TITLE
FHIR Model Info - Primary Code Path for Communication

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#638]
The primary code path in the FHIR 4.0.1 model info file (and earlier) for the Communication type is set to category. However, [QDM-to-QICore](http://hl7.org/fhir/us/qicore/qdm-to-qicore.html#871-communication-performed) maps the QDM Communication, Performed primary code path to reasonCode, and the [errata documentation](https://confluence.hl7.org/pages/viewpage.action?pageId=97467459#QDM5.6MappingtoQICore[Draft]-8.7Communication) in HL7 Confluence retains this mapping. Based on a read of the specification, it seems that reasonCode should be the primary code path in the model info file. Thoughts?

**Comment by brynrhodes** [comment]
Agree that the primary code path should be reasonCode, based on the QDM-to-QICore mapping. Marking this as an enhancement for inclusion in the next release.

**Comment by brynrhodes** [comment]
Included in 1.5.6 release
