### ISSUE TITLE
Support JSON as a serialization format for ModelInfo

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/clinical_quality_language#640]
The translator currently only supports XML deserialization of model info, which means there is not a good story for deserialization of model info files in the Android space, which effectively prevents the translator from being used in an Android environment.

**Comment by fredhersch** [comment]
@brynrhodes Is this still open? Or now resolved?

**Comment by brynrhodes** [comment]
Hi @vitorpamplona , we can't abandon it but we can restructure the dependencies, that's the next step here, to separate out the "hardcoded" nature of the modelinfo loading and make sure we can do it dynamically. One easy thing we can try (and I just haven't yet) is to see if the Jackson library actually can deserialize the XML modelinfo. Modelinfo is a much simpler structure, so it may just work (The reason we can't use the ELM XML is because it has the JAXB dependencies, not because we can't deserialize XML at all, right?)

**Comment by vitorpamplona** [comment]
I am happy to report that it largely works. But I am having a hard time figuring out what is wrong with the USCore and QICore packages. 

![Screen Shot 2022-05-03 at 5 26 33 PM](https://user-images.githubusercontent.com/532031/166569337-edef3790-1556-4fd8-a413-f801cb1da83d.png)

**Comment by vitorpamplona** [comment]
All good! PR #745 is ready for a review. 

Noticed that: 
1 - There were types on the modelinfo files: `primaryCocdePath` and `primaryCOdePath` (Jackson XML is case sensitive)
2 - There is a bug that requires `xsi:type` to be the first property on XML elements with polymorphic nested objects.
