### ISSUE TITLE
Alphanumeric versions not allowed on included libraries

### ISSUE THREAD

**Issue by jward-123** [cqframework/clinical_quality_language#641]
Hi,

I have a test library using a mix of alphanumeric characters e.g. "Lib2020". The translator will throw the following error when including a library with this type of version:

![2021-05-19 08_39_29-Window](https://user-images.githubusercontent.com/83230317/118822519-dc37cf80-b87d-11eb-8ed2-6e25538ad8ac.png)

Note it doesn't restrict the version on the library being translated itself, just the libraries it includes. It does allow special characters like ".". I don't see this kind of restriction in the CQL handbook. Should it exist?

**Comment by brynrhodes** [comment]
@jward-123 , no, you are correct, the spec is intentionally silent on version formats, so the translator should not be requiring this... marking as an issue. Is this blocking for you?

**Comment by jward-123** [comment]
Thanks Bryn! No it's not blocking. Right now I have a work around to replace the version with a placeholder before and after the translation.

**Comment by brynrhodes** [comment]
Included in v1.5.7
