### ISSUE TITLE
cql-formatter Main produces unusable output

### ISSUE THREAD

**Issue by csandersdev** [cqframework/clinical_quality_language#652]
I was playing around with the tools/cql-formatter project and noticed that when you run the main method, it produces unusable output.

```
$ ./cql-formatter dummy.cql
org.cqframework.cql.tools.formatter.CqlFormatterVisitor$FormatResult@2dff7085
```

The code either needs to implement toString on FormatResult or interrogate the FormatResult in main and handle as needed.

**Comment by brynrhodes** [comment]
Included in 1.5.4-SNAPSHOT
