### ISSUE TITLE
Concatenating Comments to Defines in ELM XML

### ISSUE THREAD

**Issue by jkotanchik-SB** [cqframework/clinical_quality_language#657]
For FHIR and QDM measures, the XML generated by the Translator (1.5.2, 1.5.3, 1.5.4) is concatenating line and block comments to the following define statement which causes the define declaration to appear commented out in the ELM.

### Example CQL:
![Screen Shot 2021-07-06 at 11 35 05 AM](https://user-images.githubusercontent.com/56264529/127700057-20fb97f2-4162-48da-af58-285bce3032d8.png)

### Generated XML ELM:
![Screen Shot 2021-07-06 at 11 36 07 AM](https://user-images.githubusercontent.com/56264529/127700075-b89c2cd9-c653-4cff-b350-b7fdd4ea5144.png)

### Generated JSON ELM with the comment separated within the Array:
![Screen Shot 2021-07-06 at 11 39 02 AM](https://user-images.githubusercontent.com/56264529/127700099-f7f2f3cd-a8dc-42f8-964d-5ec518d6381f.png)

**Comment by jkotanchik-SB** [comment]
@mdnazmulkarim

Thanks for checking out this issue! 

> When translator option EnableNarrative is on, in the annotation narrative it includes comments and function definitions which is normal.

I'm not sold that general CQL comments should be included in the ELM annotation narratives. In version `1.4.x` , only the CQL text was included in the ELM annotation narrative when the `EnabledAnnotations` was set (I couldn't find any EnableNarrative option).  Though, I have yet to find a source defining ELM annotation narratives, I am not aware of an explicit change in what is expected in the narrative. 

Was an issue reported requesting general CQL comments be added to the annotation narrative? Or perhaps some change in the CQL 1.5 specification that encouraged general comments be added?

Perhaps @brynrhodes or @cmoesel can clarify the expected contents of an ELM annotation narrative, or if you happen to know of a spec/issue/conversation covering the term, please let me know!

**Comment by brynrhodes** [comment]
The ELM specification supports registering annotations to extend the base ELM functionality, including the source CQL for an expression as an annotation is part of that extended functionality. The original intent when we worked out this functionality with the tooling and measure stakeholders was to include the entire text of the definition (i.e. everything from the end of the previous definition to the beginning of the current one), which would capture comments if they were present in the CQL source. So it wasn't that CQL comments should be included, it was a fix that sometimes CQL comments weren't being included when they should have been. If there is a need, we could look at introducing a translator option to cover whether or not they are included.

**Comment by brynrhodes** [comment]
Included in 1.5.5 Release
