### ISSUE TITLE
Add an option to the LibraryManager to enable caching

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/clinical_quality_language#667]
In an authoring environment, caching of libraries is undesirable since the content of those libraries is changing frequently. Add library caching as an option in the LibraryManager to allow authoring environments to disable the functionality.

**Comment by JPercival** [comment]
One consideration here is that certain platforms may need to be able to expire the cache externally. For example, if there's a resident global LibraryManager in a HAPI FHIR server, updates to Library resources should expire the LibraryManager cache.

The cql-evaluator and HAPI fhir server implemented this behavior by providing a cache-aware wrapper for the LibraryManager.

**Comment by brynrhodes** [comment]
Included in 1.5.6 release
