### ISSUE TITLE
SNAPSHOT-1.1.0 mistranslation of Exp and removal of Implies operator

### ISSUE THREAD

**Issue by c-schuler** [cqframework/clinical_quality_language#69]
I am experiencing a similar issue as the Time(x.x.x...) issue I posted back in June. The Exp operation is being translated as a function reference instead of a Exp expression. This is not an issue with the 1.2.0 SNAPSHOT. Also, has the _implies_ operation been removed from the language? I do not see it in the expression.xsd...

**Comment by brynrhodes** [comment]
This issue has been corrected in the 1.1 translator, but not verified in a unit test, so I added a unit test.

**Comment by brynrhodes** [comment]
Also, the `implies` operator is being added in CQL 1.2, it is not defined for CQL 1.1.
