### ISSUE TITLE
Refactor ELM node tracking to use a `decorate()` method on an ObjectFactoryEx

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/clinical_quality_language#697]
Right now all tracking logic goes through the track() method of the visitor. But since the creation of elements happens largely in the builder, only top-level elements that are returned from the builder get piped through the track() method. (This also applies to localId assignment as part of the narrative management logic). The result is that intermediate nodes created by the builder don't get tracked or decorated appropriately, and the is the reason for issues like #405 and #395. To address this problem generally, introduce an ObjectFactoryEx that calls a decorate() method on each constructed ELM node as part of the creation. Then define an interface to support decoration:
```
IELMDecorator {
  Element decorate(Element)
}
```
And then have the visitor provide an implementation of decorator to the ObjectFactoryEx that calls the track method.

**Comment by JPercival** [comment]
Related to https://github.com/cqframework/clinical_quality_language/issues/1279, https://github.com/cqframework/clinical_quality_language/issues/1131, https://github.com/cqframework/clinical_quality_language/issues/704, https://github.com/cqframework/clinical_quality_language/issues/697
