### ISSUE TITLE
Handling localId creation differently

### ISSUE THREAD

**Issue by mdnazmulkarim** [cqframework/clinical_quality_language#704]
Based on Bryn's comment on [PR](https://github.com/cqframework/clinical_quality_language/pull/677)
We need a tweak to the ObjectFactory to decorate ELM nodes as they are creating, rather than trying to react to them being created in all the different places that they are.  Logging a tracker to add an ObjectFactoryEx pattern with a decorate() method that gets called on each node as it is created by the factory.

**Comment by JPercival** [comment]
Related to #1279 and #1131
