### ISSUE TITLE
Does this project or its dependencies use log4j?

### ISSUE THREAD

**Issue by StephenBoydMCG** [cqframework/clinical_quality_language#706]
As you may have already heard, there's a major vulnerability in one of the most popular Java logging frameworks, log4j.

https://logging.apache.org/log4j/2.x/

Does this project or any of its dependencies use log4j?

**Comment by brynrhodes** [comment]
Thank you @StephenBoydMCG We don't use log4j in this project, but we do in several of the other Java dependencies. As of this point those dependencies are all either already addressed or in progress to be addressed.
