### ISSUE TITLE
Type name DateTime is ambiguous between DateTime and System.DateTime.

### ISSUE THREAD

**Issue by jackcmeyer** [cqframework/clinical_quality_language#71]
Found an issue while running the following through the updated CQL-to-ELM translator: 

`parameter "Measurement Period" Interval<DateTime>`

The following errors occur: 
`[13:41, 13:48] Type name DateTime is ambiguous between DateTime and System.DateTime.
[13:32, 13:49] org.hl7.elm.r1.Null cannot be cast to org.hl7.elm.r1.TypeSpecifier
[13:1, 13:49] org.hl7.elm.r1.Null cannot be cast to org.hl7.elm.r1.TypeSpecifier`

Per spec, this should be allowed. If I update to the following, the translator does not error: 

`parameter "Measurement Period" Interval<System.DateTime>`

Thoughts?

**Comment by brynrhodes** [comment]
The problem was that there were some incorrect redeclarations of primitive types in the QDM model info, resulting in the ambiguous types being present in the model. I've fixed the model info for QDM 5.0 and 5.0.1.
