### ISSUE TITLE
QDM Datatype "Encounter, Active" Retrievable Set to False

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#72]
In the QDM 5.0 and QDM 5.0.1 Model Info Files, the retrievable is set to "false" for "Encounter, Active":

`<ns4:typeInfo xsi:type="ns4:ClassInfo" name="QDM.EncounterActive" retrievable="false" baseType="QDM.QDMBaseType" label="Encounter, Active">`

"Encounter, Active" is a datatype in QDM 5.0. Shouldn't this be set to "true"?

Also noticed that the reason attribute was not available for the Patient Characteristic Clinical Trial Participant in the qdm-modelinfo-5.0.xml and qdm-modelinfo-5.0.1.xml files. This attribute is in QDM for this datatype. 

Also noticed that the type attribute was not available for the Adverse Event in the qdm-modelinfo-5.0.xml and qdm-modelinfo-5.0.1.xml files. This attribute is in QDM for this datatype.

**Comment by JSRankins** [comment]
Created three pull requests to update the following files:
qdm-modelinfo-5.0.xml (75)
qdm-modelinfo-5.0_withNegationTypes.xml (74)
qdm-modelinfo-5.0.1.xml (73)

**Comment by brynrhodes** [comment]
I merged the pulls and added the reason element to the QDM 5.0 xsds.
