### ISSUE TITLE
Issue with QICore 4.1.0 model

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#724]
Good afternoon. I was doing a little bit of work with [QICore model info file 4.1.0](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/quick/src/main/resources/org/hl7/fhir/qicore-modelinfo-4.1.0.xml) today and noticed that Encounter.diagnosis was returning as a QICore.Encounter.diagnosis type and not a List<QICore.Encounter.diagnosis>. Based on QICore profile, Encounter.diagnosis has cardinality 0..*. Refer to https://build.fhir.org/ig/HL7/fhir-qi-core/StructureDefinition-qicore-encounter.html. 

I have not looked to see if there are any other issues, but I will let you know if I find any.

**Comment by brynrhodes** [comment]
Included in 1.5.12 and 2.2.0
