### ISSUE TITLE
Dynamic model info loading

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/clinical_quality_language#751]
ModelInfo is currently loaded statically, refactor this to support dynamic loading using the ServiceLoader pattern.

**Comment by vitorpamplona** [comment]
Also, we need a solution for [this](https://github.com/FasterXML/jackson-dataformat-xml/issues/525) before loading dynamic model infos.

**Comment by JPercival** [comment]
Also needed for profile-informed authoring. This would allow authors of an IG to define StructureDefinitions to represent the specific types and properties they need for their use case.

**Comment by brynrhodes** [comment]
Included in v2.0.0
