### ISSUE TITLE
ELM should include patch digit in CQL-to-ELM translator version

### ISSUE THREAD

**Issue by p9g** [cqframework/clinical_quality_language#753]
https://github.com/cqframework/clinical_quality_language/issues/345 requested adding the version, but apparently the implementation only adds the major.minor version, such as` translatorVersion="1.5"`

Request adding the patch digit, e.g., ` translatorVersion="1.5.8`" where "8" is the patch digit.
Probably ok to implement this starting with "2.0.0" and newer of the CQL-to-ELM translator.

**Comment by brynrhodes** [comment]
Addressed in v2.0.0
