### ISSUE TITLE
Allow same libraries with different versions to resolve

### ISSUE THREAD

**Issue by csenn** [cqframework/clinical_quality_language#756]
Hey, thanks again for this library, it's been a great learning experience going through this source.

I am working on a project that uses namespaces. And in the case of:

```
library name_space_one.LibraryOne version 0.0.1

include cq_core.FHIRHelpers version '4.0.1' called FHIRHelpers
include name_space_two.LibraryTwo 
```

**Comment by JPercival** [comment]
Related open issue: #758 (same topic).
