### ISSUE TITLE
CQL-to-ELM Validation Issue Related to Undeclared Definitions

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#77]
The following passes CQL-to-ELM validation:

```
library Hello

using QDM versino '5.0'

context Patient 

define "Initial Population":
    exists(Encounter) //note: the reference to the Encounter definition does not include quotes

```

Note that Encounter is not declared anywhere - just "Encounter". Is there a plan to update CQL-to-ELM to provide validation around use of non-declared items in CQL? If so, when?

**Comment by brynrhodes** [comment]
In CQL, there is no difference between the identifiers "Encounter" and Encounter. In other words, the double-quotes are not part of the identifier, they are just a syntactic construct to allow you to construct identifiers that contain things like spaces that would not be valid otherwise.
