### ISSUE TITLE
Multiple Resource or Profile Related TypeInfo Elements Missing Primary Code Path in QI-Core 4.1.1 Model Info File

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#789]
A number of FHIR Resource or Profile related typeInfo elements are missing a primaryCodePath in [QI-Core 4.1.1 Model Info File](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/quick/src/main/resources/org/hl7/fhir/qicore-modelinfo-4.1.1.xml). As a result, this missing data does not get put out to ELM and appears to cause problems when executed (e.g., in Visual Studio Clinical Quality Language plugin). Examples would include the typeInfo elements for the negative datatypes like MedicationNotRequested, ImmunizationNotDone, CommunicationNotDone, etc., as well as some of the more obscure resources where a primaryCodePath may not be readily apparent like BodyStructure, FamilyMemberHistory, RelatedPerson, Location, etc.

**Comment by brynrhodes** [comment]
Included in 1.5.12 and 2.2.0
