### ISSUE TITLE
cql-execution port to ES6...

### ISSUE THREAD

**Issue by turp1twin** [cqframework/clinical_quality_language#80]
I have nothing against Coffeescript, but its future as a language has been debated as of late (due to ES6, ES7, babel, etc)... I have ported the cql-execution engine (and all tests) to ES6, which even with decaffeinate was more work than one might think! Not sure if you are interested, but I am willing to contribute it if you want it.. If not, no big deal, just thought I would offer it up... I currently have it in a private repo, but will open it up if there is any interest. Cheers!

Jeff

**Comment by cmoesel** [comment]
Hi Jeff,

I think this sounds awesome.  After taking a long break from anything Javascript related, I've recently come back and found that I *really* like ES6 -- and some of the great tooling that's been built around ES6.  If I was writing cql-execution today, I'd certainly write it in ES6!

That said, we have a team that's already invested in the Coffeescript version (and is using Coffeescript elsewhere in their app).  They are a bit reluctant, at this point, to take on the risk of a full translation into ES6.  That may change, but that seems to be where things stand now.

But... I'd personally love to see your ES6 implementation.  Any chance you could grant me access so I could poke around and see how it works?

**Comment by turp1twin** [comment]
Hey Chris,

Yeah, sounds good. I will give you access. It is still a work in progress, and there are a few bits that I still need to work out. That being said, I tried to stay as close to the structure you have in the coffee project, but might start to reorganize things a bit more... Anyways, have a play...

Jeff

**Comment by seanknox** [comment]
Hey @turp1twin, the [Able Health team](https://github.com/AbleHealth) would love to participate if possible. Shoot me an email if you're interested: knoxville@ablehealth.com.

**Comment by turp1twin** [comment]
Hey @seanknox, glad to get you involved. Will send you an email with some details...

Jeff

**Comment by preston** [comment]
+1 to either ES6 or TypeScript-based canonical version. CoffeeScript was great while it lasted, but just isn't needed anymore.

**Comment by preston** [comment]
@turp1twin Hi Jeff: any chance you may be able to make your version of the project available soon?

**Comment by turp1twin** [comment]
Hey @preston I'll open it up later today. That being said, it needs some love, looking forward to contributions....

**Comment by preston** [comment]
@turp1twin Right on... do you think it's in a functional enough state to be suitable for npm packaging/release as well?

For context, I'm a contributor to the [CQF Knartwork](https://github.com/cqframework/knartwork) project, and would love to be able to integrate these libraries either directly or through a web service interface.

**Comment by turp1twin** [comment]
@preston The unit tests all run, but that is about all I have done with it so far. My day job has been keeping me crazy busy. The readme definitely needs updating for sure, before doing an NPM release....

**Comment by turp1twin** [comment]
@preseton the repository is public now...

**Comment by rdingwell** [comment]
@preston as long as the port didn't change any of the api name spacing or method signatures you should be able to get started with the cql-execution npm package that is already published and built from the coffeescript version of the library.  

https://www.npmjs.com/package/cql-execution

**Comment by brynrhodes** [comment]
This issue was moved to cqframework/cql-execution#47
