### ISSUE TITLE
The private keyword should make methods private

### ISSUE THREAD

**Issue by EvanMachusak** [cqframework/clinical_quality_language#821]
In library 'a':
```
define private function "Private function"(): true
```
In library 'b':

```
include 'a' called a
define "works but should not": a."Private function"()
```

The private access modifier is correctly assigned in the ELM, but library 'b' still transpiles without warnings, let alone errors.

**Comment by brynrhodes** [comment]
Agreed, and surprised this is happening, the translator definitely has code to check this, so I'm not sure what's happening. Will investigate.
