### ISSUE TITLE
modelinfo qicore servicerequest primarycodepath

### ISSUE THREAD

**Issue by p9g** [cqframework/clinical_quality_language#828]
`   <typeInfo xsi:type="ClassInfo" baseType="QICore.DomainResource" namespace="QICore" name="ServiceRequest" identifier="http://hl7.org/fhir/us/qicore/StructureDefinition/qicore-servicerequest" label="ServiceRequest" retrievable="true" primaryCodePath="type">`

Since ServiceRequest does not define a "type" element, the primaryCodePath in the line above from the [qicore-modelinfo-4.1.1.xml](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/quick/src/main/resources/org/hl7/fhir/qicore-modelinfo-4.1.1.xml) should be changed to "code" to align with the FHIR 4.0.1 modelinfo.

**Comment by mdnazmulkarim** [comment]
Related PR:
https://github.com/cqframework/clinical_quality_language/pull/1114
