### ISSUE TITLE
modelinfo for qicore 5.0.0 needed

### ISSUE THREAD

**Issue by p9g** [cqframework/clinical_quality_language#838]
https://github.com/cqframework/clinical_quality_language/tree/master/Src/java/quick/src/main/resources/org/hl7/fhir currently does not have a modelinfo for qicore 5.0.0.

See also https://jira.hl7.org/browse/FHIR-37579

**Comment by JSRankins** [comment]
@brynrhodes, I believe the plan was to remove model info with Translator 2.x version. I know that hasn't happened yet. Was the plan to do that beginning with QI-Core 5.0.0?
