### ISSUE TITLE
[Help Wanted] Updating cql-translation-service to use 2.3.0 stack

### ISSUE THREAD

**Issue by mgramigna** [cqframework/clinical_quality_language#839]
Hi @brynrhodes  @JPercival,

I am trying to update https://github.com/cqframework/cql-translation-service to use the latest 2.3.0 stack of cql-to-elm (and dependencies). I was specifically hoping for some insight on the new Model Info loading logic for 2.3.0 and where I might be going wrong in my approach.

 The changes that I made in the service can be viewed here: https://github.com/mgramigna/cql-translation-service/commit/ee28aa5bf807f0f9c1dcd9296bc06ba67f2c8b77. Specifically, [this line](https://github.com/mgramigna/cql-translation-service/commit/ee28aa5bf807f0f9c1dcd9296bc06ba67f2c8b77#diff-8bd3de99e180f632c87017c326d4ce9336752ee6e69d04d3ae77a545e24249a0R103) is what I want to inquire about, which I modeled after a [similar line in the cql-to-elm-cli project](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/cql-to-elm-cli/src/main/java/org/cqframework/cql/cql2elm/cli/CqlTranslator.java#L76).

Interestingly, I am seeing the following behavior:

* When running the translation service locally with `mvn exec:java`, I have no issues translating any CQL
* When building the jar with `mvn package` and running `java -jar target/cqlTranslationServer-2.3.0-jar-with-dependencies.jar`, I get a 400 Bad request with the following error:

```
{
  "libraryId": "Test",
  "startLine": 3,
  "startChar": 1,
  "endLine": 3,
  "endChar": 26,
  "message": "Could not resolve model info provider for model FHIR, version 4.0.1.",
  "errorType": "semantic",
  "errorSeverity": "error",
  "type": "CqlToElmError"
}
```

Here is the request used to replicate: 

```
curl --request POST \
  --url 'http://localhost:8080/cql/translator?annotations=true&=' \
  --header 'Content-Type: application/cql' \
  --header 'accept: application/elm+json' \
  --data 'library Test

using FHIR version '\''4.0.1'\''

context Patient

define "Example":
  [Encounter]'
```

In addition, I found the following to be of interest:

``` Java
// WORKS LOCALLY
// DOES NOT WORK IN JAR
modelManager.getModelInfoLoader().registerModelInfoProvider(new DefaultModelInfoProvider(cql.toPath().getParent()));

// WORKS LOCALLY
// WORKS IN JAR
modelManager.getModelInfoLoader().registerModelInfoProvider(new FhirModelInfoProvider());
modelManager.getModelInfoLoader().registerModelInfoProvider(new QICoreModelInfoProvider());
// ...
```

If I load the `ModelInfoProvider`s manually, there are no issues at all. I wonder if there is something weird going on with file paths in the jar in the case of `DefaultModelInfoProvider`

NOTE: I am testing locally with Java 11, and the `.jar` is built targeting Java 11 as well

**The Question**:

Can you think of anything (perhaps related to file paths or something) with the default model info loading behavior that would potentially cause the translator to not be able to resolve the model info specifically in an "uber-jar" environment packaged with the `maven-assembly-plugin`? Am I missing something obvious?

Any thoughts would be appreciated!

**Comment by JPercival** [comment]
The cql-translator was recently refactored to load ModelInfo providers at runtime via ServiceLoaders. This was done to make supporting loading different serializers dynamically on Android and other platforms. The short version is that you need to explicitly add dependencies to the packages that contain the ModelInfos you want to load, and to a serializaton library appropriate for your platform. The standard jaxb serializers out to work on the translation service. Something like this out to do the trick:

```
  <dependency>
            <groupId>info.cqframework</groupId>
            <artifactId>model-jaxb</artifactId>
    </dependency>
    <dependency>
        <groupId>info.cqframework</groupId>
        <artifactId>elm-jaxb</artifactId>
    </dependency>
    <dependency>
        <groupId>org.eclipse.persistence</groupId>
        <artifactId>org.eclipse.persistence.moxy</artifactId>
    </dependency>
     <dependency>
            <groupId>info.cqframework</groupId>
            <artifactId>quick</artifactId>
    </dependency>
 ```

**Comment by JPercival** [comment]
For reference:

https://github.com/cqframework/clinical_quality_language/pull/770
https://github.com/cqframework/clinical_quality_language/issues/751

**Comment by mgramigna** [comment]
🤦 Thanks, @JPercival! I was missing `org.eclipse.persistence.moxy`, which seemed to finally do the trick (I must've had it locally or something that didn't cause errors... no idea.

Closing

**Comment by mgramigna** [comment]
Whoops, I initially closed because I thought this had fixed it, but I still had code locally that loaded the ModelInfo providers individually.

My `pom.xml` does have the above and allows it to work locally, it's just this dang `.jar` :/

What strategy does the dynamic ModelInfo loading take? Can you think of any reason the smart resolution wouldn't work in a mvn packaged jar?

**Comment by mgramigna** [comment]
We resolved this over in https://github.com/cqframework/cql-translation-service/pull/34. Closing this as it is no longer an issue
