### ISSUE TITLE
checkout fails on git/windows

### ISSUE THREAD

**Issue by fhirfly** [cqframework/clinical_quality_language#865]
I get this while cloning your repo in Windoze
error: unable to create file engine.jaxb/src/test/resources/org/opencds/cqf/cql/engine/execution/ElmTests/Regression/qdm/CoronaryArteryDiseaseCADBetaBlockerTherapyPriorMyocardialInfarctionMIorLeftVentricularSystolicDysfunctionLVEF40-8.2.000.cql: Filename too long
error: unable to create file engine.jaxb/src/test/resources/org/opencds/cqf/cql/engine/execution/ElmTests/Regression/qdm/CoronaryArteryDiseaseCADBetaBlockerTherapyPriorMyocardialInfarctionMIorLeftVentricularSystolicDysfunctionLVEF40-8.2.000.json: Filename too long
error: unable to create file engine.jaxb/src/test/resources/org/opencds/cqf/cql/engine/execution/ElmTests/Regression/qdm/CoronaryArteryDiseaseCADBetaBlockerTherapyPriorMyocardialInfarctionMIorLeftVentricularSystolicDysfunctionLVEF40-8.2.000.xml: Filename too long
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by JPercival** [comment]
Readme updated.
