### ISSUE TITLE
Map ELM to Evaluator ELM without export/import into JSON/XML

### ISSUE THREAD

**Issue by vitorpamplona** [cqframework/clinical_quality_language#868]
Currently, the engine uses a JSON mapper to compile CQL into evaluation-ready elm classes. All tests run a similar line to this: 

```java
CqlTranslator translator = CqlTranslator.fromFile(cqlFile, .... );
JsonCqlLibraryReader.read(translator.toJxson());
```

We have to find a way to directly compile CQL into evaluation classes to improve performance and memory use.

**Comment by JPercival** [comment]
No longer needed, engine and compiler share ELM graph
