### ISSUE TITLE
Aggregate function always returns the source list.

### ISSUE THREAD

**Issue by dand9959** [cqframework/clinical_quality_language#883]
The cql aggregate function appears to always return the source list, unaltered, regardless of the parameters given to it.

For example, take:

({ 1, 2, 3, 4, 5 }) Num
    aggregate Result starting 1: Result * Num

This will return the array {1, 2, 3, 4, 5] rather than the expected value of 120. 

Similarly, other more complicated expressions after the ":"  still just return the input source as an array of original values.

Ref:   CqlAggregateTest.xml

**Comment by JPercival** [comment]
Resolved by #1271
