### ISSUE TITLE
FHIRHelpers source should be included by default as part of the FHIR model

### ISSUE THREAD

**Issue by nkarip** [cqframework/clinical_quality_language#89]
CQL-to-ELM translation fails with error "Could not resolve library name FHIRHelpers" if library is not included in current working directory. Per Bryn, FHIRHelpers source should be included by default as part of the FHIR model so that the libraries don't have to be distributed.

**Comment by brynrhodes** [comment]
Released in v1.1.1-SNAPSHOT
