### ISSUE TITLE
travis build uses openjdk11

### ISSUE THREAD

**Issue by deekim** [cqframework/clinical_quality_language#944]
I don't know if this is necessarily a problem, but I saw:
```yaml
jdk: openjdk11
```
in the [.travis.yml](https://github.com/DBCG/cql_engine/blob/master/.travis.yml#L3)

but
```xml
<configuration>
    <source>1.8</source>
    <target>1.8</target>
    <release>8</release>
</configuration>
```
in the [pom.xml](https://github.com/DBCG/cql_engine/blob/master/pom.xml#L317-L321)

and wanted to double-check this was intentional?

**Comment by JPercival** [comment]
Migrated to Github actions
