### ISSUE TITLE
Add links to local identifiers in ELM to the annotation narrative

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/clinical_quality_language#95]
Due to issues #86 and #61, links to local identifiers in the ELM were removed from the annotation narrative. This issue is a request to add them back in, pending implementer feedback that it is an important/desired feature.

**Comment by edeyoung** [comment]
This is a desired feature. Thanks!

**Comment by brynrhodes** [comment]
Addressed by pull request #122.
