### ISSUE TITLE
Support aggregate query clause

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/clinical_quality_language#970]
CQL 1.5 added an aggregate clause to the query:
https://cql.hl7.org/2020May/03-developersguide.html#aggregate-queries

**Comment by NataliaSmileDigital** [comment]
This is a priority community request.

**Comment by NataliaSmileDigital** [comment]
JP handed this off to Nazmul.

**Comment by JPercival** [comment]
Resolved by #1271
